// Generated by `canopus target generate-rust-bindings`. DO NOT EDIT.
//
// target_id: xiaomi-band-11-4.100.139
// firmware : 4.100.139 (user-4.100.139-cn-202608280000)
// sha256   : 31ce82257f7c127950dc5070b86316730cf468a41f0d004559e41e7d923b2c74
// revision : 2
// input_digest: 106948186347f602
//
// All firmware calls are `unsafe`; safe wrappers exist only
// where the ABI and ownership have been proven (architecture §12.1).

/// Converts a recovered Thumb entry or callable address into the only valid
/// indirect-call address. Target-private ABI adapters must use this instead
/// of transmuting raw firmware addresses directly.
#[inline(always)]
pub const fn canopus_thumb_callable(entry_or_callable: usize) -> usize {
    entry_or_callable | 1usize
}

// ---- recovered type layouts ----
// `#[repr(C, packed(N))]` + explicit padding reproduces the exact
// recovered byte layout and its target-declared alignment.
pub type canopus_interconnect_recv_cb = extern "C" fn(*mut core::ffi::c_void, i32, *const canopus_interconnect_message, *const u8) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct file_operations {
    pub open: *mut core::ffi::c_void, // +0x0
    pub close: *mut core::ffi::c_void, // +0x4
    pub read: *mut core::ffi::c_void, // +0x8
    pub write: *mut core::ffi::c_void, // +0xc
    pub lseek: *mut core::ffi::c_void, // +0x10
    pub ioctl: *mut core::ffi::c_void, // +0x14
    pub _tail: [u8; 0x18], // 24
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_order_record {
    pub app_name: [u8; 128], // +0x0
    pub _pad_80: [u8; 0x4], // 4
    pub flags: u32, // +0x84
    pub _tail: [u8; 0x4], // 4
}

pub type canopus_lvx_event_cb = extern "C" fn(*mut core::ffi::c_void) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct stock_timespec_t {
    pub tv_sec: i64, // +0x0
    pub tv_nsec: i32, // +0x8
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_thirdparty_message_content {
    pub message_id: u32, // +0x0
    pub message_kind: u16, // +0x4
    pub _pad_6: [u8; 0xa], // 10
    pub package_name: *mut core::ffi::c_void, // +0x10
    pub fingerprint_blob: *mut core::ffi::c_void, // +0x14
    pub payload_blob: *mut core::ffi::c_void, // +0x18
    pub _tail: [u8; 0x134], // 308
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct firmware_page_descriptor {
    pub parent_descriptor: *mut core::ffi::c_void, // +0x0
    pub _pad_4: [u8; 0xc], // 12
    pub page_name: *mut core::ffi::c_void, // +0x10
    pub page_id: u16, // +0x14
    pub app_id: u16, // +0x16
    pub flags: u16, // +0x18
    pub _pad_1a: [u8; 0x2], // 2
    pub scheduler_deadline: i32, // +0x1c
    pub scheduler_priority: i32, // +0x20
    pub async_destroy_state: u32, // +0x24
    pub lifecycle_state: u8, // +0x28
    pub layer: u8, // +0x29
    pub page_kind: u8, // +0x2a
    pub _pad_2b: [u8; 0x1], // 1
    pub activity_context: *mut core::ffi::c_void, // +0x2c
    pub root_object: *mut core::ffi::c_void, // +0x30
    pub on_signal: *mut core::ffi::c_void, // +0x34
    pub runtime_default_56: *mut core::ffi::c_void, // +0x38
    pub _pad_3c: [u8; 0x4], // 4
    pub registry_prev: *mut core::ffi::c_void, // +0x40
    pub registry_next: *mut core::ffi::c_void, // +0x44
    pub runtime_parent: *mut core::ffi::c_void, // +0x48
    pub on_create: *mut core::ffi::c_void, // +0x4c
    pub on_resume: *mut core::ffi::c_void, // +0x50
    pub on_foreground_data: *mut core::ffi::c_void, // +0x54
    pub extension_callback_88: *mut core::ffi::c_void, // +0x58
    pub on_pause: *mut core::ffi::c_void, // +0x5c
    pub on_stop: *mut core::ffi::c_void, // +0x60
    pub on_ui_destroy: *mut core::ffi::c_void, // +0x64
    pub extension_callback_104: *mut core::ffi::c_void, // +0x68
    pub extension_callback_108: *mut core::ffi::c_void, // +0x6c
    pub _tail: [u8; 0x8], // 8
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_interconnect_app_info {
    pub package_name: *mut core::ffi::c_void, // +0x0
    pub display_name: *mut core::ffi::c_void, // +0x4
    pub icon_file: *mut core::ffi::c_void, // +0x8
    pub extra: *mut core::ffi::c_void, // +0xc
    pub fingerprint: [u8; 20], // +0x10
}

#[repr(C, packed(8))]
#[derive(Copy, Clone, Debug)]
pub struct firmware_notification_message {
    pub message_id: u64, // +0x0
    pub repeat_count: u32, // +0x8
    pub title: *mut core::ffi::c_void, // +0xc
    pub source: *mut core::ffi::c_void, // +0x10
    pub body: *mut core::ffi::c_void, // +0x14
    pub auxiliary_text: *mut core::ffi::c_void, // +0x18
    pub small_icon_path: *mut core::ffi::c_void, // +0x1c
    pub large_icon_path: *mut core::ffi::c_void, // +0x20
    pub extension_text_36: *mut core::ffi::c_void, // +0x24
    pub extension_text_40: *mut core::ffi::c_void, // +0x28
    pub _pad_2c: [u8; 0x4], // 4
    pub timestamp: u64, // +0x30
    pub _pad_38: [u8; 0x4], // 4
    pub flags_60: [u8; 3], // +0x3c
    pub _pad_3f: [u8; 0x1], // 1
    pub action_callback: *mut core::ffi::c_void, // +0x40
    pub action_context: u32, // +0x44
    pub extension_72: u32, // +0x48
    pub extension_76: u32, // +0x4c
    pub open_callback: *mut core::ffi::c_void, // +0x50
    pub destroy_callback: *mut core::ffi::c_void, // +0x54
    pub start_reminder: u8, // +0x58
    pub flags_89: u8, // +0x59
    pub flags_90: u8, // +0x5a
    pub _pad_5b: [u8; 0x1], // 1
    pub callback_data: *mut core::ffi::c_void, // +0x5c
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct service_object {
    pub enabled_state: u8, // +0x0
    pub _pad_1: [u8; 0x3], // 3
    pub name: *mut core::ffi::c_void, // +0x4
    pub service_id: u8, // +0x8
    pub profile_group: u8, // +0x9
    pub _pad_a: [u8; 0x1a], // 26
    pub startup_cb: *mut core::ffi::c_void, // +0x24
    pub _pad_28: [u8; 0x8], // 8
    pub startup_eligibility_cb: *mut core::ffi::c_void, // +0x30
    pub get_profile_cb: *mut core::ffi::c_void, // +0x34
    pub cleanup_cb: *mut core::ffi::c_void, // +0x38
    pub _tail: [u8; 0x4], // 4
}

pub type canopus_interconnect_send_done = extern "C" fn(*mut core::ffi::c_void, i32, *const canopus_interconnect_message, *mut core::ffi::c_void) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_interconnect_message {
    pub r#type: u8, // +0x0
    pub _pad_1: [u8; 0x3], // 3
    pub length: u32, // +0x4
    pub _pad_8: [u8; 0x8], // 8
    pub value: *mut core::ffi::c_void, // +0x10
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct ordered_app_entry {
    pub app_name: *mut core::ffi::c_void, // +0x0
    pub _pad_4: [u8; 0x4], // 4
    pub enabled: u8, // +0x8
    pub hidden: u8, // +0x9
    pub _tail: [u8; 0x6], // 6
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_struct {
    pub name: [u8; 128], // +0x0
    pub flags: u8, // +0x80
    pub _tail: [u8; 0x3], // 3
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_record {
    pub app_id: u16, // +0x0
    pub _pad_2: [u8; 0x2], // 2
    pub display_name: *mut core::ffi::c_void, // +0x4
    pub package_name: *mut core::ffi::c_void, // +0x8
    pub icon_name: *mut core::ffi::c_void, // +0xc
    pub _pad_10: [u8; 0x8], // 8
    pub flags: u8, // +0x18
    pub _tail: [u8; 0x3], // 3
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_descriptor {
    pub registry_links: u64, // +0x0
    pub vtable: *mut core::ffi::c_void, // +0x8
    pub package_name: *mut core::ffi::c_void, // +0xc
    pub launcher_icon_resource: *mut core::ffi::c_void, // +0x10
    pub app_id: u16, // +0x14
    pub flags: u8, // +0x16
    pub _pad_17: [u8; 0x5], // 5
    pub owned_string_28: *mut core::ffi::c_void, // +0x1c
    pub owned_string_32: *mut core::ffi::c_void, // +0x20
    pub launcher_metadata_callback: *mut core::ffi::c_void, // +0x24
    pub _pad_28: [u8; 0x10], // 16
    pub page_registry: *mut core::ffi::c_void, // +0x38
    pub _pad_3c: [u8; 0xc], // 12
    pub hidden_flags: u8, // +0x48
    pub _tail: [u8; 0x7], // 7
}

// ---- runtime identity guard ----
/// Returns 0 when the running firmware matches this pack's
/// version + build identity, -1 otherwise. Call once before use.
pub fn canopus_identity_guard() -> i32 {
    const EXPECT_VERSION: &[u8] = b"4.100.139";
    const EXPECT_BUILD: &[u8] = b"user-4.100.139-cn-202608280000";
    if !identity_token_eq(0x0CA0D216, EXPECT_VERSION) { return -1; }
    if !identity_token_eq(0x0CA0D28E, EXPECT_BUILD) { return -1; }
    0
}

/// Compares an LF-, CR-, or NUL-terminated identity token.
fn identity_token_eq(addr: usize, expected: &[u8]) -> bool {
    let mut i = 0usize;
    while i <= expected.len() && i < 64 {
        let b = unsafe { *((addr + i) as *const u8) };
        if i < expected.len() {
            if b != expected[i] { return false; }
        } else {
            return b == 0 || b == b'\n' || b == b'\r';
        }
        i += 1;
    }
    false
}

// ---- typed firmware bindings (unsafe) ----
/// Recovered `lvx_label_create` at 0xc3ab300. Thumb callable address 0xc3ab301.
pub const CANOPUS_FW_LVX_LABEL_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc3ab301usize);

/// Recovered `bt_timer_add` at 0xc8c7ff0. Thumb callable address 0xc8c7ff1.
pub const CANOPUS_FW_BT_TIMER_ADD_CALLABLE: usize = canopus_thumb_callable(0xc8c7ff1usize);

/// Recovered `gap_host_stock_receive` at 0xc863c98. Thumb callable address 0xc863c99.
pub const CANOPUS_FW_GAP_HOST_STOCK_RECEIVE_CALLABLE: usize = canopus_thumb_callable(0xc863c99usize);

/// Recovered `unregister_blockdriver` at 0xc7b955e. Thumb callable address 0xc7b955f.
pub const CANOPUS_FW_UNREGISTER_BLOCKDRIVER_CALLABLE: usize = canopus_thumb_callable(0xc7b955fusize);

/// Recovered `thirdparty_submit_message_content` at 0xc9427f0. Thumb callable address 0xc9427f1.
pub const CANOPUS_FW_THIRDPARTY_SUBMIT_MESSAGE_CONTENT_CALLABLE: usize = canopus_thumb_callable(0xc9427f1usize);

/// Recovered `hfp_ag_disconnect` at 0xc531644. Thumb callable address 0xc531645.
pub const CANOPUS_FW_HFP_AG_DISCONNECT_CALLABLE: usize = canopus_thumb_callable(0xc531645usize);

/// Recovered `font_manager_add_path` at 0x0c4924e0. Thumb callable address 0x0c4924e1.
pub const CANOPUS_FW_FONT_MANAGER_ADD_PATH_CALLABLE: usize = canopus_thumb_callable(0x0c4924e1usize);

/// Recovered `bt_alloc` at 0xc351724. Thumb callable address 0xc351725.
pub const CANOPUS_FW_BT_ALLOC_CALLABLE: usize = canopus_thumb_callable(0xc351725usize);

/// Recovered `bt_adapter_unregister` at 0xc46a3f8. Thumb callable address 0xc46a3f9.
pub const CANOPUS_FW_BT_ADAPTER_UNREGISTER_CALLABLE: usize = canopus_thumb_callable(0xc46a3f9usize);

/// Recovered `lv_bar_set_value` at 0xc3ad8b4. Thumb callable address 0xc3ad8b5.
pub const CANOPUS_FW_LV_BAR_SET_VALUE_CALLABLE: usize = canopus_thumb_callable(0xc3ad8b5usize);

/// Recovered `lv_obj_align_to` at 0xc3877b0. Thumb callable address 0xc3877b1.
pub const CANOPUS_FW_LV_OBJ_ALIGN_TO_CALLABLE: usize = canopus_thumb_callable(0xc3877b1usize);

/// Recovered `sdp_builder_create` at 0xc88555c. Thumb callable address 0xc88555d.
pub const CANOPUS_FW_SDP_BUILDER_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc88555dusize);

/// Recovered global `mpu_region_bitmap` at 0x200f5190.
pub const canopus_fw_mpu_region_bitmap: usize = 0x200f5190usize;

/// Recovered `heap_zalloc` at 0xc484430. Thumb callable address 0xc484431.
pub const CANOPUS_FW_HEAP_ZALLOC_CALLABLE: usize = canopus_thumb_callable(0xc484431usize);

/// Recovered `cache_i_clean_invalidate_all` at 0xc0c181e. Thumb callable address 0xc0c181f.
pub const CANOPUS_FW_CACHE_I_CLEAN_INVALIDATE_ALL_CALLABLE: usize = canopus_thumb_callable(0xc0c181fusize);

/// Recovered `vendor_hci_transport_register` at 0xc6c922c. Thumb callable address 0xc6c922d.
pub const CANOPUS_FW_VENDOR_HCI_TRANSPORT_REGISTER_CALLABLE: usize = canopus_thumb_callable(0xc6c922dusize);

/// Recovered `firmware_log` at 0xc36c71c. Thumb callable address 0xc36c71d.
pub const CANOPUS_FW_FIRMWARE_LOG_CALLABLE: usize = canopus_thumb_callable(0xc36c71dusize);

/// Recovered `bt_buffer_new` at 0xc862ed2. Thumb callable address 0xc862ed3.
pub const CANOPUS_FW_BT_BUFFER_NEW_CALLABLE: usize = canopus_thumb_callable(0xc862ed3usize);

/// Recovered `register_blockdriver` at 0xc46c25a. Thumb callable address 0xc46c25b.
pub const CANOPUS_FW_REGISTER_BLOCKDRIVER_CALLABLE: usize = canopus_thumb_callable(0xc46c25busize);

/// Recovered `app_launcher_add` at 0xc547b54. Thumb callable address 0xc547b55.
pub const CANOPUS_FW_APP_LAUNCHER_ADD_CALLABLE: usize = canopus_thumb_callable(0xc547b55usize);

/// Recovered `lvx_content_pad_bottom` at 0xc387c6e. Thumb callable address 0xc387c6f.
pub const CANOPUS_FW_LVX_CONTENT_PAD_BOTTOM_CALLABLE: usize = canopus_thumb_callable(0xc387c6fusize);

/// Recovered `cache_barrier` at 0xc91e542. Thumb callable address 0xc91e543.
pub const CANOPUS_FW_CACHE_BARRIER_CALLABLE: usize = canopus_thumb_callable(0xc91e543usize);

/// Recovered global `umem_heap_descriptor` at 0x3c356b40.
pub const canopus_fw_umem_heap_descriptor: usize = 0x3c356b40usize;

/// Recovered `app_launcher_data_init` at 0xc344108. Thumb callable address 0xc344109.
pub const CANOPUS_FW_APP_LAUNCHER_DATA_INIT_CALLABLE: usize = canopus_thumb_callable(0xc344109usize);

/// Recovered `lv_obj_clear_flag` at 0xc3840d8. Thumb callable address 0xc3840d9.
pub const CANOPUS_FW_LV_OBJ_CLEAR_FLAG_CALLABLE: usize = canopus_thumb_callable(0xc3840d9usize);

/// Recovered `lv_timer_del` at 0xc3abe70. Thumb callable address 0xc3abe71.
pub const CANOPUS_FW_LV_TIMER_DEL_CALLABLE: usize = canopus_thumb_callable(0xc3abe71usize);

/// Recovered `watchface_reset_watchface` at 0xc5f3474. Thumb callable address 0xc5f3475.
pub const CANOPUS_FW_WATCHFACE_RESET_WATCHFACE_CALLABLE: usize = canopus_thumb_callable(0xc5f3475usize);

/// Recovered `lvx_object_add_flag` at 0xc38404c. Thumb callable address 0xc38404d.
pub const CANOPUS_FW_LVX_OBJECT_ADD_FLAG_CALLABLE: usize = canopus_thumb_callable(0xc38404dusize);

/// Recovered `bt_l2cap_disconnect` at 0xc86f0a4. Thumb callable address 0xc86f0a5.
pub const CANOPUS_FW_BT_L2CAP_DISCONNECT_CALLABLE: usize = canopus_thumb_callable(0xc86f0a5usize);

/// Recovered `page_goto` at 0xc8ed780. Thumb callable address 0xc8ed781.
pub const CANOPUS_FW_PAGE_GOTO_CALLABLE: usize = canopus_thumb_callable(0xc8ed781usize);

/// Recovered `sdp_unregister` at 0xc86f3e0. Thumb callable address 0xc86f3e1.
pub const CANOPUS_FW_SDP_UNREGISTER_CALLABLE: usize = canopus_thumb_callable(0xc86f3e1usize);

/// Recovered `hidden_and_show_app_cb` at 0xc547988. Thumb callable address 0xc547989.
pub const CANOPUS_FW_HIDDEN_AND_SHOW_APP_CB_CALLABLE: usize = canopus_thumb_callable(0xc547989usize);

/// Recovered `lv_image_set_src` at 0xc3b2c28. Thumb callable address 0xc3b2c29.
pub const CANOPUS_FW_LV_IMAGE_SET_SRC_CALLABLE: usize = canopus_thumb_callable(0xc3b2c29usize);

/// Recovered `mm_mallinfo` at 0xc34f0a0. Thumb callable address 0xc34f0a1.
pub const CANOPUS_FW_MM_MALLINFO_CALLABLE: usize = canopus_thumb_callable(0xc34f0a1usize);

/// Recovered `bt_free` at 0xc34cd2c. Thumb callable address 0xc34cd2d.
pub const CANOPUS_FW_BT_FREE_CALLABLE: usize = canopus_thumb_callable(0xc34cd2dusize);

/// Recovered `lv_obj_set_hidden` at 0xc721318. Thumb callable address 0xc721319.
pub const CANOPUS_FW_LV_OBJ_SET_HIDDEN_CALLABLE: usize = canopus_thumb_callable(0xc721319usize);

/// Recovered `bt_create_bond_private` at 0xc342412. Thumb callable address 0xc342413.
pub const CANOPUS_FW_BT_CREATE_BOND_PRIVATE_CALLABLE: usize = canopus_thumb_callable(0xc342413usize);

/// Recovered `lv_obj_set_style_pad_top` at 0xc387c58. Thumb callable address 0xc387c59.
pub const CANOPUS_FW_LV_OBJ_SET_STYLE_PAD_TOP_CALLABLE: usize = canopus_thumb_callable(0xc387c59usize);

/// Recovered global `style_misans_medium_28` at 0x200c1574.
pub const canopus_fw_style_misans_medium_28: usize = 0x200c1574usize;

/// Recovered `lv_obj_set_style_pad_bottom` at 0xc387c6e. Thumb callable address 0xc387c6f.
pub const CANOPUS_FW_LV_OBJ_SET_STYLE_PAD_BOTTOM_CALLABLE: usize = canopus_thumb_callable(0xc387c6fusize);

/// Recovered `app_launcher_del` at 0xc572cf4. Thumb callable address 0xc572cf5.
pub const CANOPUS_FW_APP_LAUNCHER_DEL_CALLABLE: usize = canopus_thumb_callable(0xc572cf5usize);

/// Recovered `close` at 0xc33818c. Thumb callable address 0xc33818d.
pub const CANOPUS_FW_CLOSE_CALLABLE: usize = canopus_thumb_callable(0xc33818dusize);

/// Recovered `kmem_free` at 0xc34ccb8. Thumb callable address 0xc34ccb9.
pub const CANOPUS_FW_KMEM_FREE_CALLABLE: usize = canopus_thumb_callable(0xc34ccb9usize);

/// Recovered `core_bt_pair_request_callback` at 0xc4f438c. Thumb callable address 0xc4f438d.
pub const CANOPUS_FW_CORE_BT_PAIR_REQUEST_CALLBACK_CALLABLE: usize = canopus_thumb_callable(0xc4f438dusize);

/// Recovered `pthread_create_internal` at 0xc91bf34. Thumb callable address 0xc91bf35.
pub const CANOPUS_FW_PTHREAD_CREATE_INTERNAL_CALLABLE: usize = canopus_thumb_callable(0xc91bf35usize);

/// Recovered global `style_misans_medium_24` at 0x200c1568.
pub const canopus_fw_style_misans_medium_24: usize = 0x200c1568usize;

/// Recovered `heap_free` at 0xc34cd2c. Thumb callable address 0xc34cd2d.
pub const CANOPUS_FW_HEAP_FREE_CALLABLE: usize = canopus_thumb_callable(0xc34cd2dusize);

/// Recovered `lv_obj_add_event_cb` at 0xc37fc1c. Thumb callable address 0xc37fc1d.
pub const CANOPUS_FW_LV_OBJ_ADD_EVENT_CB_CALLABLE: usize = canopus_thumb_callable(0xc37fc1dusize);

/// Recovered `lvx_object_delete` at 0xc720ea8. Thumb callable address 0xc720ea9.
pub const CANOPUS_FW_LVX_OBJECT_DELETE_CALLABLE: usize = canopus_thumb_callable(0xc720ea9usize);

/// Recovered `sem_post` at 0xc359150. Thumb callable address 0xc359151.
pub const CANOPUS_FW_SEM_POST_CALLABLE: usize = canopus_thumb_callable(0xc359151usize);

/// Recovered `font_manager_generate_def_path` at 0x0c490edc. Thumb callable address 0x0c490edd.
pub const CANOPUS_FW_FONT_MANAGER_GENERATE_DEF_PATH_CALLABLE: usize = canopus_thumb_callable(0x0c490eddusize);

/// Recovered `lvx_list_item_add_content` at 0xc50fad0. Thumb callable address 0xc50fad1.
pub const CANOPUS_FW_LVX_LIST_ITEM_ADD_CONTENT_CALLABLE: usize = canopus_thumb_callable(0xc50fad1usize);

/// Recovered `bt_timer_cancel_owned` at 0xc863058. Thumb callable address 0xc863059.
pub const CANOPUS_FW_BT_TIMER_CANCEL_OWNED_CALLABLE: usize = canopus_thumb_callable(0xc863059usize);

/// Recovered `register_driver` at 0xc914f64. Thumb callable address 0xc914f65.
pub const CANOPUS_FW_REGISTER_DRIVER_CALLABLE: usize = canopus_thumb_callable(0xc914f65usize);

/// Recovered `write` at 0xc33dc4e. Thumb callable address 0xc33dc4f.
pub const CANOPUS_FW_WRITE_CALLABLE: usize = canopus_thumb_callable(0xc33dc4fusize);

/// Recovered `font_manager_remove_path` at 0x0c904cfc. Thumb callable address 0x0c904cfd.
pub const CANOPUS_FW_FONT_MANAGER_REMOVE_PATH_CALLABLE: usize = canopus_thumb_callable(0x0c904cfdusize);

/// Recovered `lvx_label_set_text` at 0xc3b3948. Thumb callable address 0xc3b3949.
pub const CANOPUS_FW_LVX_LABEL_SET_TEXT_CALLABLE: usize = canopus_thumb_callable(0xc3b3949usize);

/// Recovered `offload_property_apply` at 0xc468674. Thumb callable address 0xc468675.
pub const CANOPUS_FW_OFFLOAD_PROPERTY_APPLY_CALLABLE: usize = canopus_thumb_callable(0xc468675usize);

/// Recovered `unlink` at 0xc33dbec. Thumb callable address 0xc33dbed.
pub const CANOPUS_FW_UNLINK_CALLABLE: usize = canopus_thumb_callable(0xc33dbedusize);

/// Recovered `bt_get_pairing_state` at 0xc43e73a. Thumb callable address 0xc43e73b.
pub const CANOPUS_FW_BT_GET_PAIRING_STATE_CALLABLE: usize = canopus_thumb_callable(0xc43e73busize);

/// Recovered `read` at 0xc33d784. Thumb callable address 0xc33d785.
pub const CANOPUS_FW_READ_CALLABLE: usize = canopus_thumb_callable(0xc33d785usize);

/// Recovered `service_manager_register` at 0xc573ba8. Thumb callable address 0xc573ba9.
pub const CANOPUS_FW_SERVICE_MANAGER_REGISTER_CALLABLE: usize = canopus_thumb_callable(0xc573ba9usize);

/// Recovered `bt_adapter_get_scan_mode` at 0xc66b0c0. Thumb callable address 0xc66b0c1.
pub const CANOPUS_FW_BT_ADAPTER_GET_SCAN_MODE_CALLABLE: usize = canopus_thumb_callable(0xc66b0c1usize);

/// Recovered `lvx_object_set_size` at 0xc387ba8. Thumb callable address 0xc387ba9.
pub const CANOPUS_FW_LVX_OBJECT_SET_SIZE_CALLABLE: usize = canopus_thumb_callable(0xc387ba9usize);

/// Recovered global `gap_host_receive_slot` at 0x200bda80.
pub const canopus_fw_gap_host_receive_slot: usize = 0x200bda80usize;

/// Recovered `on_resume_wrapped` at 0x0c696c18. Thumb callable address 0x0c696c19.
pub const CANOPUS_FW_ON_RESUME_WRAPPED_CALLABLE: usize = canopus_thumb_callable(0x0c696c19usize);

/// Recovered `modhandle` at 0xc36dd44. Thumb callable address 0xc36dd45.
pub const CANOPUS_FW_MODHANDLE_CALLABLE: usize = canopus_thumb_callable(0xc36dd45usize);

/// Recovered `system_router_app_wrapper` at 0xc45be22. Thumb callable address 0xc45be23.
pub const CANOPUS_FW_SYSTEM_ROUTER_APP_WRAPPER_CALLABLE: usize = canopus_thumb_callable(0xc45be23usize);

/// Recovered `lv_bar_set_range` at 0xc3ad920. Thumb callable address 0xc3ad921.
pub const CANOPUS_FW_LV_BAR_SET_RANGE_CALLABLE: usize = canopus_thumb_callable(0xc3ad921usize);

/// Recovered `lvx_object_align` at 0xc387788. Thumb callable address 0xc387789.
pub const CANOPUS_FW_LVX_OBJECT_ALIGN_CALLABLE: usize = canopus_thumb_callable(0xc387789usize);

/// Recovered `driver_ioctl_dispatch` at 0xc7d48e0. Thumb callable address 0xc7d48e1.
pub const CANOPUS_FW_DRIVER_IOCTL_DISPATCH_CALLABLE: usize = canopus_thumb_callable(0xc7d48e1usize);

/// Recovered `bt_pair_display_reply` at 0xc46a9fe. Thumb callable address 0xc46a9ff.
pub const CANOPUS_FW_BT_PAIR_DISPLAY_REPLY_CALLABLE: usize = canopus_thumb_callable(0xc46a9ffusize);

/// Recovered `lvx_style_apply` at 0xc4fbe54. Thumb callable address 0xc4fbe55.
pub const CANOPUS_FW_LVX_STYLE_APPLY_CALLABLE: usize = canopus_thumb_callable(0xc4fbe55usize);

/// Recovered `sport_titlebar_dispatch` at 0xc341178. Thumb callable address 0xc341179.
pub const CANOPUS_FW_SPORT_TITLEBAR_DISPATCH_CALLABLE: usize = canopus_thumb_callable(0xc341179usize);

/// Recovered `bt_queue_external` at 0xc863bc4. Thumb callable address 0xc863bc5.
pub const CANOPUS_FW_BT_QUEUE_EXTERNAL_CALLABLE: usize = canopus_thumb_callable(0xc863bc5usize);

/// Recovered `lv_timer_create` at 0xc3abd20. Thumb callable address 0xc3abd21.
pub const CANOPUS_FW_LV_TIMER_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc3abd21usize);

/// Recovered `exec_pop_lifecycle_without_cachepolicy` at 0x0c696e34. Thumb callable address 0x0c696e35.
pub const CANOPUS_FW_EXEC_POP_LIFECYCLE_WITHOUT_CACHEPOLICY_CALLABLE: usize = canopus_thumb_callable(0x0c696e35usize);

/// Recovered `page_finish` at 0xc69b5ac. Thumb callable address 0xc69b5ad.
pub const CANOPUS_FW_PAGE_FINISH_CALLABLE: usize = canopus_thumb_callable(0xc69b5adusize);

/// Recovered `lv_obj_set_style_bg_opa` at 0xc6c7dcc. Thumb callable address 0xc6c7dcd.
pub const CANOPUS_FW_LV_OBJ_SET_STYLE_BG_OPA_CALLABLE: usize = canopus_thumb_callable(0xc6c7dcdusize);

/// Recovered `service_manager_startup` at 0xc90d8ac. Thumb callable address 0xc90d8ad.
pub const CANOPUS_FW_SERVICE_MANAGER_STARTUP_CALLABLE: usize = canopus_thumb_callable(0xc90d8adusize);

/// Recovered `watchface_manager_delete_watchface` at 0xc6c6650. Thumb callable address 0xc6c6651.
pub const CANOPUS_FW_WATCHFACE_MANAGER_DELETE_WATCHFACE_CALLABLE: usize = canopus_thumb_callable(0xc6c6651usize);

/// Recovered `lvx_msgbox_set_content` at 0xc566b9c. Thumb callable address 0xc566b9d.
pub const CANOPUS_FW_LVX_MSGBOX_SET_CONTENT_CALLABLE: usize = canopus_thumb_callable(0xc566b9dusize);

/// Recovered `lvx_page_title_create` at 0xc89e7dc. Thumb callable address 0xc89e7dd.
pub const CANOPUS_FW_LVX_PAGE_TITLE_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc89e7ddusize);

/// Recovered `bt_l2cap_connect` at 0xc86f020. Thumb callable address 0xc86f021.
pub const CANOPUS_FW_BT_L2CAP_CONNECT_CALLABLE: usize = canopus_thumb_callable(0xc86f021usize);

/// Recovered `bt_adapter_get_state` at 0xc46a44c. Thumb callable address 0xc46a44d.
pub const CANOPUS_FW_BT_ADAPTER_GET_STATE_CALLABLE: usize = canopus_thumb_callable(0xc46a44dusize);

/// Recovered `page_stack_get` at 0x0c697450. Thumb callable address 0x0c697451.
pub const CANOPUS_FW_PAGE_STACK_GET_CALLABLE: usize = canopus_thumb_callable(0x0c697451usize);

/// Recovered `rmmod` at 0xc32a690. Thumb callable address 0xc32a691.
pub const CANOPUS_FW_RMMOD_CALLABLE: usize = canopus_thumb_callable(0xc32a691usize);

/// Recovered `open` at 0xc342c54. Thumb callable address 0xc342c55.
pub const CANOPUS_FW_OPEN_CALLABLE: usize = canopus_thumb_callable(0xc342c55usize);

/// Recovered `interconnect_close` at 0xc908358. Thumb callable address 0xc908359.
pub const CANOPUS_FW_INTERCONNECT_CLOSE_CALLABLE: usize = canopus_thumb_callable(0xc908359usize);

/// Recovered `bt_timer_cancel` at 0xc863010. Thumb callable address 0xc863011.
pub const CANOPUS_FW_BT_TIMER_CANCEL_CALLABLE: usize = canopus_thumb_callable(0xc863011usize);

/// Recovered `heap_mallinfo` at 0xc3608b8. Thumb callable address 0xc3608b9.
pub const CANOPUS_FW_HEAP_MALLINFO_CALLABLE: usize = canopus_thumb_callable(0xc3608b9usize);

/// Recovered `heap_malloc` at 0xc3513e8. Thumb callable address 0xc3513e9.
pub const CANOPUS_FW_HEAP_MALLOC_CALLABLE: usize = canopus_thumb_callable(0xc3513e9usize);

/// Recovered `bt_adapter_register` at 0xc46a38e. Thumb callable address 0xc46a38f.
pub const CANOPUS_FW_BT_ADAPTER_REGISTER_CALLABLE: usize = canopus_thumb_callable(0xc46a38fusize);

/// Recovered `interconnect_connect` at 0xc3ccef4. Thumb callable address 0xc3ccef5.
pub const CANOPUS_FW_INTERCONNECT_CONNECT_CALLABLE: usize = canopus_thumb_callable(0xc3ccef5usize);

/// Recovered `bt_adapter_set_scan_mode` at 0xc789cf8. Thumb callable address 0xc789cf9.
pub const CANOPUS_FW_BT_ADAPTER_SET_SCAN_MODE_CALLABLE: usize = canopus_thumb_callable(0xc789cf9usize);

/// Recovered `lv_obj_set_width` at 0xc387b2e. Thumb callable address 0xc387b2f.
pub const CANOPUS_FW_LV_OBJ_SET_WIDTH_CALLABLE: usize = canopus_thumb_callable(0xc387b2fusize);

/// Recovered `bt_get_bond_state` at 0xc46a884. Thumb callable address 0xc46a885.
pub const CANOPUS_FW_BT_GET_BOND_STATE_CALLABLE: usize = canopus_thumb_callable(0xc46a885usize);

/// Recovered `sem_trywait` at 0xc358c40. Thumb callable address 0xc358c41.
pub const CANOPUS_FW_SEM_TRYWAIT_CALLABLE: usize = canopus_thumb_callable(0xc358c41usize);

/// Recovered `bt_queue_free` at 0xc858998. Thumb callable address 0xc858999.
pub const CANOPUS_FW_BT_QUEUE_FREE_CALLABLE: usize = canopus_thumb_callable(0xc858999usize);

/// Recovered `lseek` at 0xc33d510. Thumb callable address 0xc33d511.
pub const CANOPUS_FW_LSEEK_CALLABLE: usize = canopus_thumb_callable(0xc33d511usize);

/// Recovered global `bt_shared_adapter` at 0x200c3148.
pub const canopus_fw_bt_shared_adapter: usize = 0x200c3148usize;

/// Recovered `service_manager_get_profile` at 0xc54a06c. Thumb callable address 0xc54a06d.
pub const CANOPUS_FW_SERVICE_MANAGER_GET_PROFILE_CALLABLE: usize = canopus_thumb_callable(0xc54a06dusize);

/// Recovered `lv_image_cache_drop` at 0x0c3a3888. Thumb callable address 0x0c3a3889.
pub const CANOPUS_FW_LV_IMAGE_CACHE_DROP_CALLABLE: usize = canopus_thumb_callable(0x0c3a3889usize);

/// Recovered `lvgl_posix_open` at 0x0c3a6194. Thumb callable address 0x0c3a6195.
pub const CANOPUS_FW_LVGL_POSIX_OPEN_CALLABLE: usize = canopus_thumb_callable(0x0c3a6195usize);

/// Recovered `lvx_list_item_create` at 0xc50f4e4. Thumb callable address 0xc50f4e5.
pub const CANOPUS_FW_LVX_LIST_ITEM_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc50f4e5usize);

/// Recovered `sdp_commit` at 0xc86f2cc. Thumb callable address 0xc86f2cd.
pub const CANOPUS_FW_SDP_COMMIT_CALLABLE: usize = canopus_thumb_callable(0xc86f2cdusize);

/// Recovered `rename` at 0xc33d79c. Thumb callable address 0xc33d79d.
pub const CANOPUS_FW_RENAME_CALLABLE: usize = canopus_thumb_callable(0xc33d79dusize);

/// Recovered `page_navigator_open_page` at 0xc4eec84. Thumb callable address 0xc4eec85.
pub const CANOPUS_FW_PAGE_NAVIGATOR_OPEN_PAGE_CALLABLE: usize = canopus_thumb_callable(0xc4eec85usize);

/// Recovered `ioctl` at 0xc341e38. Thumb callable address 0xc341e39.
pub const CANOPUS_FW_IOCTL_CALLABLE: usize = canopus_thumb_callable(0xc341e39usize);

/// Recovered `bt_remove_bond_private` at 0xc3d5280. Thumb callable address 0xc3d5281.
pub const CANOPUS_FW_BT_REMOVE_BOND_PRIVATE_CALLABLE: usize = canopus_thumb_callable(0xc3d5281usize);

/// Recovered `sem_wait` at 0xc358ce0. Thumb callable address 0xc358ce1.
pub const CANOPUS_FW_SEM_WAIT_CALLABLE: usize = canopus_thumb_callable(0xc358ce1usize);

/// Recovered `system_router_get_pages_wrapper` at 0xc8e21bc. Thumb callable address 0xc8e21bd.
pub const CANOPUS_FW_SYSTEM_ROUTER_GET_PAGES_WRAPPER_CALLABLE: usize = canopus_thumb_callable(0xc8e21bdusize);

/// Recovered `lv_obj_set_local_style_prop` at 0xc3872b4. Thumb callable address 0xc3872b5.
pub const CANOPUS_FW_LV_OBJ_SET_LOCAL_STYLE_PROP_CALLABLE: usize = canopus_thumb_callable(0xc3872b5usize);

/// Recovered global `bt_l2cap_owner` at 0x200be890.
pub const canopus_fw_bt_l2cap_owner: usize = 0x200be890usize;

/// Recovered `lvx_object_create` at 0xc380686. Thumb callable address 0xc380687.
pub const CANOPUS_FW_LVX_OBJECT_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc380687usize);

/// Recovered `lv_cache_drop` at 0x0c8b8cae. Thumb callable address 0x0c8b8caf.
pub const CANOPUS_FW_LV_CACHE_DROP_CALLABLE: usize = canopus_thumb_callable(0x0c8b8cafusize);

/// Recovered `lvx_label_set_long_mode` at 0xc3b3f5c. Thumb callable address 0xc3b3f5d.
pub const CANOPUS_FW_LVX_LABEL_SET_LONG_MODE_CALLABLE: usize = canopus_thumb_callable(0xc3b3f5dusize);

/// Recovered `bt_socket_client_sendrecv` at 0xc46a218. Thumb callable address 0xc46a219.
pub const CANOPUS_FW_BT_SOCKET_CLIENT_SENDRECV_CALLABLE: usize = canopus_thumb_callable(0xc46a219usize);

/// Recovered `driver_close_dispatch` at 0xc53e2bc. Thumb callable address 0xc53e2bd.
pub const CANOPUS_FW_DRIVER_CLOSE_DISPATCH_CALLABLE: usize = canopus_thumb_callable(0xc53e2bdusize);

/// Recovered `bt_discovery_stop` at 0xc46a49a. Thumb callable address 0xc46a49b.
pub const CANOPUS_FW_BT_DISCOVERY_STOP_CALLABLE: usize = canopus_thumb_callable(0xc46a49busize);

/// Recovered `service_manager_cleanup` at 0xc5ab3b8. Thumb callable address 0xc5ab3b9.
pub const CANOPUS_FW_SERVICE_MANAGER_CLEANUP_CALLABLE: usize = canopus_thumb_callable(0xc5ab3b9usize);

/// Recovered global `kmem_heap_slot` at 0x200b01c8.
pub const canopus_fw_kmem_heap_slot: usize = 0x200b01c8usize;

/// Recovered `interconnect_send` at 0xc3605bc. Thumb callable address 0xc3605bd.
pub const CANOPUS_FW_INTERCONNECT_SEND_CALLABLE: usize = canopus_thumb_callable(0xc3605bdusize);

/// Recovered `unregister_driver` at 0xc6678c4. Thumb callable address 0xc6678c5.
pub const CANOPUS_FW_UNREGISTER_DRIVER_CALLABLE: usize = canopus_thumb_callable(0xc6678c5usize);

/// Recovered `sdp_set_raw_attribute` at 0xc86f140. Thumb callable address 0xc86f141.
pub const CANOPUS_FW_SDP_SET_RAW_ATTRIBUTE_CALLABLE: usize = canopus_thumb_callable(0xc86f141usize);

/// Recovered `app_lookup` at 0xc6ac54c. Thumb callable address 0xc6ac54d.
pub const CANOPUS_FW_APP_LOOKUP_CALLABLE: usize = canopus_thumb_callable(0xc6ac54dusize);

/// Recovered global `umem_heap_slot` at 0x200b2590.
pub const canopus_fw_umem_heap_slot: usize = 0x200b2590usize;

/// Recovered `mm_memalign` at 0xc3507e8. Thumb callable address 0xc3507e9.
pub const CANOPUS_FW_MM_MEMALIGN_CALLABLE: usize = canopus_thumb_callable(0xc3507e9usize);

/// Recovered `bt_discovery_start` at 0xc46a472. Thumb callable address 0xc46a473.
pub const CANOPUS_FW_BT_DISCOVERY_START_CALLABLE: usize = canopus_thumb_callable(0xc46a473usize);

/// Recovered `controller_crash_dump` at 0xc92c388. Thumb callable address 0xc92c389.
pub const CANOPUS_FW_CONTROLLER_CRASH_DUMP_CALLABLE: usize = canopus_thumb_callable(0xc92c389usize);

/// Recovered `quickapp_register_app` at 0xc5239c4. Thumb callable address 0xc5239c5.
pub const CANOPUS_FW_QUICKAPP_REGISTER_APP_CALLABLE: usize = canopus_thumb_callable(0xc5239c5usize);

/// Recovered `service_manager_shutdown` at 0xc90d84c. Thumb callable address 0xc90d84d.
pub const CANOPUS_FW_SERVICE_MANAGER_SHUTDOWN_CALLABLE: usize = canopus_thumb_callable(0xc90d84dusize);

/// Recovered `lvx_list_item_update` at 0xc50ec5c. Thumb callable address 0xc50ec5d.
pub const CANOPUS_FW_LVX_LIST_ITEM_UPDATE_CALLABLE: usize = canopus_thumb_callable(0xc50ec5dusize);

/// Recovered `bt_pair_request_reply` at 0xc46a9c4. Thumb callable address 0xc46a9c5.
pub const CANOPUS_FW_BT_PAIR_REQUEST_REPLY_CALLABLE: usize = canopus_thumb_callable(0xc46a9c5usize);

/// Recovered `clock_gettime` at 0xc34d58c. Thumb callable address 0xc34d58d.
pub const CANOPUS_FW_CLOCK_GETTIME_CALLABLE: usize = canopus_thumb_callable(0xc34d58dusize);

/// Recovered `bt_adapter_get_instance` at 0xc56f644. Thumb callable address 0xc56f645.
pub const CANOPUS_FW_BT_ADAPTER_GET_INSTANCE_CALLABLE: usize = canopus_thumb_callable(0xc56f645usize);

/// Recovered `bt_adapter_register_hfp_ag_callbacks` at 0xc8abf64. Thumb callable address 0xc8abf65.
pub const CANOPUS_FW_BT_ADAPTER_REGISTER_HFP_AG_CALLBACKS_CALLABLE: usize = canopus_thumb_callable(0xc8abf65usize);

/// Recovered `lvx_notification_insert_message` at 0xc8f2bb0. Thumb callable address 0xc8f2bb1.
pub const CANOPUS_FW_LVX_NOTIFICATION_INSERT_MESSAGE_CALLABLE: usize = canopus_thumb_callable(0xc8f2bb1usize);

/// Recovered `lv_obj_remove_style_all` at 0xc38583c. Thumb callable address 0xc38583d.
pub const CANOPUS_FW_LV_OBJ_REMOVE_STYLE_ALL_CALLABLE: usize = canopus_thumb_callable(0xc38583dusize);

/// Recovered `protobuf_set_ordered_app_list` at 0xc54cb6c. Thumb callable address 0xc54cb6d.
pub const CANOPUS_FW_PROTOBUF_SET_ORDERED_APP_LIST_CALLABLE: usize = canopus_thumb_callable(0xc54cb6dusize);

/// Recovered `_lv_inv_area` at 0x0c382428. Thumb callable address 0x0c382429.
pub const CANOPUS_FW__LV_INV_AREA_CALLABLE: usize = canopus_thumb_callable(0x0c382429usize);

/// Recovered `lvx_msgbox_create` at 0xc43e7d0. Thumb callable address 0xc43e7d1.
pub const CANOPUS_FW_LVX_MSGBOX_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc43e7d1usize);

/// Recovered `lvx_image_set_scale` at 0xc3ae46e. Thumb callable address 0xc3ae46f.
pub const CANOPUS_FW_LVX_IMAGE_SET_SCALE_CALLABLE: usize = canopus_thumb_callable(0xc3ae46fusize);

/// Recovered `lv_image_create` at 0xc3ae1d0. Thumb callable address 0xc3ae1d1.
pub const CANOPUS_FW_LV_IMAGE_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc3ae1d1usize);

/// Recovered `bt_l2cap_submit_cid` at 0xc86f0cc. Thumb callable address 0xc86f0cd.
pub const CANOPUS_FW_BT_L2CAP_SUBMIT_CID_CALLABLE: usize = canopus_thumb_callable(0xc86f0cdusize);

/// Recovered `bt_socket_server_receive` at 0xc4b3218. Thumb callable address 0xc4b3219.
pub const CANOPUS_FW_BT_SOCKET_SERVER_RECEIVE_CALLABLE: usize = canopus_thumb_callable(0xc4b3219usize);

/// Recovered `bt_adapter_register_a2dp_callbacks` at 0xc8ac188. Thumb callable address 0xc8ac189.
pub const CANOPUS_FW_BT_ADAPTER_REGISTER_A2DP_CALLBACKS_CALLABLE: usize = canopus_thumb_callable(0xc8ac189usize);

/// Recovered `errno_location` at 0xc349538. Thumb callable address 0xc349539.
pub const CANOPUS_FW_ERRNO_LOCATION_CALLABLE: usize = canopus_thumb_callable(0xc349539usize);

/// Recovered `lv_event_get_code` at 0xc0f7728. Thumb callable address 0xc0f7729.
pub const CANOPUS_FW_LV_EVENT_GET_CODE_CALLABLE: usize = canopus_thumb_callable(0xc0f7729usize);

/// Recovered `hfp_ag_connect` at 0xc46bdd8. Thumb callable address 0xc46bdd9.
pub const CANOPUS_FW_HFP_AG_CONNECT_CALLABLE: usize = canopus_thumb_callable(0xc46bdd9usize);

/// Recovered `lv_event_get_user_data` at 0xc720f20. Thumb callable address 0xc720f21.
pub const CANOPUS_FW_LV_EVENT_GET_USER_DATA_CALLABLE: usize = canopus_thumb_callable(0xc720f21usize);

/// Recovered `lv_obj_move_to_index` at 0xc3846ac. Thumb callable address 0xc3846ad.
pub const CANOPUS_FW_LV_OBJ_MOVE_TO_INDEX_CALLABLE: usize = canopus_thumb_callable(0xc3846adusize);

/// Recovered `lv_bar_create` at 0xc3ad7f4. Thumb callable address 0xc3ad7f5.
pub const CANOPUS_FW_LV_BAR_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc3ad7f5usize);

/// Recovered `cache_d_clean_all` at 0xc93021a. Thumb callable address 0xc93021b.
pub const CANOPUS_FW_CACHE_D_CLEAN_ALL_CALLABLE: usize = canopus_thumb_callable(0xc93021busize);

/// Recovered `app_install` at 0xc6ab350. Thumb callable address 0xc6ab351.
pub const CANOPUS_FW_APP_INSTALL_CALLABLE: usize = canopus_thumb_callable(0xc6ab351usize);

// ---- excluded symbols ----
// _lv_inv_area: restricted - not exported until context/ownership approved
// app_install: restricted - not exported until context/ownership approved
// app_launcher_add: restricted - not exported until context/ownership approved
// app_launcher_data_init: restricted - not exported until context/ownership approved
// app_launcher_del: restricted - not exported until context/ownership approved
// app_lookup: restricted - not exported until context/ownership approved
// bt_adapter_get_instance: restricted - not exported until context/ownership approved
// bt_adapter_get_scan_mode: restricted - not exported until context/ownership approved
// bt_adapter_get_state: restricted - not exported until context/ownership approved
// bt_adapter_register: restricted - not exported until context/ownership approved
// bt_adapter_register_a2dp_callbacks: restricted - not exported until context/ownership approved
// bt_adapter_register_hfp_ag_callbacks: restricted - not exported until context/ownership approved
// bt_adapter_set_scan_mode: restricted - not exported until context/ownership approved
// bt_adapter_unregister: restricted - not exported until context/ownership approved
// bt_alloc: restricted - not exported until context/ownership approved
// bt_buffer_new: restricted - not exported until context/ownership approved
// bt_create_bond_private: restricted - not exported until context/ownership approved
// bt_discovery_start: restricted - not exported until context/ownership approved
// bt_discovery_stop: restricted - not exported until context/ownership approved
// bt_free: restricted - not exported until context/ownership approved
// bt_get_bond_state: restricted - not exported until context/ownership approved
// bt_get_pairing_state: restricted - not exported until context/ownership approved
// bt_l2cap_connect: restricted - not exported until context/ownership approved
// bt_l2cap_disconnect: restricted - not exported until context/ownership approved
// bt_l2cap_submit_cid: restricted - not exported until context/ownership approved
// bt_pair_display_reply: restricted - not exported until context/ownership approved
// bt_pair_request_reply: restricted - not exported until context/ownership approved
// bt_queue_external: restricted - not exported until context/ownership approved
// bt_queue_free: restricted - not exported until context/ownership approved
// bt_remove_bond_private: restricted - not exported until context/ownership approved
// bt_socket_client_sendrecv: restricted - not exported until context/ownership approved
// bt_socket_server_receive: restricted - not exported until context/ownership approved
// bt_timer_add: restricted - not exported until context/ownership approved
// bt_timer_cancel: restricted - not exported until context/ownership approved
// bt_timer_cancel_owned: restricted - not exported until context/ownership approved
// cache_barrier: restricted - not exported until context/ownership approved
// cache_d_clean_all: restricted - not exported until context/ownership approved
// cache_i_clean_invalidate_all: restricted - not exported until context/ownership approved
// clock_gettime: restricted - not exported until context/ownership approved
// close: restricted - not exported until context/ownership approved
// controller_crash_dump: restricted - not exported until context/ownership approved
// core_bt_pair_request_callback: restricted - not exported until context/ownership approved
// driver_close_dispatch: restricted - not exported until context/ownership approved
// driver_ioctl_dispatch: restricted - not exported until context/ownership approved
// errno_location: restricted - not exported until context/ownership approved
// exec_pop_lifecycle_without_cachepolicy: restricted - not exported until context/ownership approved
// firmware_log: restricted - not exported until context/ownership approved
// font_manager_add_path: restricted - not exported until context/ownership approved
// font_manager_generate_def_path: restricted - not exported until context/ownership approved
// font_manager_remove_path: restricted - not exported until context/ownership approved
// gap_host_stock_receive: restricted - not exported until context/ownership approved
// heap_free: restricted - not exported until context/ownership approved
// heap_mallinfo: restricted - not exported until context/ownership approved
// heap_malloc: restricted - not exported until context/ownership approved
// heap_zalloc: restricted - not exported until context/ownership approved
// hfp_ag_connect: restricted - not exported until context/ownership approved
// hfp_ag_disconnect: restricted - not exported until context/ownership approved
// hidden_and_show_app_cb: restricted - not exported until context/ownership approved
// insmod: FORBIDDEN - no binding may ever be generated
// interconnect_close: restricted - not exported until context/ownership approved
// interconnect_connect: restricted - not exported until context/ownership approved
// interconnect_send: restricted - not exported until context/ownership approved
// ioctl: restricted - not exported until context/ownership approved
// kmem_free: restricted - not exported until context/ownership approved
// lseek: restricted - not exported until context/ownership approved
// lv_bar_create: restricted - not exported until context/ownership approved
// lv_bar_set_range: restricted - not exported until context/ownership approved
// lv_bar_set_value: restricted - not exported until context/ownership approved
// lv_cache_drop: restricted - not exported until context/ownership approved
// lv_event_get_code: restricted - not exported until context/ownership approved
// lv_event_get_user_data: restricted - not exported until context/ownership approved
// lv_image_cache_drop: restricted - not exported until context/ownership approved
// lv_image_create: restricted - not exported until context/ownership approved
// lv_image_set_src: restricted - not exported until context/ownership approved
// lv_obj_add_event_cb: restricted - not exported until context/ownership approved
// lv_obj_align_to: restricted - not exported until context/ownership approved
// lv_obj_clear_flag: restricted - not exported until context/ownership approved
// lv_obj_move_to_index: restricted - not exported until context/ownership approved
// lv_obj_remove_style_all: restricted - not exported until context/ownership approved
// lv_obj_set_hidden: restricted - not exported until context/ownership approved
// lv_obj_set_local_style_prop: restricted - not exported until context/ownership approved
// lv_obj_set_style_bg_opa: restricted - not exported until context/ownership approved
// lv_obj_set_style_pad_bottom: restricted - not exported until context/ownership approved
// lv_obj_set_style_pad_top: restricted - not exported until context/ownership approved
// lv_obj_set_width: restricted - not exported until context/ownership approved
// lv_timer_create: restricted - not exported until context/ownership approved
// lv_timer_del: restricted - not exported until context/ownership approved
// lvgl_posix_open: restricted - not exported until context/ownership approved
// lvx_content_pad_bottom: restricted - not exported until context/ownership approved
// lvx_image_set_scale: restricted - not exported until context/ownership approved
// lvx_label_create: restricted - not exported until context/ownership approved
// lvx_label_set_long_mode: restricted - not exported until context/ownership approved
// lvx_label_set_text: restricted - not exported until context/ownership approved
// lvx_list_item_add_content: restricted - not exported until context/ownership approved
// lvx_list_item_create: restricted - not exported until context/ownership approved
// lvx_list_item_update: restricted - not exported until context/ownership approved
// lvx_list_row_create: restricted - not exported until context/ownership approved
// lvx_list_row_trailing: restricted - not exported until context/ownership approved
// lvx_msgbox_create: restricted - not exported until context/ownership approved
// lvx_msgbox_set_content: restricted - not exported until context/ownership approved
// lvx_notification_insert_message: restricted - not exported until context/ownership approved
// lvx_object_add_flag: restricted - not exported until context/ownership approved
// lvx_object_align: restricted - not exported until context/ownership approved
// lvx_object_create: restricted - not exported until context/ownership approved
// lvx_object_delete: restricted - not exported until context/ownership approved
// lvx_object_set_size: restricted - not exported until context/ownership approved
// lvx_page_content_create: restricted - not exported until context/ownership approved
// lvx_page_title_create: restricted - not exported until context/ownership approved
// lvx_style_apply: restricted - not exported until context/ownership approved
// mm_mallinfo: restricted - not exported until context/ownership approved
// mm_memalign: restricted - not exported until context/ownership approved
// modhandle: restricted - not exported until context/ownership approved
// offload_property_apply: restricted - not exported until context/ownership approved
// on_resume_wrapped: restricted - not exported until context/ownership approved
// open: restricted - not exported until context/ownership approved
// page_finish: restricted - not exported until context/ownership approved
// page_goto: restricted - not exported until context/ownership approved
// page_navigator_open_page: restricted - not exported until context/ownership approved
// page_stack_get: restricted - not exported until context/ownership approved
// protobuf_set_ordered_app_list: restricted - not exported until context/ownership approved
// pthread_create_internal: restricted - not exported until context/ownership approved
// quickapp_register_app: restricted - not exported until context/ownership approved
// read: restricted - not exported until context/ownership approved
// register_blockdriver: restricted - not exported until context/ownership approved
// register_driver: restricted - not exported until context/ownership approved
// rename: restricted - not exported until context/ownership approved
// rmmod: restricted - not exported until context/ownership approved
// sdp_builder_create: restricted - not exported until context/ownership approved
// sdp_commit: restricted - not exported until context/ownership approved
// sdp_set_raw_attribute: restricted - not exported until context/ownership approved
// sdp_unregister: restricted - not exported until context/ownership approved
// sem_post: restricted - not exported until context/ownership approved
// sem_trywait: restricted - not exported until context/ownership approved
// sem_wait: restricted - not exported until context/ownership approved
// service_manager_cleanup: restricted - not exported until context/ownership approved
// service_manager_get_profile: restricted - not exported until context/ownership approved
// service_manager_register: restricted - not exported until context/ownership approved
// service_manager_shutdown: restricted - not exported until context/ownership approved
// service_manager_startup: restricted - not exported until context/ownership approved
// sport_titlebar_dispatch: restricted - not exported until context/ownership approved
// system_router_app_wrapper: restricted - not exported until context/ownership approved
// system_router_get_pages_wrapper: restricted - not exported until context/ownership approved
// thirdparty_submit_message_content: restricted - not exported until context/ownership approved
// unlink: restricted - not exported until context/ownership approved
// unregister_blockdriver: restricted - not exported until context/ownership approved
// unregister_driver: restricted - not exported until context/ownership approved
// vendor_hci_transport_register: restricted - not exported until context/ownership approved
// watchface_manager_delete_watchface: restricted - not exported until context/ownership approved
// watchface_reset_watchface: restricted - not exported until context/ownership approved
// write: restricted - not exported until context/ownership approved

