// Generated by `canopus target generate-rust-bindings`. DO NOT EDIT.
//
// target_id: xiaomi-band-9-pro-3.1.175
// firmware : 3.1.175 (CONBINE_LTALM054_T1175_04141021_release_5793)
// sha256   : 4f43b325addd6d9e6e7c7e2a4d00ffe3f23d5fb1560d8fe503544002ac1f516b
// revision : 1
// input_digest: 3e0d09824655519c
//
// All firmware calls are `unsafe`; safe wrappers exist only
// where the ABI and ownership have been proven (architecture §12.1).

/// Converts a recovered Thumb entry or callable address into the only valid
/// indirect-call address. Target-private ABI adapters must use this instead
/// of transmuting raw firmware addresses directly.
#[inline(always)]
pub const fn canopus_thumb_callable(entry_or_callable: usize) -> usize {
    entry_or_callable | 1usize
}

// ---- recovered type layouts ----
// `#[repr(C, packed(N))]` + explicit padding reproduces the exact
// recovered byte layout and its target-declared alignment.
pub type canopus_interconnect_recv_cb = extern "C" fn(*mut core::ffi::c_void, i32, *const canopus_interconnect_message, *const u8) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct file_operations {
    pub open: *mut core::ffi::c_void, // +0x0
    pub close: *mut core::ffi::c_void, // +0x4
    pub read: *mut core::ffi::c_void, // +0x8
    pub write: *mut core::ffi::c_void, // +0xc
    pub lseek: *mut core::ffi::c_void, // +0x10
    pub ioctl: *mut core::ffi::c_void, // +0x14
    pub _pad_18: [u8; 0x8], // 8
    pub fsync: *mut core::ffi::c_void, // +0x20
    pub _tail: [u8; 0xc], // 12
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_order_record {
    pub app_name: [u8; 128], // +0x0
    pub _pad_80: [u8; 0x4], // 4
    pub flags: u32, // +0x84
    pub _tail: [u8; 0x4], // 4
}

pub type canopus_lvx_event_cb = extern "C" fn(*mut core::ffi::c_void) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct stock_timespec_t {
    pub tv_sec: i64, // +0x0
    pub tv_nsec: i32, // +0x8
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_thirdparty_message_content {
    pub message_id: u32, // +0x0
    pub message_kind: u16, // +0x4
    pub _pad_6: [u8; 0xa], // 10
    pub package_name: *mut core::ffi::c_void, // +0x10
    pub fingerprint_blob: *mut core::ffi::c_void, // +0x14
    pub payload_blob: *mut core::ffi::c_void, // +0x18
    pub _tail: [u8; 0x10c], // 268
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct firmware_page_descriptor {
    pub parent_descriptor: *mut core::ffi::c_void, // +0x0
    pub _pad_4: [u8; 0xc], // 12
    pub page_name: *mut core::ffi::c_void, // +0x10
    pub page_id: u16, // +0x14
    pub app_id: u16, // +0x16
    pub flags: u16, // +0x18
    pub _pad_1a: [u8; 0x2], // 2
    pub scheduler_deadline: i32, // +0x1c
    pub scheduler_priority: i32, // +0x20
    pub async_destroy_state: u32, // +0x24
    pub lifecycle_state: u8, // +0x28
    pub layer: u8, // +0x29
    pub page_kind: u8, // +0x2a
    pub _pad_2b: [u8; 0x1], // 1
    pub activity_context: *mut core::ffi::c_void, // +0x2c
    pub root_object: *mut core::ffi::c_void, // +0x30
    pub on_signal: *mut core::ffi::c_void, // +0x34
    pub runtime_default_56: *mut core::ffi::c_void, // +0x38
    pub _pad_3c: [u8; 0x4], // 4
    pub registry_prev: *mut core::ffi::c_void, // +0x40
    pub registry_next: *mut core::ffi::c_void, // +0x44
    pub runtime_parent: *mut core::ffi::c_void, // +0x48
    pub on_create: *mut core::ffi::c_void, // +0x4c
    pub on_resume: *mut core::ffi::c_void, // +0x50
    pub on_foreground_data: *mut core::ffi::c_void, // +0x54
    pub on_pause: *mut core::ffi::c_void, // +0x58
    pub on_destroy: *mut core::ffi::c_void, // +0x5c
    pub on_ui_destroy: *mut core::ffi::c_void, // +0x60
    pub extension_callback_100: *mut core::ffi::c_void, // +0x64
    pub extension_callback_104: *mut core::ffi::c_void, // +0x68
    pub extension_callback_108: *mut core::ffi::c_void, // +0x6c
    pub _tail: [u8; 0x4], // 4
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_interconnect_app_info {
    pub package_name: *mut core::ffi::c_void, // +0x0
    pub display_name: *mut core::ffi::c_void, // +0x4
    pub icon_file: *mut core::ffi::c_void, // +0x8
    pub extra: *mut core::ffi::c_void, // +0xc
    pub fingerprint: [u8; 20], // +0x10
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct firmware_notification_message {
    pub message_id: u64, // +0x0
    pub repeat_count: u32, // +0x8
    pub title: *mut core::ffi::c_void, // +0xc
    pub source: *mut core::ffi::c_void, // +0x10
    pub body: *mut core::ffi::c_void, // +0x14
    pub auxiliary_text: *mut core::ffi::c_void, // +0x18
    pub small_icon_path: *mut core::ffi::c_void, // +0x1c
    pub large_icon_path: *mut core::ffi::c_void, // +0x20
    pub extension_text_36: *mut core::ffi::c_void, // +0x24
    pub extension_text_40: *mut core::ffi::c_void, // +0x28
    pub timestamp: u32, // +0x2c
    pub _pad_30: [u8; 0x8], // 8
    pub action_callback: *mut core::ffi::c_void, // +0x38
    pub action_context: u32, // +0x3c
    pub extension_64: u32, // +0x40
    pub extension_68: u32, // +0x44
    pub open_callback: *mut core::ffi::c_void, // +0x48
    pub destroy_callback: *mut core::ffi::c_void, // +0x4c
    pub start_reminder: u8, // +0x50
    pub flags_81: u8, // +0x51
    pub flags_82: u8, // +0x52
    pub _pad_53: [u8; 0x1], // 1
    pub callback_data: *mut core::ffi::c_void, // +0x54
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct service_object {
    pub enabled_state: u8, // +0x0
    pub _pad_1: [u8; 0x3], // 3
    pub name: *mut core::ffi::c_void, // +0x4
    pub service_id: u8, // +0x8
    pub profile_group: u8, // +0x9
    pub _pad_a: [u8; 0x1a], // 26
    pub startup_cb: *mut core::ffi::c_void, // +0x24
    pub _pad_28: [u8; 0x8], // 8
    pub startup_eligibility_cb: *mut core::ffi::c_void, // +0x30
    pub get_profile_cb: *mut core::ffi::c_void, // +0x34
    pub cleanup_cb: *mut core::ffi::c_void, // +0x38
    pub _tail: [u8; 0x4], // 4
}

pub type canopus_interconnect_send_done = extern "C" fn(*mut core::ffi::c_void, i32, *const canopus_interconnect_message, *mut core::ffi::c_void) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_interconnect_message {
    pub r#type: u8, // +0x0
    pub _pad_1: [u8; 0x3], // 3
    pub length: u32, // +0x4
    pub _pad_8: [u8; 0x8], // 8
    pub value: *mut core::ffi::c_void, // +0x10
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct ordered_app_entry {
    pub app_name: *mut core::ffi::c_void, // +0x0
    pub _pad_4: [u8; 0x4], // 4
    pub enabled: u8, // +0x8
    pub hidden: u8, // +0x9
    pub _tail: [u8; 0x6], // 6
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_struct {
    pub name: [u8; 128], // +0x0
    pub flags: u8, // +0x80
    pub _tail: [u8; 0x3], // 3
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_record {
    pub app_id: u16, // +0x0
    pub _pad_2: [u8; 0x2], // 2
    pub icon_handle: *mut core::ffi::c_void, // +0x4
    pub name: *mut core::ffi::c_void, // +0x8
    pub icon_name: *mut core::ffi::c_void, // +0xc
    pub _pad_10: [u8; 0x4], // 4
    pub flags: u8, // +0x14
    pub _tail: [u8; 0x3], // 3
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_descriptor {
    pub registry_links: u64, // +0x0
    pub package_name: *mut core::ffi::c_void, // +0x8
    pub launcher_icon_resource: *mut core::ffi::c_void, // +0xc
    pub app_id: u16, // +0x10
    pub flags: u16, // +0x12
    pub owned_string_20: *mut core::ffi::c_void, // +0x14
    pub owned_string_24: *mut core::ffi::c_void, // +0x18
    pub launcher_metadata_callback: *mut core::ffi::c_void, // +0x1c
    pub _pad_20: [u8; 0xc], // 12
    pub page_registry: *mut core::ffi::c_void, // +0x2c
    pub _pad_30: [u8; 0x8], // 8
    pub hidden_flags: u8, // +0x38
    pub _tail: [u8; 0x3], // 3
}

// ---- runtime identity guard ----
/// Returns 0 when the running firmware matches this pack's
/// version + build identity, -1 otherwise. Call once before use.
pub fn canopus_identity_guard() -> i32 {
    const EXPECT_VERSION: &[u8] = b"3.1.175";
    const EXPECT_BUILD: &[u8] = b"CONBINE_LTALM054_T1175_04141021_release_5793";
    if !c_str_eq(0x0C080810, EXPECT_VERSION) { return -1; }
    if !c_str_eq(0x0C080850, EXPECT_BUILD) { return -1; }
    0
}

/// Compares a NUL-terminated string at `addr` to `expected`.
fn c_str_eq(addr: usize, expected: &[u8]) -> bool {
    let mut i = 0usize;
    while i <= expected.len() && i < 64 {
        let b = unsafe { *((addr + i) as *const u8) };
        if i < expected.len() {
            if b != expected[i] { return false; }
        } else {
            return b == 0;
        }
        i += 1;
    }
    false
}

// ---- typed firmware bindings (unsafe) ----
/// Recovered `bt_l2cap_submit_cid` at 0x0C39E57E. Thumb callable address 0x0C39E57F.
pub const CANOPUS_FW_BT_L2CAP_SUBMIT_CID_CALLABLE: usize = canopus_thumb_callable(0x0C39E57Fusize);

/// Recovered global `bt_l2cap_owner` at 0x200D5F20.
pub const canopus_fw_bt_l2cap_owner: usize = 0x200D5F20usize;

/// Recovered `lvx_object_set_size` at 0x0C23DDE0. Thumb callable address 0x0C23DDE1.
pub const CANOPUS_FW_LVX_OBJECT_SET_SIZE_CALLABLE: usize = canopus_thumb_callable(0x0C23DDE1usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_object_set_size(a0: *mut core::ffi::c_void, a1: i32, a2: i32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, i32, i32) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LVX_OBJECT_SET_SIZE_CALLABLE) };
    f(a0, a1, a2);
}

/// Recovered `lvx_page_title_create` at 0x0C2781D4. Thumb callable address 0x0C2781D5.
pub const CANOPUS_FW_LVX_PAGE_TITLE_CREATE_CALLABLE: usize = canopus_thumb_callable(0x0C2781D5usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_page_title_create(a0: *mut core::ffi::c_void, a1: *const u8, a2: u32, a3: canopus_lvx_event_cb, a4: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, u32, canopus_lvx_event_cb, *mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_LVX_PAGE_TITLE_CREATE_CALLABLE) };
    f(a0, a1, a2, a3, a4)
}

/// Recovered `bt_gap_client_cleanup` at 0x0C3BFA40. Thumb callable address 0x0C3BFA41.
pub const CANOPUS_FW_BT_GAP_CLIENT_CLEANUP_CALLABLE: usize = canopus_thumb_callable(0x0C3BFA41usize);

/// Recovered `lvx_align_to` at 0x0C240CE8. Thumb callable address 0x0C240CE9.
pub const CANOPUS_FW_LVX_ALIGN_TO_CALLABLE: usize = canopus_thumb_callable(0x0C240CE9usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_align_to(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void, a2: u32, a3: i32, a4: i32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void, u32, i32, i32) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LVX_ALIGN_TO_CALLABLE) };
    f(a0, a1, a2, a3, a4);
}

/// Recovered `lv_img_create` at 0x0C261644. Thumb callable address 0x0C261645.
pub const CANOPUS_FW_LV_IMG_CREATE_CALLABLE: usize = canopus_thumb_callable(0x0C261645usize);

/// Recovered `interconnect_close` at 0x0C4F7170. Thumb callable address 0x0C4F7171.
pub const CANOPUS_FW_INTERCONNECT_CLOSE_CALLABLE: usize = canopus_thumb_callable(0x0C4F7171usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_interconnect_close(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_INTERCONNECT_CLOSE_CALLABLE) };
    f(a0)
}

/// Recovered `bt_remove_bond` at 0x0C3BFE98. Thumb callable address 0x0C3BFE99.
pub const CANOPUS_FW_BT_REMOVE_BOND_CALLABLE: usize = canopus_thumb_callable(0x0C3BFE99usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_remove_bond(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_BT_REMOVE_BOND_CALLABLE) };
    f(a0, a1)
}

/// Recovered `mm_free` at 0x0C0F19DC. Thumb callable address 0x0C0F19DD.
pub const CANOPUS_FW_MM_FREE_CALLABLE: usize = canopus_thumb_callable(0x0C0F19DDusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_mm_free(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void) -> () = unsafe { core::mem::transmute(CANOPUS_FW_MM_FREE_CALLABLE) };
    f(a0, a1);
}

/// Recovered `mpu_region_configure` at 0x0C51D758. Thumb callable address 0x0C51D759.
pub const CANOPUS_FW_MPU_REGION_CONFIGURE_CALLABLE: usize = canopus_thumb_callable(0x0C51D759usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_mpu_region_configure(a0: u32, a1: u32, a2: u32, a3: u32, a4: u32) -> i32 {
    let f: extern "C" fn(u32, u32, u32, u32, u32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_MPU_REGION_CONFIGURE_CALLABLE) };
    f(a0, a1, a2, a3, a4)
}

/// Recovered `bt_discovery_stop` at 0x0C3C002C. Thumb callable address 0x0C3C002D.
pub const CANOPUS_FW_BT_DISCOVERY_STOP_CALLABLE: usize = canopus_thumb_callable(0x0C3C002Dusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_discovery_stop(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_BT_DISCOVERY_STOP_CALLABLE) };
    f(a0)
}

/// Recovered `write` at 0x0C380106. Thumb callable address 0x0C380107.
pub const CANOPUS_FW_WRITE_CALLABLE: usize = canopus_thumb_callable(0x0C380107usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_write(a0: i32, a1: *const core::ffi::c_void, a2: u32) -> i32 {
    let f: extern "C" fn(i32, *const core::ffi::c_void, u32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_WRITE_CALLABLE) };
    f(a0, a1, a2)
}

/// Recovered `mm_alloc` at 0x0C0F24E0. Thumb callable address 0x0C0F24E1.
pub const CANOPUS_FW_MM_ALLOC_CALLABLE: usize = canopus_thumb_callable(0x0C0F24E1usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_mm_alloc(a0: u32) -> *mut core::ffi::c_void {
    let f: extern "C" fn(u32) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_MM_ALLOC_CALLABLE) };
    f(a0)
}

/// Recovered `thirdparty_submit_message_content` at 0x0C4CF24A. Thumb callable address 0x0C4CF24B.
pub const CANOPUS_FW_THIRDPARTY_SUBMIT_MESSAGE_CONTENT_CALLABLE: usize = canopus_thumb_callable(0x0C4CF24Busize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_thirdparty_submit_message_content(a0: *const core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*const core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_THIRDPARTY_SUBMIT_MESSAGE_CONTENT_CALLABLE) };
    f(a0)
}

/// Recovered `unlink` at 0x0C3800E8. Thumb callable address 0x0C3800E9.
pub const CANOPUS_FW_UNLINK_CALLABLE: usize = canopus_thumb_callable(0x0C3800E9usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_unlink(a0: *const u8) -> i32 {
    let f: extern "C" fn(*const u8) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_UNLINK_CALLABLE) };
    f(a0)
}

/// Recovered `mm_memalign_default` at 0x0C0F21EC. Thumb callable address 0x0C0F21ED.
pub const CANOPUS_FW_MM_MEMALIGN_DEFAULT_CALLABLE: usize = canopus_thumb_callable(0x0C0F21EDusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_mm_memalign_default(a0: u32, a1: u32) -> *mut core::ffi::c_void {
    let f: extern "C" fn(u32, u32) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_MM_MEMALIGN_DEFAULT_CALLABLE) };
    f(a0, a1)
}

/// Recovered `app_install` at 0x0C44B5D0. Thumb callable address 0x0C44B5D1.
pub const CANOPUS_FW_APP_INSTALL_CALLABLE: usize = canopus_thumb_callable(0x0C44B5D1usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_app_install(a0: *const launcher_app_descriptor, a1: *const *const firmware_page_descriptor, a2: u32) -> i32 {
    let f: extern "C" fn(*const launcher_app_descriptor, *const *const firmware_page_descriptor, u32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_APP_INSTALL_CALLABLE) };
    f(a0, a1, a2)
}

/// Recovered `bt_pair_request_reply` at 0x0C3BFD48. Thumb callable address 0x0C3BFD49.
pub const CANOPUS_FW_BT_PAIR_REQUEST_REPLY_CALLABLE: usize = canopus_thumb_callable(0x0C3BFD49usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_pair_request_reply(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_BT_PAIR_REQUEST_REPLY_CALLABLE) };
    f(a0)
}

/// Recovered `lvx_timer_create` at 0x0C25CB8C. Thumb callable address 0x0C25CB8D.
pub const CANOPUS_FW_LVX_TIMER_CREATE_CALLABLE: usize = canopus_thumb_callable(0x0C25CB8Dusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_timer_create(a0: canopus_lvx_event_cb, a1: u32, a2: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(canopus_lvx_event_cb, u32, *mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_LVX_TIMER_CREATE_CALLABLE) };
    f(a0, a1, a2)
}

/// Recovered global `bt_l2cap_submit_context` at 0x200D5C7C.
pub const canopus_fw_bt_l2cap_submit_context: usize = 0x200D5C7Cusize;

/// Recovered `mpu_region_allocate` at 0x0C51D8D0. Thumb callable address 0x0C51D8D1.
pub const CANOPUS_FW_MPU_REGION_ALLOCATE_CALLABLE: usize = canopus_thumb_callable(0x0C51D8D1usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_mpu_region_allocate() -> u32 {
    let f: extern "C" fn() -> u32 = unsafe { core::mem::transmute(CANOPUS_FW_MPU_REGION_ALLOCATE_CALLABLE) };
    f()
}

/// Recovered `lvx_label_set_text` at 0x0C266C28. Thumb callable address 0x0C266C29.
pub const CANOPUS_FW_LVX_LABEL_SET_TEXT_CALLABLE: usize = canopus_thumb_callable(0x0C266C29usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_label_set_text(a0: *mut core::ffi::c_void, a1: *const u8) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LVX_LABEL_SET_TEXT_CALLABLE) };
    f(a0, a1);
}

/// Recovered `bt_buffer_new` at 0x0C38AAA8. Thumb callable address 0x0C38AAA9.
pub const CANOPUS_FW_BT_BUFFER_NEW_CALLABLE: usize = canopus_thumb_callable(0x0C38AAA9usize);

/// Recovered `read` at 0x0C37F9EA. Thumb callable address 0x0C37F9EB.
pub const CANOPUS_FW_READ_CALLABLE: usize = canopus_thumb_callable(0x0C37F9EBusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_read(a0: i32, a1: *mut core::ffi::c_void, a2: u32) -> i32 {
    let f: extern "C" fn(i32, *mut core::ffi::c_void, u32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_READ_CALLABLE) };
    f(a0, a1, a2)
}

/// Recovered `app_lookup` at 0x0C449334. Thumb callable address 0x0C449335.
pub const CANOPUS_FW_APP_LOOKUP_CALLABLE: usize = canopus_thumb_callable(0x0C449335usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_app_lookup(a0: u16) -> *mut core::ffi::c_void {
    let f: extern "C" fn(u16) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_APP_LOOKUP_CALLABLE) };
    f(a0)
}

/// Recovered `lv_img_set_src` at 0x0C2645F8. Thumb callable address 0x0C2645F9.
pub const CANOPUS_FW_LV_IMG_SET_SRC_CALLABLE: usize = canopus_thumb_callable(0x0C2645F9usize);

/// Recovered `app_launcher_add` at 0x0C2A7CB8. Thumb callable address 0x0C2A7CB9.
pub const CANOPUS_FW_APP_LAUNCHER_ADD_CALLABLE: usize = canopus_thumb_callable(0x0C2A7CB9usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_app_launcher_add(a0: u16) -> i32 {
    let f: extern "C" fn(u16) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_APP_LAUNCHER_ADD_CALLABLE) };
    f(a0)
}

/// Recovered `sdp_commit` at 0x0C39ECD0. Thumb callable address 0x0C39ECD1.
pub const CANOPUS_FW_SDP_COMMIT_CALLABLE: usize = canopus_thumb_callable(0x0C39ECD1usize);

/// Recovered `close` at 0x0C37EFF8. Thumb callable address 0x0C37EFF9.
pub const CANOPUS_FW_CLOSE_CALLABLE: usize = canopus_thumb_callable(0x0C37EFF9usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_close(a0: i32) -> i32 {
    let f: extern "C" fn(i32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_CLOSE_CALLABLE) };
    f(a0)
}

/// Recovered `bt_timer_create_private` at 0x0C16A9C8. Thumb callable address 0x0C16A9C9.
pub const CANOPUS_FW_BT_TIMER_CREATE_PRIVATE_CALLABLE: usize = canopus_thumb_callable(0x0C16A9C9usize);

/// Recovered `mm_free_default` at 0x0C0F1B00. Thumb callable address 0x0C0F1B01.
pub const CANOPUS_FW_MM_FREE_DEFAULT_CALLABLE: usize = canopus_thumb_callable(0x0C0F1B01usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_mm_free_default(a0: *mut core::ffi::c_void) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void) -> () = unsafe { core::mem::transmute(CANOPUS_FW_MM_FREE_DEFAULT_CALLABLE) };
    f(a0);
}

/// Recovered `bt_create_bond` at 0x0C3BFDE0. Thumb callable address 0x0C3BFDE1.
pub const CANOPUS_FW_BT_CREATE_BOND_CALLABLE: usize = canopus_thumb_callable(0x0C3BFDE1usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_create_bond(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_BT_CREATE_BOND_CALLABLE) };
    f(a0, a1)
}

/// Recovered `interconnect_connect` at 0x0C1134D4. Thumb callable address 0x0C1134D5.
pub const CANOPUS_FW_INTERCONNECT_CONNECT_CALLABLE: usize = canopus_thumb_callable(0x0C1134D5usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_interconnect_connect(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void, a2: *const u8, a3: *const u8, a4: canopus_interconnect_recv_cb) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void, *const u8, *const u8, canopus_interconnect_recv_cb) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_INTERCONNECT_CONNECT_CALLABLE) };
    f(a0, a1, a2, a3, a4)
}

/// Recovered `lvx_list_row_set_trailing` at 0x0C272E1C. Thumb callable address 0x0C272E1D.
pub const CANOPUS_FW_LVX_LIST_ROW_SET_TRAILING_CALLABLE: usize = canopus_thumb_callable(0x0C272E1Dusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_list_row_set_trailing(a0: *mut core::ffi::c_void, a1: u8, a2: u8) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, u8, u8) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_LVX_LIST_ROW_SET_TRAILING_CALLABLE) };
    f(a0, a1, a2)
}

/// Recovered `bt_l2cap_connect_private` at 0x0C39E90C. Thumb callable address 0x0C39E90D.
pub const CANOPUS_FW_BT_L2CAP_CONNECT_PRIVATE_CALLABLE: usize = canopus_thumb_callable(0x0C39E90Dusize);

/// Recovered `unregister_driver` at 0x0C381C00. Thumb callable address 0x0C381C01.
pub const CANOPUS_FW_UNREGISTER_DRIVER_CALLABLE: usize = canopus_thumb_callable(0x0C381C01usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_unregister_driver(a0: *const u8) -> i32 {
    let f: extern "C" fn(*const u8) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_UNREGISTER_DRIVER_CALLABLE) };
    f(a0)
}

/// Recovered `bt_gap_client_create` at 0x0C3BC1FC. Thumb callable address 0x0C3BC1FD.
pub const CANOPUS_FW_BT_GAP_CLIENT_CREATE_CALLABLE: usize = canopus_thumb_callable(0x0C3BC1FDusize);

/// Recovered global `default_heap` at 0x200B17F4.
pub const canopus_fw_default_heap: usize = 0x200B17F4usize;

/// Recovered `lvx_list_row_update` at 0x0C2797B8. Thumb callable address 0x0C2797B9.
pub const CANOPUS_FW_LVX_LIST_ROW_UPDATE_CALLABLE: usize = canopus_thumb_callable(0x0C2797B9usize);
// lvx_list_row_update: skipped (argument type not mappable)
/// Recovered `register_driver` at 0x0C4F0108. Thumb callable address 0x0C4F0109.
pub const CANOPUS_FW_REGISTER_DRIVER_CALLABLE: usize = canopus_thumb_callable(0x0C4F0109usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_register_driver(a0: *const u8, a1: *const core::ffi::c_void, a2: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*const u8, *const core::ffi::c_void, *mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_REGISTER_DRIVER_CALLABLE) };
    f(a0, a1, a2)
}

/// Recovered `bt_discovery_start` at 0x0C3BFFC0. Thumb callable address 0x0C3BFFC1.
pub const CANOPUS_FW_BT_DISCOVERY_START_CALLABLE: usize = canopus_thumb_callable(0x0C3BFFC1usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_discovery_start(a0: *mut core::ffi::c_void, a1: i32) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, i32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_BT_DISCOVERY_START_CALLABLE) };
    f(a0, a1)
}

/// Recovered `bt_timer_start_private` at 0x0C16AA60. Thumb callable address 0x0C16AA61.
pub const CANOPUS_FW_BT_TIMER_START_PRIVATE_CALLABLE: usize = canopus_thumb_callable(0x0C16AA61usize);

/// Recovered `open` at 0x0C37F760. Thumb callable address 0x0C37F761.
pub const CANOPUS_FW_OPEN_CALLABLE: usize = canopus_thumb_callable(0x0C37F761usize);
// open: skipped (argument type not mappable)
/// Recovered `page_goto` at 0x0C49E7CC. Thumb callable address 0x0C49E7CD.
pub const CANOPUS_FW_PAGE_GOTO_CALLABLE: usize = canopus_thumb_callable(0x0C49E7CDusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_page_goto(a0: u32, a1: u32, a2: u32, a3: u32) -> i32 {
    let f: extern "C" fn(u32, u32, u32, u32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_PAGE_GOTO_CALLABLE) };
    f(a0, a1, a2, a3)
}

/// Recovered `sdp_set_raw_attribute` at 0x0C39EB3E. Thumb callable address 0x0C39EB3F.
pub const CANOPUS_FW_SDP_SET_RAW_ATTRIBUTE_CALLABLE: usize = canopus_thumb_callable(0x0C39EB3Fusize);

/// Recovered `lvx_object_align` at 0x0C23DE6A. Thumb callable address 0x0C23DE6B.
pub const CANOPUS_FW_LVX_OBJECT_ALIGN_CALLABLE: usize = canopus_thumb_callable(0x0C23DE6Busize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_object_align(a0: *mut core::ffi::c_void, a1: u32, a2: i32, a3: i32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, u32, i32, i32) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LVX_OBJECT_ALIGN_CALLABLE) };
    f(a0, a1, a2, a3);
}

/// Recovered `clock_gettime` at 0x0C0BBB10. Thumb callable address 0x0C0BBB11.
pub const CANOPUS_FW_CLOCK_GETTIME_CALLABLE: usize = canopus_thumb_callable(0x0C0BBB11usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_clock_gettime(a0: u32, a1: *const stock_timespec_t) -> i32 {
    let f: extern "C" fn(u32, *const stock_timespec_t) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_CLOCK_GETTIME_CALLABLE) };
    f(a0, a1)
}

/// Recovered `quickapp_register_app` at 0x0C2C655C. Thumb callable address 0x0C2C655D.
pub const CANOPUS_FW_QUICKAPP_REGISTER_APP_CALLABLE: usize = canopus_thumb_callable(0x0C2C655Dusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_quickapp_register_app(a0: u16, a1: *const canopus_interconnect_app_info) -> i32 {
    let f: extern "C" fn(u16, *const canopus_interconnect_app_info) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_QUICKAPP_REGISTER_APP_CALLABLE) };
    f(a0, a1)
}

/// Recovered `lv_bar_set_range` at 0x0C25E57C. Thumb callable address 0x0C25E57D.
pub const CANOPUS_FW_LV_BAR_SET_RANGE_CALLABLE: usize = canopus_thumb_callable(0x0C25E57Dusize);

/// Recovered `errno_location` at 0x0C0E4B6C. Thumb callable address 0x0C0E4B6D.
pub const CANOPUS_FW_ERRNO_LOCATION_CALLABLE: usize = canopus_thumb_callable(0x0C0E4B6Dusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_errno_location() -> *const i32 {
    let f: extern "C" fn() -> *const i32 = unsafe { core::mem::transmute(CANOPUS_FW_ERRNO_LOCATION_CALLABLE) };
    f()
}

/// Recovered `page_finish` at 0x0C44FC90. Thumb callable address 0x0C44FC91.
pub const CANOPUS_FW_PAGE_FINISH_CALLABLE: usize = canopus_thumb_callable(0x0C44FC91usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_page_finish(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_PAGE_FINISH_CALLABLE) };
    f(a0)
}

/// Recovered `bt_timer_stop_private` at 0x0C16AAD8. Thumb callable address 0x0C16AAD9.
pub const CANOPUS_FW_BT_TIMER_STOP_PRIVATE_CALLABLE: usize = canopus_thumb_callable(0x0C16AAD9usize);

/// Recovered `manager_delete_watchface` at 0x0C44F470. Thumb callable address 0x0C44F471.
pub const CANOPUS_FW_MANAGER_DELETE_WATCHFACE_CALLABLE: usize = canopus_thumb_callable(0x0C44F471usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_manager_delete_watchface(a0: *const u8) -> i32 {
    let f: extern "C" fn(*const u8) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_MANAGER_DELETE_WATCHFACE_CALLABLE) };
    f(a0)
}

/// Recovered `lvx_object_clear_flag` at 0x0C23E96E. Thumb callable address 0x0C23E96F.
pub const CANOPUS_FW_LVX_OBJECT_CLEAR_FLAG_CALLABLE: usize = canopus_thumb_callable(0x0C23E96Fusize);

/// Recovered `bt_pair_display_reply` at 0x0C3BFD94. Thumb callable address 0x0C3BFD95.
pub const CANOPUS_FW_BT_PAIR_DISPLAY_REPLY_CALLABLE: usize = canopus_thumb_callable(0x0C3BFD95usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_pair_display_reply(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_BT_PAIR_DISPLAY_REPLY_CALLABLE) };
    f(a0)
}

/// Recovered `lv_bar_create` at 0x0C262EC8. Thumb callable address 0x0C262EC9.
pub const CANOPUS_FW_LV_BAR_CREATE_CALLABLE: usize = canopus_thumb_callable(0x0C262EC9usize);

/// Recovered `fsync` at 0x0C380148. Thumb callable address 0x0C380149.
pub const CANOPUS_FW_FSYNC_CALLABLE: usize = canopus_thumb_callable(0x0C380149usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_fsync(a0: i32) -> i32 {
    let f: extern "C" fn(i32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_FSYNC_CALLABLE) };
    f(a0)
}

/// Recovered `lvx_timer_delete` at 0x0C25B4B8. Thumb callable address 0x0C25B4B9.
pub const CANOPUS_FW_LVX_TIMER_DELETE_CALLABLE: usize = canopus_thumb_callable(0x0C25B4B9usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_timer_delete(a0: *mut core::ffi::c_void) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LVX_TIMER_DELETE_CALLABLE) };
    f(a0);
}

/// Recovered `bt_queue_external` at 0x0C391BC8. Thumb callable address 0x0C391BC9.
pub const CANOPUS_FW_BT_QUEUE_EXTERNAL_CALLABLE: usize = canopus_thumb_callable(0x0C391BC9usize);

/// Recovered `lvx_notification_insert_message` at 0x0C4F1C44. Thumb callable address 0x0C4F1C45.
pub const CANOPUS_FW_LVX_NOTIFICATION_INSERT_MESSAGE_CALLABLE: usize = canopus_thumb_callable(0x0C4F1C45usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_notification_insert_message(a0: *const firmware_notification_message) -> i32 {
    let f: extern "C" fn(*const firmware_notification_message) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_LVX_NOTIFICATION_INSERT_MESSAGE_CALLABLE) };
    f(a0)
}

/// Recovered global `interconnect_loop` at 0x200C9D28.
pub const canopus_fw_interconnect_loop: usize = 0x200C9D28usize;

/// Recovered global `style_misans_demibold_32` at 0x200CA048.
pub const canopus_fw_style_misans_demibold_32: usize = 0x200CA048usize;

/// Recovered `lvx_event_add` at 0x0C244F3C. Thumb callable address 0x0C244F3D.
pub const CANOPUS_FW_LVX_EVENT_ADD_CALLABLE: usize = canopus_thumb_callable(0x0C244F3Dusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_event_add(a0: *mut core::ffi::c_void, a1: canopus_lvx_event_cb, a2: u32, a3: *mut core::ffi::c_void) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, canopus_lvx_event_cb, u32, *mut core::ffi::c_void) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LVX_EVENT_ADD_CALLABLE) };
    f(a0, a1, a2, a3);
}

/// Recovered `bt_adapter_get_instance` at 0x0C3BCAA8. Thumb callable address 0x0C3BCAA9.
pub const CANOPUS_FW_BT_ADAPTER_GET_INSTANCE_CALLABLE: usize = canopus_thumb_callable(0x0C3BCAA9usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_adapter_get_instance() -> *mut core::ffi::c_void {
    let f: extern "C" fn() -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_BT_ADAPTER_GET_INSTANCE_CALLABLE) };
    f()
}

/// Recovered `lvx_label_create` at 0x0C261660. Thumb callable address 0x0C261661.
pub const CANOPUS_FW_LVX_LABEL_CREATE_CALLABLE: usize = canopus_thumb_callable(0x0C261661usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_label_create(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_LVX_LABEL_CREATE_CALLABLE) };
    f(a0)
}

/// Recovered `interconnect_send` at 0x0C114044. Thumb callable address 0x0C114045.
pub const CANOPUS_FW_INTERCONNECT_SEND_CALLABLE: usize = canopus_thumb_callable(0x0C114045usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_interconnect_send(a0: *mut core::ffi::c_void, a1: *const u8, a2: *const canopus_interconnect_message, a3: canopus_interconnect_send_done, a4: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, *const canopus_interconnect_message, canopus_interconnect_send_done, *mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_INTERCONNECT_SEND_CALLABLE) };
    f(a0, a1, a2, a3, a4)
}

/// Recovered `rename` at 0x0C37FA24. Thumb callable address 0x0C37FA25.
pub const CANOPUS_FW_RENAME_CALLABLE: usize = canopus_thumb_callable(0x0C37FA25usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_rename(a0: *const u8, a1: *const u8) -> i32 {
    let f: extern "C" fn(*const u8, *const u8) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_RENAME_CALLABLE) };
    f(a0, a1)
}

/// Recovered `lseek` at 0x0C37F648. Thumb callable address 0x0C37F649.
pub const CANOPUS_FW_LSEEK_CALLABLE: usize = canopus_thumb_callable(0x0C37F649usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lseek(a0: i32, a1: i64, a2: i32) -> i64 {
    let f: extern "C" fn(i32, i64, i32) -> i64 = unsafe { core::mem::transmute(CANOPUS_FW_LSEEK_CALLABLE) };
    f(a0, a1, a2)
}

/// Recovered `lvx_style_apply` at 0x0C371CA0. Thumb callable address 0x0C371CA1.
pub const CANOPUS_FW_LVX_STYLE_APPLY_CALLABLE: usize = canopus_thumb_callable(0x0C371CA1usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_style_apply(a0: *mut core::ffi::c_void, a1: *const core::ffi::c_void, a2: u32, a3: u32) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const core::ffi::c_void, u32, u32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_LVX_STYLE_APPLY_CALLABLE) };
    f(a0, a1, a2, a3)
}

/// Recovered `lv_bar_set_value` at 0x0C25E53C. Thumb callable address 0x0C25E53D.
pub const CANOPUS_FW_LV_BAR_SET_VALUE_CALLABLE: usize = canopus_thumb_callable(0x0C25E53Dusize);

/// Recovered `bt_get_bonded_devices` at 0x0C17AC40. Thumb callable address 0x0C17AC41.
pub const CANOPUS_FW_BT_GET_BONDED_DEVICES_CALLABLE: usize = canopus_thumb_callable(0x0C17AC41usize);

/// Recovered `bt_queue_free` at 0x0C38A0A8. Thumb callable address 0x0C38A0A9.
pub const CANOPUS_FW_BT_QUEUE_FREE_CALLABLE: usize = canopus_thumb_callable(0x0C38A0A9usize);

/// Recovered `lvx_list_row_create` at 0x0C2D9C08. Thumb callable address 0x0C2D9C09.
pub const CANOPUS_FW_LVX_LIST_ROW_CREATE_CALLABLE: usize = canopus_thumb_callable(0x0C2D9C09usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_list_row_create(a0: *mut core::ffi::c_void, a1: *const u8) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_LVX_LIST_ROW_CREATE_CALLABLE) };
    f(a0, a1)
}

/// Recovered `bt_l2cap_disconnect` at 0x0C39E990. Thumb callable address 0x0C39E991.
pub const CANOPUS_FW_BT_L2CAP_DISCONNECT_CALLABLE: usize = canopus_thumb_callable(0x0C39E991usize);

/// Recovered `mpu_region_release` at 0x0C51D928. Thumb callable address 0x0C51D929.
pub const CANOPUS_FW_MPU_REGION_RELEASE_CALLABLE: usize = canopus_thumb_callable(0x0C51D929usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_mpu_region_release(a0: u32) -> () {
    let f: extern "C" fn(u32) -> () = unsafe { core::mem::transmute(CANOPUS_FW_MPU_REGION_RELEASE_CALLABLE) };
    f(a0);
}

/// Recovered `lvx_object_add_flag` at 0x0C23E8F8. Thumb callable address 0x0C23E8F9.
pub const CANOPUS_FW_LVX_OBJECT_ADD_FLAG_CALLABLE: usize = canopus_thumb_callable(0x0C23E8F9usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_object_add_flag(a0: *mut core::ffi::c_void, a1: u32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, u32) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LVX_OBJECT_ADD_FLAG_CALLABLE) };
    f(a0, a1);
}

/// Recovered `bt_timer_delete_private` at 0x0C16AA30. Thumb callable address 0x0C16AA31.
pub const CANOPUS_FW_BT_TIMER_DELETE_PRIVATE_CALLABLE: usize = canopus_thumb_callable(0x0C16AA31usize);

/// Recovered `sdp_unregister` at 0x0C39EDE8. Thumb callable address 0x0C39EDE9.
pub const CANOPUS_FW_SDP_UNREGISTER_CALLABLE: usize = canopus_thumb_callable(0x0C39EDE9usize);

/// Recovered `sdp_builder_create` at 0x0C39EE30. Thumb callable address 0x0C39EE31.
pub const CANOPUS_FW_SDP_BUILDER_CREATE_CALLABLE: usize = canopus_thumb_callable(0x0C39EE31usize);

/// Recovered `lvx_list_row_trailing` at 0x0C272C8E. Thumb callable address 0x0C272C8F.
pub const CANOPUS_FW_LVX_LIST_ROW_TRAILING_CALLABLE: usize = canopus_thumb_callable(0x0C272C8Fusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_list_row_trailing(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_LVX_LIST_ROW_TRAILING_CALLABLE) };
    f(a0)
}

/// Recovered `bt_adapter_set_scan_mode_private` at 0x0C3BFF74. Thumb callable address 0x0C3BFF75.
pub const CANOPUS_FW_BT_ADAPTER_SET_SCAN_MODE_PRIVATE_CALLABLE: usize = canopus_thumb_callable(0x0C3BFF75usize);

// ---- excluded symbols ----
// bt_adapter_set_scan_mode_private: restricted - not exported until context/ownership approved
// bt_buffer_new: restricted - not exported until context/ownership approved
// bt_gap_client_cleanup: restricted - not exported until context/ownership approved
// bt_gap_client_create: restricted - not exported until context/ownership approved
// bt_get_bonded_devices: restricted - not exported until context/ownership approved
// bt_l2cap_connect_private: restricted - not exported until context/ownership approved
// bt_l2cap_disconnect: restricted - not exported until context/ownership approved
// bt_l2cap_submit_cid: restricted - not exported until context/ownership approved
// bt_queue_external: restricted - not exported until context/ownership approved
// bt_queue_free: restricted - not exported until context/ownership approved
// bt_timer_create_private: restricted - not exported until context/ownership approved
// bt_timer_delete_private: restricted - not exported until context/ownership approved
// bt_timer_start_private: restricted - not exported until context/ownership approved
// bt_timer_stop_private: restricted - not exported until context/ownership approved
// lv_bar_create: restricted - not exported until context/ownership approved
// lv_bar_set_range: restricted - not exported until context/ownership approved
// lv_bar_set_value: restricted - not exported until context/ownership approved
// lv_img_create: restricted - not exported until context/ownership approved
// lv_img_set_src: restricted - not exported until context/ownership approved
// lvx_object_clear_flag: restricted - not exported until context/ownership approved
// sdp_builder_create: restricted - not exported until context/ownership approved
// sdp_commit: restricted - not exported until context/ownership approved
// sdp_set_raw_attribute: restricted - not exported until context/ownership approved
// sdp_unregister: restricted - not exported until context/ownership approved

