// Generated by `canopus target generate-rust-bindings`. DO NOT EDIT.
//
// target_id: xiaomi-band-10-pro-3.101.043
// firmware : 3.101.043 (CONBINE_LTALM078_T3.101.043_08041658)
// sha256   : 519307675665e4866d722a8119a98589c397b614ac3294cb87bfc86de45756ec
// revision : 6
// input_digest: 08ecdd6e2f85ac44
//
// All firmware calls are `unsafe`; safe wrappers exist only
// where the ABI and ownership have been proven (architecture §12.1).

/// Converts a recovered Thumb entry or callable address into the only valid
/// indirect-call address. Target-private ABI adapters must use this instead
/// of transmuting raw firmware addresses directly.
#[inline(always)]
pub const fn canopus_thumb_callable(entry_or_callable: usize) -> usize {
    entry_or_callable | 1usize
}

// ---- recovered type layouts ----
// `#[repr(C, packed(N))]` + explicit padding reproduces the exact
// recovered byte layout and its target-declared alignment.
pub type canopus_interconnect_recv_cb = extern "C" fn(*mut core::ffi::c_void, i32, *const canopus_interconnect_message, *const u8) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct file_operations {
    pub open: *mut core::ffi::c_void, // +0x0
    pub close: *mut core::ffi::c_void, // +0x4
    pub read: *mut core::ffi::c_void, // +0x8
    pub write: *mut core::ffi::c_void, // +0xc
    pub lseek: *mut core::ffi::c_void, // +0x10
    pub ioctl: *mut core::ffi::c_void, // +0x14
    pub _tail: [u8; 0x18], // 24
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_order_record {
    pub app_name: [u8; 128], // +0x0
    pub _pad_80: [u8; 0x4], // 4
    pub flags: u32, // +0x84
    pub _tail: [u8; 0x4], // 4
}

pub type canopus_lvx_event_cb = extern "C" fn(*mut core::ffi::c_void) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct stock_timespec_t {
    pub tv_sec: i64, // +0x0
    pub tv_nsec: i32, // +0x8
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_thirdparty_message_content {
    pub message_id: u32, // +0x0
    pub message_kind: u16, // +0x4
    pub _pad_6: [u8; 0xa], // 10
    pub package_name: *mut core::ffi::c_void, // +0x10
    pub fingerprint_blob: *mut core::ffi::c_void, // +0x14
    pub payload_blob: *mut core::ffi::c_void, // +0x18
    pub _tail: [u8; 0x134], // 308
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct firmware_page_descriptor {
    pub parent_descriptor: *mut core::ffi::c_void, // +0x0
    pub _pad_4: [u8; 0xc], // 12
    pub page_name: *mut core::ffi::c_void, // +0x10
    pub page_id: u16, // +0x14
    pub app_id: u16, // +0x16
    pub flags: u16, // +0x18
    pub _pad_1a: [u8; 0x2], // 2
    pub scheduler_deadline: i32, // +0x1c
    pub scheduler_priority: i32, // +0x20
    pub async_destroy_state: u32, // +0x24
    pub lifecycle_state: u8, // +0x28
    pub layer: u8, // +0x29
    pub page_kind: u8, // +0x2a
    pub _pad_2b: [u8; 0x1], // 1
    pub activity_context: *mut core::ffi::c_void, // +0x2c
    pub root_object: *mut core::ffi::c_void, // +0x30
    pub on_signal: *mut core::ffi::c_void, // +0x34
    pub runtime_default_56: *mut core::ffi::c_void, // +0x38
    pub _pad_3c: [u8; 0x4], // 4
    pub registry_prev: *mut core::ffi::c_void, // +0x40
    pub registry_next: *mut core::ffi::c_void, // +0x44
    pub runtime_parent: *mut core::ffi::c_void, // +0x48
    pub on_create: *mut core::ffi::c_void, // +0x4c
    pub on_resume: *mut core::ffi::c_void, // +0x50
    pub on_foreground_data: *mut core::ffi::c_void, // +0x54
    pub on_pause: *mut core::ffi::c_void, // +0x58
    pub on_destroy: *mut core::ffi::c_void, // +0x5c
    pub on_ui_destroy: *mut core::ffi::c_void, // +0x60
    pub extension_callback_100: *mut core::ffi::c_void, // +0x64
    pub extension_callback_104: *mut core::ffi::c_void, // +0x68
    pub extension_callback_108: *mut core::ffi::c_void, // +0x6c
    pub _tail: [u8; 0x4], // 4
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_interconnect_app_info {
    pub package_name: *mut core::ffi::c_void, // +0x0
    pub display_name: *mut core::ffi::c_void, // +0x4
    pub icon_file: *mut core::ffi::c_void, // +0x8
    pub extra: *mut core::ffi::c_void, // +0xc
    pub fingerprint: [u8; 20], // +0x10
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct firmware_notification_message {
    pub message_id: u64, // +0x0
    pub repeat_count: u32, // +0x8
    pub title: *mut core::ffi::c_void, // +0xc
    pub source: *mut core::ffi::c_void, // +0x10
    pub body: *mut core::ffi::c_void, // +0x14
    pub auxiliary_text: *mut core::ffi::c_void, // +0x18
    pub small_icon_path: *mut core::ffi::c_void, // +0x1c
    pub large_icon_path: *mut core::ffi::c_void, // +0x20
    pub extension_text_36: *mut core::ffi::c_void, // +0x24
    pub extension_text_40: *mut core::ffi::c_void, // +0x28
    pub timestamp: u32, // +0x2c
    pub _pad_30: [u8; 0x8], // 8
    pub action_callback: *mut core::ffi::c_void, // +0x38
    pub action_context: u32, // +0x3c
    pub extension_64: u32, // +0x40
    pub extension_68: u32, // +0x44
    pub open_callback: *mut core::ffi::c_void, // +0x48
    pub destroy_callback: *mut core::ffi::c_void, // +0x4c
    pub start_reminder: u8, // +0x50
    pub flags_81: u8, // +0x51
    pub flags_82: u8, // +0x52
    pub _pad_53: [u8; 0x1], // 1
    pub callback_data: *mut core::ffi::c_void, // +0x54
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct service_object {
    pub enabled_state: u8, // +0x0
    pub _pad_1: [u8; 0x3], // 3
    pub name: *mut core::ffi::c_void, // +0x4
    pub service_id: u8, // +0x8
    pub profile_group: u8, // +0x9
    pub _pad_a: [u8; 0x1a], // 26
    pub startup_cb: *mut core::ffi::c_void, // +0x24
    pub _pad_28: [u8; 0x8], // 8
    pub startup_eligibility_cb: *mut core::ffi::c_void, // +0x30
    pub get_profile_cb: *mut core::ffi::c_void, // +0x34
    pub cleanup_cb: *mut core::ffi::c_void, // +0x38
    pub _tail: [u8; 0x4], // 4
}

pub type canopus_interconnect_send_done = extern "C" fn(*mut core::ffi::c_void, i32, *const canopus_interconnect_message, *mut core::ffi::c_void) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_interconnect_message {
    pub r#type: u8, // +0x0
    pub _pad_1: [u8; 0x3], // 3
    pub length: u32, // +0x4
    pub _pad_8: [u8; 0x8], // 8
    pub value: *mut core::ffi::c_void, // +0x10
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct ordered_app_entry {
    pub app_name: *mut core::ffi::c_void, // +0x0
    pub _pad_4: [u8; 0x4], // 4
    pub enabled: u8, // +0x8
    pub hidden: u8, // +0x9
    pub _tail: [u8; 0x6], // 6
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_struct {
    pub name: [u8; 128], // +0x0
    pub flags: u8, // +0x80
    pub _tail: [u8; 0x3], // 3
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_record {
    pub app_id: u16, // +0x0
    pub _pad_2: [u8; 0x2], // 2
    pub icon_handle: *mut core::ffi::c_void, // +0x4
    pub name: *mut core::ffi::c_void, // +0x8
    pub icon_name: *mut core::ffi::c_void, // +0xc
    pub _pad_10: [u8; 0x4], // 4
    pub flags: u8, // +0x14
    pub _tail: [u8; 0x3], // 3
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_descriptor {
    pub registry_links: u64, // +0x0
    pub package_name: *mut core::ffi::c_void, // +0x8
    pub launcher_icon_resource: *mut core::ffi::c_void, // +0xc
    pub app_id: u16, // +0x10
    pub flags: u8, // +0x12
    pub _pad_13: [u8; 0x1], // 1
    pub owned_string_20: *mut core::ffi::c_void, // +0x14
    pub owned_string_24: *mut core::ffi::c_void, // +0x18
    pub launcher_metadata_callback: *mut core::ffi::c_void, // +0x1c
    pub _pad_20: [u8; 0x10], // 16
    pub page_registry: *mut core::ffi::c_void, // +0x30
    pub _pad_34: [u8; 0x8], // 8
    pub hidden_flags: u8, // +0x3c
    pub _tail: [u8; 0x3], // 3
}

// ---- runtime identity guard ----
/// Returns 0 when the running firmware matches this pack's
/// version + build identity, -1 otherwise. Call once before use.
pub fn canopus_identity_guard() -> i32 {
    const EXPECT_VERSION: &[u8] = b"3.101.043";
    const EXPECT_BUILD: &[u8] = b"CONBINE_LTALM078_T3.101.043_08041658";
    if !c_str_eq(0x0C0C0810, EXPECT_VERSION) { return -1; }
    if !c_str_eq(0x0C0C0850, EXPECT_BUILD) { return -1; }
    0
}

/// Compares a NUL-terminated string at `addr` to `expected`.
fn c_str_eq(addr: usize, expected: &[u8]) -> bool {
    let mut i = 0usize;
    while i <= expected.len() && i < 64 {
        let b = unsafe { *((addr + i) as *const u8) };
        if i < expected.len() {
            if b != expected[i] { return false; }
        } else {
            return b == 0;
        }
        i += 1;
    }
    false
}

// ---- typed firmware bindings (unsafe) ----
/// Recovered `lv_obj_move_to_index` at 0xc589550. Thumb callable address 0xc589551.
pub const CANOPUS_FW_LV_OBJ_MOVE_TO_INDEX_CALLABLE: usize = canopus_thumb_callable(0xc589551usize);

/// Recovered `write` at 0xc1d2640. Thumb callable address 0xc1d2641.
pub const CANOPUS_FW_WRITE_CALLABLE: usize = canopus_thumb_callable(0xc1d2641usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_write(a0: i32, a1: *const core::ffi::c_void, a2: u32) -> i32 {
    let f: extern "C" fn(i32, *const core::ffi::c_void, u32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_WRITE_CALLABLE) };
    f(a0, a1, a2)
}

/// Recovered global `miwear_bt_cpevent_registration_handle` at 0x2013DBE0.
pub const canopus_fw_miwear_bt_cpevent_registration_handle: usize = 0x2013DBE0usize;

/// Recovered `watchface_reset_watchface` at 0xc5f36c0. Thumb callable address 0xc5f36c1.
pub const CANOPUS_FW_WATCHFACE_RESET_WATCHFACE_CALLABLE: usize = canopus_thumb_callable(0xc5f36c1usize);

/// Recovered `lvx_notification_insert_message` at 0xca9a898. Thumb callable address 0xca9a899.
pub const CANOPUS_FW_LVX_NOTIFICATION_INSERT_MESSAGE_CALLABLE: usize = canopus_thumb_callable(0xca9a899usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_notification_insert_message(a0: *const firmware_notification_message) -> i32 {
    let f: extern "C" fn(*const firmware_notification_message) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_LVX_NOTIFICATION_INSERT_MESSAGE_CALLABLE) };
    f(a0)
}

/// Recovered `lvx_content_pad_bottom` at 0xc5893c0. Thumb callable address 0xc5893c1.
pub const CANOPUS_FW_LVX_CONTENT_PAD_BOTTOM_CALLABLE: usize = canopus_thumb_callable(0xc5893c1usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_content_pad_bottom(a0: *mut core::ffi::c_void, a1: i32, a2: u32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, i32, u32) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LVX_CONTENT_PAD_BOTTOM_CALLABLE) };
    f(a0, a1, a2);
}

/// Recovered `lvx_list_item_update` at 0xc4c8904. Thumb callable address 0xc4c8905.
pub const CANOPUS_FW_LVX_LIST_ITEM_UPDATE_CALLABLE: usize = canopus_thumb_callable(0xc4c8905usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_list_item_update(a0: *mut core::ffi::c_void, a1: *const u8, a2: *const u8, a3: *const u8, a4: i32, a5: u8) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, *const u8, *const u8, i32, u8) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_LVX_LIST_ITEM_UPDATE_CALLABLE) };
    f(a0, a1, a2, a3, a4, a5)
}

/// Recovered `lv_obj_set_hidden` at 0xc588518. Thumb callable address 0xc588519.
pub const CANOPUS_FW_LV_OBJ_SET_HIDDEN_CALLABLE: usize = canopus_thumb_callable(0xc588519usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lv_obj_set_hidden(a0: *mut core::ffi::c_void, a1: u32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, u32) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LV_OBJ_SET_HIDDEN_CALLABLE) };
    f(a0, a1);
}

/// Recovered `unlink` at 0xc1d2354. Thumb callable address 0xc1d2355.
pub const CANOPUS_FW_UNLINK_CALLABLE: usize = canopus_thumb_callable(0xc1d2355usize);

/// Recovered `bt_l2cap_submit_cid` at 0xc805be8. Thumb callable address 0xc805be9.
pub const CANOPUS_FW_BT_L2CAP_SUBMIT_CID_CALLABLE: usize = canopus_thumb_callable(0xc805be9usize);

/// Recovered `unregister_blockdriver` at 0xc1b009c. Thumb callable address 0xc1b009d.
pub const CANOPUS_FW_UNREGISTER_BLOCKDRIVER_CALLABLE: usize = canopus_thumb_callable(0xc1b009dusize);

/// Recovered `sdp_builder_create` at 0xc80a684. Thumb callable address 0xc80a685.
pub const CANOPUS_FW_SDP_BUILDER_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc80a685usize);

/// Recovered `lv_timer_create` at 0xc587ed0. Thumb callable address 0xc587ed1.
pub const CANOPUS_FW_LV_TIMER_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc587ed1usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lv_timer_create(a0: canopus_lvx_event_cb, a1: u32, a2: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(canopus_lvx_event_cb, u32, *mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_LV_TIMER_CREATE_CALLABLE) };
    f(a0, a1, a2)
}

/// Recovered `lvx_label_create` at 0xc588f30. Thumb callable address 0xc588f31.
pub const CANOPUS_FW_LVX_LABEL_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc588f31usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_label_create(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_LVX_LABEL_CREATE_CALLABLE) };
    f(a0)
}

/// Recovered global `gap_host_receive_slot` at 0x2013C144.
pub const canopus_fw_gap_host_receive_slot: usize = 0x2013C144usize;

/// Recovered `register_blockdriver` at 0xc1affd8. Thumb callable address 0xc1affd9.
pub const CANOPUS_FW_REGISTER_BLOCKDRIVER_CALLABLE: usize = canopus_thumb_callable(0xc1affd9usize);

/// Recovered `lvx_style_apply` at 0xc4bf898. Thumb callable address 0xc4bf899.
pub const CANOPUS_FW_LVX_STYLE_APPLY_CALLABLE: usize = canopus_thumb_callable(0xc4bf899usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_style_apply(a0: *mut core::ffi::c_void, a1: *const core::ffi::c_void, a2: u32, a3: u32) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const core::ffi::c_void, u32, u32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_LVX_STYLE_APPLY_CALLABLE) };
    f(a0, a1, a2, a3)
}

/// Recovered `interconnect_send` at 0xc2e8684. Thumb callable address 0xc2e8685.
pub const CANOPUS_FW_INTERCONNECT_SEND_CALLABLE: usize = canopus_thumb_callable(0xc2e8685usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_interconnect_send(a0: *mut core::ffi::c_void, a1: *const u8, a2: *const canopus_interconnect_message, a3: canopus_interconnect_send_done, a4: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, *const canopus_interconnect_message, canopus_interconnect_send_done, *mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_INTERCONNECT_SEND_CALLABLE) };
    f(a0, a1, a2, a3, a4)
}

/// Recovered `bt_pair_request_reply` at 0xc3b0050. Thumb callable address 0xc3b0051.
pub const CANOPUS_FW_BT_PAIR_REQUEST_REPLY_CALLABLE: usize = canopus_thumb_callable(0xc3b0051usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_pair_request_reply(a0: *mut core::ffi::c_void, a1: *const u8, a2: i32) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, i32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_BT_PAIR_REQUEST_REPLY_CALLABLE) };
    f(a0, a1, a2)
}

/// Recovered `page_finish` at 0xca6b9e8. Thumb callable address 0xca6b9e9.
pub const CANOPUS_FW_PAGE_FINISH_CALLABLE: usize = canopus_thumb_callable(0xca6b9e9usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_page_finish(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_PAGE_FINISH_CALLABLE) };
    f(a0)
}

/// Recovered `errno_location` at 0xc1e45bc. Thumb callable address 0xc1e45bd.
pub const CANOPUS_FW_ERRNO_LOCATION_CALLABLE: usize = canopus_thumb_callable(0xc1e45bdusize);

/// Recovered `bt_adapter_get_scan_mode` at 0xc3b5698. Thumb callable address 0xc3b5699.
pub const CANOPUS_FW_BT_ADAPTER_GET_SCAN_MODE_CALLABLE: usize = canopus_thumb_callable(0xc3b5699usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_adapter_get_scan_mode() -> i32 {
    let f: extern "C" fn() -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_BT_ADAPTER_GET_SCAN_MODE_CALLABLE) };
    f()
}

/// Recovered `interconnect_close` at 0xc2e8758. Thumb callable address 0xc2e8759.
pub const CANOPUS_FW_INTERCONNECT_CLOSE_CALLABLE: usize = canopus_thumb_callable(0xc2e8759usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_interconnect_close(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_INTERCONNECT_CLOSE_CALLABLE) };
    f(a0)
}

/// Recovered `interconnect_connect` at 0xc2e85f4. Thumb callable address 0xc2e85f5.
pub const CANOPUS_FW_INTERCONNECT_CONNECT_CALLABLE: usize = canopus_thumb_callable(0xc2e85f5usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_interconnect_connect(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void, a2: *const u8, a3: canopus_interconnect_recv_cb) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void, *const u8, canopus_interconnect_recv_cb) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_INTERCONNECT_CONNECT_CALLABLE) };
    f(a0, a1, a2, a3)
}

/// Recovered `sem_wait` at 0xc206944. Thumb callable address 0xc206945.
pub const CANOPUS_FW_SEM_WAIT_CALLABLE: usize = canopus_thumb_callable(0xc206945usize);

/// Recovered global `bt_l2cap_owner` at 0x2013BDBC.
pub const canopus_fw_bt_l2cap_owner: usize = 0x2013BDBCusize;

/// Recovered `bt_adapter_set_scan_mode` at 0xc3b56a8. Thumb callable address 0xc3b56a9.
pub const CANOPUS_FW_BT_ADAPTER_SET_SCAN_MODE_CALLABLE: usize = canopus_thumb_callable(0xc3b56a9usize);

/// Recovered `lvx_object_align` at 0xc589188. Thumb callable address 0xc589189.
pub const CANOPUS_FW_LVX_OBJECT_ALIGN_CALLABLE: usize = canopus_thumb_callable(0xc589189usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_object_align(a0: *mut core::ffi::c_void, a1: u32, a2: i32, a3: i32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, u32, i32, i32) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LVX_OBJECT_ALIGN_CALLABLE) };
    f(a0, a1, a2, a3);
}

/// Recovered `insmod` at 0xc203a50. Thumb callable address 0xc203a51.
pub const CANOPUS_FW_INSMOD_CALLABLE: usize = canopus_thumb_callable(0xc203a51usize);

/// Recovered global `miwear_bt_adapter_instance` at 0x2013DBE4.
pub const canopus_fw_miwear_bt_adapter_instance: usize = 0x2013DBE4usize;

/// Recovered `app_launcher_add` at 0xc513a44. Thumb callable address 0xc513a45.
pub const CANOPUS_FW_APP_LAUNCHER_ADD_CALLABLE: usize = canopus_thumb_callable(0xc513a45usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_app_launcher_add(a0: u16) -> i32 {
    let f: extern "C" fn(u16) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_APP_LAUNCHER_ADD_CALLABLE) };
    f(a0)
}

/// Recovered `lvx_object_set_size` at 0xc588628. Thumb callable address 0xc588629.
pub const CANOPUS_FW_LVX_OBJECT_SET_SIZE_CALLABLE: usize = canopus_thumb_callable(0xc588629usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_object_set_size(a0: *mut core::ffi::c_void, a1: i32, a2: i32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, i32, i32) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LVX_OBJECT_SET_SIZE_CALLABLE) };
    f(a0, a1, a2);
}

/// Recovered `bt_free` at 0xc840c60. Thumb callable address 0xc840c61.
pub const CANOPUS_FW_BT_FREE_CALLABLE: usize = canopus_thumb_callable(0xc840c61usize);

/// Recovered `heap_malloc` at 0xc1f903c. Thumb callable address 0xc1f903d.
pub const CANOPUS_FW_HEAP_MALLOC_CALLABLE: usize = canopus_thumb_callable(0xc1f903dusize);

/// Recovered `driver_ioctl_dispatch` at 0xc1cff88. Thumb callable address 0xc1cff89.
pub const CANOPUS_FW_DRIVER_IOCTL_DISPATCH_CALLABLE: usize = canopus_thumb_callable(0xc1cff89usize);

/// Recovered `bt_create_bond_private` at 0xc3b6898. Thumb callable address 0xc3b6899.
pub const CANOPUS_FW_BT_CREATE_BOND_PRIVATE_CALLABLE: usize = canopus_thumb_callable(0xc3b6899usize);

/// Recovered `lv_obj_align_to` at 0xc588ef0. Thumb callable address 0xc588ef1.
pub const CANOPUS_FW_LV_OBJ_ALIGN_TO_CALLABLE: usize = canopus_thumb_callable(0xc588ef1usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lv_obj_align_to(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void, a2: u32, a3: i32, a4: i32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void, u32, i32, i32) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LV_OBJ_ALIGN_TO_CALLABLE) };
    f(a0, a1, a2, a3, a4);
}

/// Recovered `lvx_label_set_long_mode` at 0xc588bf8. Thumb callable address 0xc588bf9.
pub const CANOPUS_FW_LVX_LABEL_SET_LONG_MODE_CALLABLE: usize = canopus_thumb_callable(0xc588bf9usize);

/// Recovered `sem_trywait` at 0xc206bfc. Thumb callable address 0xc206bfd.
pub const CANOPUS_FW_SEM_TRYWAIT_CALLABLE: usize = canopus_thumb_callable(0xc206bfdusize);

/// Recovered `open` at 0xc1d0a28. Thumb callable address 0xc1d0a29.
pub const CANOPUS_FW_OPEN_CALLABLE: usize = canopus_thumb_callable(0xc1d0a29usize);
// open: skipped (argument type not mappable)
/// Recovered `register_driver` at 0xc1aff60. Thumb callable address 0xc1aff61.
pub const CANOPUS_FW_REGISTER_DRIVER_CALLABLE: usize = canopus_thumb_callable(0xc1aff61usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_register_driver(a0: *const u8, a1: *const core::ffi::c_void, a2: u32, a3: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*const u8, *const core::ffi::c_void, u32, *mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_REGISTER_DRIVER_CALLABLE) };
    f(a0, a1, a2, a3)
}

/// Recovered `service_manager_register` at 0xc3bdbac. Thumb callable address 0xc3bdbad.
pub const CANOPUS_FW_SERVICE_MANAGER_REGISTER_CALLABLE: usize = canopus_thumb_callable(0xc3bdbadusize);

/// Recovered `lvx_object_add_flag` at 0xcac00c0. Thumb callable address 0xcac00c1.
pub const CANOPUS_FW_LVX_OBJECT_ADD_FLAG_CALLABLE: usize = canopus_thumb_callable(0xcac00c1usize);

/// Recovered `app_launcher_del` at 0xc513b2c. Thumb callable address 0xc513b2d.
pub const CANOPUS_FW_APP_LAUNCHER_DEL_CALLABLE: usize = canopus_thumb_callable(0xc513b2dusize);

/// Recovered `bt_timer_add` at 0xc7eb270. Thumb callable address 0xc7eb271.
pub const CANOPUS_FW_BT_TIMER_ADD_CALLABLE: usize = canopus_thumb_callable(0xc7eb271usize);

/// Recovered `bt_adapter_get_state` at 0xc3af4f4. Thumb callable address 0xc3af4f5.
pub const CANOPUS_FW_BT_ADAPTER_GET_STATE_CALLABLE: usize = canopus_thumb_callable(0xc3af4f5usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_adapter_get_state(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_BT_ADAPTER_GET_STATE_CALLABLE) };
    f(a0)
}

/// Recovered `lvx_label_set_text` at 0xc589490. Thumb callable address 0xc589491.
pub const CANOPUS_FW_LVX_LABEL_SET_TEXT_CALLABLE: usize = canopus_thumb_callable(0xc589491usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_label_set_text(a0: *mut core::ffi::c_void, a1: *const u8) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LVX_LABEL_SET_TEXT_CALLABLE) };
    f(a0, a1);
}

/// Recovered global `stock_bt_callback_descriptor` at 0x2CD4A744.
pub const canopus_fw_stock_bt_callback_descriptor: usize = 0x2CD4A744usize;

/// Recovered `bt_adapter_register` at 0xc3af3e8. Thumb callable address 0xc3af3e9.
pub const CANOPUS_FW_BT_ADAPTER_REGISTER_CALLABLE: usize = canopus_thumb_callable(0xc3af3e9usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_adapter_register(a0: *mut core::ffi::c_void, a1: *const u32) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_BT_ADAPTER_REGISTER_CALLABLE) };
    f(a0, a1)
}

/// Recovered `lv_timer_del` at 0xc588128. Thumb callable address 0xc588129.
pub const CANOPUS_FW_LV_TIMER_DEL_CALLABLE: usize = canopus_thumb_callable(0xc588129usize);

/// Recovered `gap_host_stock_receive` at 0xc7ec47c. Thumb callable address 0xc7ec47d.
pub const CANOPUS_FW_GAP_HOST_STOCK_RECEIVE_CALLABLE: usize = canopus_thumb_callable(0xc7ec47dusize);

/// Recovered `page_goto` at 0xca6c358. Thumb callable address 0xca6c359.
pub const CANOPUS_FW_PAGE_GOTO_CALLABLE: usize = canopus_thumb_callable(0xca6c359usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_page_goto(a0: u32, a1: u32, a2: u32, a3: u32) -> i32 {
    let f: extern "C" fn(u32, u32, u32, u32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_PAGE_GOTO_CALLABLE) };
    f(a0, a1, a2, a3)
}

/// Recovered `lvx_list_row_trailing` at 0xc4c8c60. Thumb callable address 0xc4c8c61.
pub const CANOPUS_FW_LVX_LIST_ROW_TRAILING_CALLABLE: usize = canopus_thumb_callable(0xc4c8c61usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_list_row_trailing(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_LVX_LIST_ROW_TRAILING_CALLABLE) };
    f(a0)
}

/// Recovered `lvx_page_content_create` at 0xca67244. Thumb callable address 0xca67245.
pub const CANOPUS_FW_LVX_PAGE_CONTENT_CREATE_CALLABLE: usize = canopus_thumb_callable(0xca67245usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_page_content_create(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_LVX_PAGE_CONTENT_CREATE_CALLABLE) };
    f(a0)
}

/// Recovered `lvx_msgbox_create` at 0xc4ca0d8. Thumb callable address 0xc4ca0d9.
pub const CANOPUS_FW_LVX_MSGBOX_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc4ca0d9usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_msgbox_create(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_LVX_MSGBOX_CREATE_CALLABLE) };
    f(a0, a1)
}

/// Recovered `bt_buffer_new` at 0xc7eafbc. Thumb callable address 0xc7eafbd.
pub const CANOPUS_FW_BT_BUFFER_NEW_CALLABLE: usize = canopus_thumb_callable(0xc7eafbdusize);

/// Recovered global `style_misans_regular_24` at 0x2010CE44.
pub const canopus_fw_style_misans_regular_24: usize = 0x2010CE44usize;

/// Recovered `close` at 0xc1b9d80. Thumb callable address 0xc1b9d81.
pub const CANOPUS_FW_CLOSE_CALLABLE: usize = canopus_thumb_callable(0xc1b9d81usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_close(a0: i32) -> i32 {
    let f: extern "C" fn(i32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_CLOSE_CALLABLE) };
    f(a0)
}

/// Recovered `bt_queue_external` at 0xc7eb9cc. Thumb callable address 0xc7eb9cd.
pub const CANOPUS_FW_BT_QUEUE_EXTERNAL_CALLABLE: usize = canopus_thumb_callable(0xc7eb9cdusize);

/// Recovered `bt_alloc` at 0xc840c54. Thumb callable address 0xc840c55.
pub const CANOPUS_FW_BT_ALLOC_CALLABLE: usize = canopus_thumb_callable(0xc840c55usize);

/// Recovered `modhandle` at 0xc203a68. Thumb callable address 0xc203a69.
pub const CANOPUS_FW_MODHANDLE_CALLABLE: usize = canopus_thumb_callable(0xc203a69usize);

/// Recovered `watchface_manager_delete_watchface` at 0xca95c68. Thumb callable address 0xca95c69.
pub const CANOPUS_FW_WATCHFACE_MANAGER_DELETE_WATCHFACE_CALLABLE: usize = canopus_thumb_callable(0xca95c69usize);

/// Recovered `bt_get_bond_state` at 0xc3b5a60. Thumb callable address 0xc3b5a61.
pub const CANOPUS_FW_BT_GET_BOND_STATE_CALLABLE: usize = canopus_thumb_callable(0xc3b5a61usize);

/// Recovered `app_launcher_data_init` at 0xc513e90. Thumb callable address 0xc513e91.
pub const CANOPUS_FW_APP_LAUNCHER_DATA_INIT_CALLABLE: usize = canopus_thumb_callable(0xc513e91usize);

/// Recovered `lv_obj_set_local_style_prop` at 0xc107790. Thumb callable address 0xc107791.
pub const CANOPUS_FW_LV_OBJ_SET_LOCAL_STYLE_PROP_CALLABLE: usize = canopus_thumb_callable(0xc107791usize);

/// Recovered `read` at 0xc1d129c. Thumb callable address 0xc1d129d.
pub const CANOPUS_FW_READ_CALLABLE: usize = canopus_thumb_callable(0xc1d129dusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_read(a0: i32, a1: *mut core::ffi::c_void, a2: u32) -> i32 {
    let f: extern "C" fn(i32, *mut core::ffi::c_void, u32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_READ_CALLABLE) };
    f(a0, a1, a2)
}

/// Recovered `lv_bar_create` at 0xc0c21d8. Thumb callable address 0xc0c21d9.
pub const CANOPUS_FW_LV_BAR_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc0c21d9usize);

/// Recovered `thirdparty_submit_message_content` at 0xcaa5204. Thumb callable address 0xcaa5205.
pub const CANOPUS_FW_THIRDPARTY_SUBMIT_MESSAGE_CONTENT_CALLABLE: usize = canopus_thumb_callable(0xcaa5205usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_thirdparty_submit_message_content(a0: *const core::ffi::c_void, a1: u32, a2: u32) -> i32 {
    let f: extern "C" fn(*const core::ffi::c_void, u32, u32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_THIRDPARTY_SUBMIT_MESSAGE_CONTENT_CALLABLE) };
    f(a0, a1, a2)
}

/// Recovered `heap_free` at 0xc1f8ff8. Thumb callable address 0xc1f8ff9.
pub const CANOPUS_FW_HEAP_FREE_CALLABLE: usize = canopus_thumb_callable(0xc1f8ff9usize);

/// Recovered `lvx_list_row_create` at 0xc54ca3c. Thumb callable address 0xc54ca3d.
pub const CANOPUS_FW_LVX_LIST_ROW_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc54ca3dusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_list_row_create(a0: *mut core::ffi::c_void, a1: *const u8, a2: *const u8, a3: u8) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, *const u8, u8) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_LVX_LIST_ROW_CREATE_CALLABLE) };
    f(a0, a1, a2, a3)
}

/// Recovered `quickapp_register_app` at 0xc549678. Thumb callable address 0xc549679.
pub const CANOPUS_FW_QUICKAPP_REGISTER_APP_CALLABLE: usize = canopus_thumb_callable(0xc549679usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_quickapp_register_app(a0: u16, a1: *const canopus_interconnect_app_info) -> i32 {
    let f: extern "C" fn(u16, *const canopus_interconnect_app_info) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_QUICKAPP_REGISTER_APP_CALLABLE) };
    f(a0, a1)
}

/// Recovered `bt_get_pairing_state` at 0xc3b60a0. Thumb callable address 0xc3b60a1.
pub const CANOPUS_FW_BT_GET_PAIRING_STATE_CALLABLE: usize = canopus_thumb_callable(0xc3b60a1usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_get_pairing_state(a0: *const u8, a1: u32) -> u32 {
    let f: extern "C" fn(*const u8, u32) -> u32 = unsafe { core::mem::transmute(CANOPUS_FW_BT_GET_PAIRING_STATE_CALLABLE) };
    f(a0, a1)
}

/// Recovered `sdp_set_raw_attribute` at 0xc808244. Thumb callable address 0xc808245.
pub const CANOPUS_FW_SDP_SET_RAW_ATTRIBUTE_CALLABLE: usize = canopus_thumb_callable(0xc808245usize);

/// Recovered `core_bt_pair_request_callback` at 0xc709e90. Thumb callable address 0xc709e91.
pub const CANOPUS_FW_CORE_BT_PAIR_REQUEST_CALLBACK_CALLABLE: usize = canopus_thumb_callable(0xc709e91usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_core_bt_pair_request_callback(a0: *mut core::ffi::c_void, a1: *const u8) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_CORE_BT_PAIR_REQUEST_CALLBACK_CALLABLE) };
    f(a0, a1)
}

/// Recovered `bt_pair_display_reply` at 0xc3aff64. Thumb callable address 0xc3aff65.
pub const CANOPUS_FW_BT_PAIR_DISPLAY_REPLY_CALLABLE: usize = canopus_thumb_callable(0xc3aff65usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_pair_display_reply(a0: *mut core::ffi::c_void, a1: *const u8, a2: i32, a3: i32) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, i32, i32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_BT_PAIR_DISPLAY_REPLY_CALLABLE) };
    f(a0, a1, a2, a3)
}

/// Recovered `lvx_image_set_scale` at 0xc179db0. Thumb callable address 0xc179db1.
pub const CANOPUS_FW_LVX_IMAGE_SET_SCALE_CALLABLE: usize = canopus_thumb_callable(0xc179db1usize);

/// Recovered `clock_gettime` at 0xc201fe0. Thumb callable address 0xc201fe1.
pub const CANOPUS_FW_CLOCK_GETTIME_CALLABLE: usize = canopus_thumb_callable(0xc201fe1usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_clock_gettime(a0: u32, a1: *const stock_timespec_t) -> i32 {
    let f: extern "C" fn(u32, *const stock_timespec_t) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_CLOCK_GETTIME_CALLABLE) };
    f(a0, a1)
}

/// Recovered `lvx_msgbox_set_content` at 0xc4ca130. Thumb callable address 0xc4ca131.
pub const CANOPUS_FW_LVX_MSGBOX_SET_CONTENT_CALLABLE: usize = canopus_thumb_callable(0xc4ca131usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_msgbox_set_content(a0: *mut core::ffi::c_void, a1: u32, a2: *const u8, a3: *const u8, a4: *const u8, a5: *const core::ffi::c_void, a6: u32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, u32, *const u8, *const u8, *const u8, *const core::ffi::c_void, u32) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LVX_MSGBOX_SET_CONTENT_CALLABLE) };
    f(a0, a1, a2, a3, a4, a5, a6);
}

/// Recovered `lv_bar_set_range` at 0xc5883d8. Thumb callable address 0xc5883d9.
pub const CANOPUS_FW_LV_BAR_SET_RANGE_CALLABLE: usize = canopus_thumb_callable(0xc5883d9usize);

/// Recovered global `core_bt_registration_handle` at 0x20126734.
pub const canopus_fw_core_bt_registration_handle: usize = 0x20126734usize;

/// Recovered `hidden_and_show_app_cb` at 0xc5141f0. Thumb callable address 0xc5141f1.
pub const CANOPUS_FW_HIDDEN_AND_SHOW_APP_CB_CALLABLE: usize = canopus_thumb_callable(0xc5141f1usize);

/// Recovered `lv_image_create` at 0xc179f00. Thumb callable address 0xc179f01.
pub const CANOPUS_FW_LV_IMAGE_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc179f01usize);

/// Recovered `lv_bar_set_value` at 0xc5890a8. Thumb callable address 0xc5890a9.
pub const CANOPUS_FW_LV_BAR_SET_VALUE_CALLABLE: usize = canopus_thumb_callable(0xc5890a9usize);

/// Recovered `bt_discovery_stop` at 0xc3af550. Thumb callable address 0xc3af551.
pub const CANOPUS_FW_BT_DISCOVERY_STOP_CALLABLE: usize = canopus_thumb_callable(0xc3af551usize);

/// Recovered `protobuf_set_ordered_app_list` at 0xc513528. Thumb callable address 0xc513529.
pub const CANOPUS_FW_PROTOBUF_SET_ORDERED_APP_LIST_CALLABLE: usize = canopus_thumb_callable(0xc513529usize);

/// Recovered `bt_timer_cancel` at 0xc7eb33c. Thumb callable address 0xc7eb33d.
pub const CANOPUS_FW_BT_TIMER_CANCEL_CALLABLE: usize = canopus_thumb_callable(0xc7eb33dusize);

/// Recovered `bt_remove_bond_private` at 0xc3b697c. Thumb callable address 0xc3b697d.
pub const CANOPUS_FW_BT_REMOVE_BOND_PRIVATE_CALLABLE: usize = canopus_thumb_callable(0xc3b697dusize);

/// Recovered `heap_mallinfo` at 0xc1f900c. Thumb callable address 0xc1f900d.
pub const CANOPUS_FW_HEAP_MALLINFO_CALLABLE: usize = canopus_thumb_callable(0xc1f900dusize);

/// Recovered `bt_adapter_get_instance` at 0xca40f68. Thumb callable address 0xca40f69.
pub const CANOPUS_FW_BT_ADAPTER_GET_INSTANCE_CALLABLE: usize = canopus_thumb_callable(0xca40f69usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_adapter_get_instance() -> *mut core::ffi::c_void {
    let f: extern "C" fn() -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_BT_ADAPTER_GET_INSTANCE_CALLABLE) };
    f()
}

/// Recovered `bt_l2cap_disconnect` at 0xc805b38. Thumb callable address 0xc805b39.
pub const CANOPUS_FW_BT_L2CAP_DISCONNECT_CALLABLE: usize = canopus_thumb_callable(0xc805b39usize);

/// Recovered `service_manager_shutdown` at 0xc3bdce8. Thumb callable address 0xc3bdce9.
pub const CANOPUS_FW_SERVICE_MANAGER_SHUTDOWN_CALLABLE: usize = canopus_thumb_callable(0xc3bdce9usize);

/// Recovered `lv_event_get_code` at 0xc588210. Thumb callable address 0xc588211.
pub const CANOPUS_FW_LV_EVENT_GET_CODE_CALLABLE: usize = canopus_thumb_callable(0xc588211usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lv_event_get_code(a0: *mut core::ffi::c_void) -> u32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> u32 = unsafe { core::mem::transmute(CANOPUS_FW_LV_EVENT_GET_CODE_CALLABLE) };
    f(a0)
}

/// Recovered `sem_post` at 0xc2070d0. Thumb callable address 0xc2070d1.
pub const CANOPUS_FW_SEM_POST_CALLABLE: usize = canopus_thumb_callable(0xc2070d1usize);

/// Recovered `heap_zalloc` at 0xc1f90bc. Thumb callable address 0xc1f90bd.
pub const CANOPUS_FW_HEAP_ZALLOC_CALLABLE: usize = canopus_thumb_callable(0xc1f90bdusize);

/// Recovered `lseek` at 0xc1d0524. Thumb callable address 0xc1d0525.
pub const CANOPUS_FW_LSEEK_CALLABLE: usize = canopus_thumb_callable(0xc1d0525usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lseek(a0: i32, a1: i64, a2: i32) -> i64 {
    let f: extern "C" fn(i32, i64, i32) -> i64 = unsafe { core::mem::transmute(CANOPUS_FW_LSEEK_CALLABLE) };
    f(a0, a1, a2)
}

/// Recovered `bt_adapter_unregister` at 0xc3af450. Thumb callable address 0xc3af451.
pub const CANOPUS_FW_BT_ADAPTER_UNREGISTER_CALLABLE: usize = canopus_thumb_callable(0xc3af451usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_adapter_unregister(a0: *mut core::ffi::c_void, a1: u32) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, u32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_BT_ADAPTER_UNREGISTER_CALLABLE) };
    f(a0, a1)
}

/// Recovered `app_install` at 0xca6a30c. Thumb callable address 0xca6a30d.
pub const CANOPUS_FW_APP_INSTALL_CALLABLE: usize = canopus_thumb_callable(0xca6a30dusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_app_install(a0: *const launcher_app_descriptor, a1: *const *const firmware_page_descriptor, a2: u32) -> i32 {
    let f: extern "C" fn(*const launcher_app_descriptor, *const *const firmware_page_descriptor, u32) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_APP_INSTALL_CALLABLE) };
    f(a0, a1, a2)
}

/// Recovered `bt_discovery_start` at 0xc3af524. Thumb callable address 0xc3af525.
pub const CANOPUS_FW_BT_DISCOVERY_START_CALLABLE: usize = canopus_thumb_callable(0xc3af525usize);

/// Recovered `sdp_unregister` at 0xc80a734. Thumb callable address 0xc80a735.
pub const CANOPUS_FW_SDP_UNREGISTER_CALLABLE: usize = canopus_thumb_callable(0xc80a735usize);

/// Recovered global `style_misans_demibold_32` at 0x2010D054.
pub const canopus_fw_style_misans_demibold_32: usize = 0x2010D054usize;

/// Recovered `service_manager_get_profile` at 0xc3bdd88. Thumb callable address 0xc3bdd89.
pub const CANOPUS_FW_SERVICE_MANAGER_GET_PROFILE_CALLABLE: usize = canopus_thumb_callable(0xc3bdd89usize);

/// Recovered `lvx_object_delete` at 0xc588de8. Thumb callable address 0xc588de9.
pub const CANOPUS_FW_LVX_OBJECT_DELETE_CALLABLE: usize = canopus_thumb_callable(0xc588de9usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_object_delete(a0: *mut core::ffi::c_void) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LVX_OBJECT_DELETE_CALLABLE) };
    f(a0);
}

/// Recovered `rmmod` at 0xc203a5c. Thumb callable address 0xc203a5d.
pub const CANOPUS_FW_RMMOD_CALLABLE: usize = canopus_thumb_callable(0xc203a5dusize);

/// Recovered `bt_l2cap_connect` at 0xc805b0c. Thumb callable address 0xc805b0d.
pub const CANOPUS_FW_BT_L2CAP_CONNECT_CALLABLE: usize = canopus_thumb_callable(0xc805b0dusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_l2cap_connect(a0: *const core::ffi::c_void) -> u32 {
    let f: extern "C" fn(*const core::ffi::c_void) -> u32 = unsafe { core::mem::transmute(CANOPUS_FW_BT_L2CAP_CONNECT_CALLABLE) };
    f(a0)
}

/// Recovered global `core_bt_adapter_instance` at 0x20126738.
pub const canopus_fw_core_bt_adapter_instance: usize = 0x20126738usize;

/// Recovered `firmware_log` at 0xc1f0d20. Thumb callable address 0xc1f0d21.
pub const CANOPUS_FW_FIRMWARE_LOG_CALLABLE: usize = canopus_thumb_callable(0xc1f0d21usize);

/// Recovered `unregister_driver` at 0xc1b002c. Thumb callable address 0xc1b002d.
pub const CANOPUS_FW_UNREGISTER_DRIVER_CALLABLE: usize = canopus_thumb_callable(0xc1b002dusize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_unregister_driver(a0: *const u8) -> i32 {
    let f: extern "C" fn(*const u8) -> i32 = unsafe { core::mem::transmute(CANOPUS_FW_UNREGISTER_DRIVER_CALLABLE) };
    f(a0)
}

/// Recovered `lv_obj_add_event_cb` at 0xc5883f0. Thumb callable address 0xc5883f1.
pub const CANOPUS_FW_LV_OBJ_ADD_EVENT_CB_CALLABLE: usize = canopus_thumb_callable(0xc5883f1usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lv_obj_add_event_cb(a0: *mut core::ffi::c_void, a1: canopus_lvx_event_cb, a2: u32, a3: *mut core::ffi::c_void) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, canopus_lvx_event_cb, u32, *mut core::ffi::c_void) -> () = unsafe { core::mem::transmute(CANOPUS_FW_LV_OBJ_ADD_EVENT_CB_CALLABLE) };
    f(a0, a1, a2, a3);
}

/// Recovered `lv_event_get_user_data` at 0xc588310. Thumb callable address 0xc588311.
pub const CANOPUS_FW_LV_EVENT_GET_USER_DATA_CALLABLE: usize = canopus_thumb_callable(0xc588311usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lv_event_get_user_data(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_LV_EVENT_GET_USER_DATA_CALLABLE) };
    f(a0)
}

/// Recovered `lv_obj_set_style_bg_opa` at 0xc108374. Thumb callable address 0xc108375.
pub const CANOPUS_FW_LV_OBJ_SET_STYLE_BG_OPA_CALLABLE: usize = canopus_thumb_callable(0xc108375usize);

/// Recovered `sdp_commit` at 0xc808648. Thumb callable address 0xc808649.
pub const CANOPUS_FW_SDP_COMMIT_CALLABLE: usize = canopus_thumb_callable(0xc808649usize);

/// Recovered `lvx_page_title_create` at 0xc4ca6c4. Thumb callable address 0xc4ca6c5.
pub const CANOPUS_FW_LVX_PAGE_TITLE_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc4ca6c5usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_page_title_create(a0: *mut core::ffi::c_void, a1: *const u8, a2: u32, a3: canopus_lvx_event_cb, a4: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, u32, canopus_lvx_event_cb, *mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_LVX_PAGE_TITLE_CREATE_CALLABLE) };
    f(a0, a1, a2, a3, a4)
}

/// Recovered `bt_queue_free` at 0xc6b9cf0. Thumb callable address 0xc6b9cf1.
pub const CANOPUS_FW_BT_QUEUE_FREE_CALLABLE: usize = canopus_thumb_callable(0xc6b9cf1usize);

/// Recovered `app_lookup` at 0xca69934. Thumb callable address 0xca69935.
pub const CANOPUS_FW_APP_LOOKUP_CALLABLE: usize = canopus_thumb_callable(0xca69935usize);
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_app_lookup(a0: u16) -> *mut core::ffi::c_void {
    let f: extern "C" fn(u16) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(CANOPUS_FW_APP_LOOKUP_CALLABLE) };
    f(a0)
}

/// Recovered `lv_image_set_src` at 0xc17a2f4. Thumb callable address 0xc17a2f5.
pub const CANOPUS_FW_LV_IMAGE_SET_SRC_CALLABLE: usize = canopus_thumb_callable(0xc17a2f5usize);

/// Recovered `rename` at 0xc1d12e8. Thumb callable address 0xc1d12e9.
pub const CANOPUS_FW_RENAME_CALLABLE: usize = canopus_thumb_callable(0xc1d12e9usize);

/// Recovered `ioctl` at 0xc1d01a4. Thumb callable address 0xc1d01a5.
pub const CANOPUS_FW_IOCTL_CALLABLE: usize = canopus_thumb_callable(0xc1d01a5usize);

/// Recovered `driver_close_dispatch` at 0xc1cec08. Thumb callable address 0xc1cec09.
pub const CANOPUS_FW_DRIVER_CLOSE_DISPATCH_CALLABLE: usize = canopus_thumb_callable(0xc1cec09usize);

/// Recovered `service_manager_startup` at 0xc3bdc24. Thumb callable address 0xc3bdc25.
pub const CANOPUS_FW_SERVICE_MANAGER_STARTUP_CALLABLE: usize = canopus_thumb_callable(0xc3bdc25usize);

// ---- excluded symbols ----
// app_launcher_data_init: restricted - not exported until context/ownership approved
// app_launcher_del: restricted - not exported until context/ownership approved
// bt_adapter_register_a2dp_callbacks: FORBIDDEN - no binding may ever be generated
// bt_adapter_register_hfp_ag_callbacks: FORBIDDEN - no binding may ever be generated
// bt_adapter_set_scan_mode: restricted - not exported until context/ownership approved
// bt_alloc: restricted - not exported until context/ownership approved
// bt_buffer_new: restricted - not exported until context/ownership approved
// bt_create_bond_private: restricted - not exported until context/ownership approved
// bt_discovery_start: restricted - not exported until context/ownership approved
// bt_discovery_stop: restricted - not exported until context/ownership approved
// bt_free: restricted - not exported until context/ownership approved
// bt_get_bond_state: restricted - not exported until context/ownership approved
// bt_l2cap_disconnect: restricted - not exported until context/ownership approved
// bt_l2cap_submit_cid: restricted - not exported until context/ownership approved
// bt_queue_external: restricted - not exported until context/ownership approved
// bt_queue_free: restricted - not exported until context/ownership approved
// bt_remove_bond_private: restricted - not exported until context/ownership approved
// bt_socket_server_receive: FORBIDDEN - no binding may ever be generated
// bt_timer_add: restricted - not exported until context/ownership approved
// bt_timer_cancel: restricted - not exported until context/ownership approved
// btsnoop_avdtp_recognizer: WITHDRAWN - no binding may ever be generated
// controller_crash_dump: FORBIDDEN - no binding may ever be generated
// driver_close_dispatch: restricted - not exported until context/ownership approved
// driver_ioctl_dispatch: restricted - not exported until context/ownership approved
// driver_open_dispatch: WITHDRAWN - no binding may ever be generated
// driver_read_dispatch: WITHDRAWN - no binding may ever be generated
// driver_write_dispatch: WITHDRAWN - no binding may ever be generated
// errno_location: restricted - not exported until context/ownership approved
// firmware_log: restricted - not exported until context/ownership approved
// gap_host_stock_receive: restricted - not exported until context/ownership approved
// heap_free: restricted - not exported until context/ownership approved
// heap_mallinfo: restricted - not exported until context/ownership approved
// heap_malloc: restricted - not exported until context/ownership approved
// heap_zalloc: restricted - not exported until context/ownership approved
// hfp_ag_connect: FORBIDDEN - no binding may ever be generated
// hfp_ag_disconnect: FORBIDDEN - no binding may ever be generated
// hidden_and_show_app_cb: restricted - not exported until context/ownership approved
// insmod: restricted - not exported until context/ownership approved
// ioctl: restricted - not exported until context/ownership approved
// lv_bar_create: restricted - not exported until context/ownership approved
// lv_bar_set_range: restricted - not exported until context/ownership approved
// lv_bar_set_value: restricted - not exported until context/ownership approved
// lv_image_create: restricted - not exported until context/ownership approved
// lv_image_set_src: restricted - not exported until context/ownership approved
// lv_obj_move_to_index: restricted - not exported until context/ownership approved
// lv_obj_set_local_style_prop: restricted - not exported until context/ownership approved
// lv_obj_set_style_bg_opa: restricted - not exported until context/ownership approved
// lv_timer_del: restricted - not exported until context/ownership approved
// lvx_image_set_scale: restricted - not exported until context/ownership approved
// lvx_label_set_long_mode: restricted - not exported until context/ownership approved
// lvx_object_add_flag: restricted - not exported until context/ownership approved
// modhandle: restricted - not exported until context/ownership approved
// offload_property_apply: FORBIDDEN - no binding may ever be generated
// page_navigator_open_page: FORBIDDEN - no binding may ever be generated
// protobuf_set_ordered_app_list: restricted - not exported until context/ownership approved
// pthread_create_internal: FORBIDDEN - no binding may ever be generated
// public_work_queue: FORBIDDEN - no binding may ever be generated
// register_blockdriver: restricted - not exported until context/ownership approved
// rename: restricted - not exported until context/ownership approved
// rmmod: restricted - not exported until context/ownership approved
// sdp_builder_create: restricted - not exported until context/ownership approved
// sdp_commit: restricted - not exported until context/ownership approved
// sdp_set_raw_attribute: restricted - not exported until context/ownership approved
// sdp_unregister: restricted - not exported until context/ownership approved
// sem_post: restricted - not exported until context/ownership approved
// sem_trywait: restricted - not exported until context/ownership approved
// sem_wait: restricted - not exported until context/ownership approved
// service_manager_cleanup: FORBIDDEN - no binding may ever be generated
// service_manager_get_profile: restricted - not exported until context/ownership approved
// service_manager_register: restricted - not exported until context/ownership approved
// service_manager_shutdown: restricted - not exported until context/ownership approved
// service_manager_startup: restricted - not exported until context/ownership approved
// sport_titlebar_dispatch: FORBIDDEN - no binding may ever be generated
// sport_titlebar_lifecycle_reset: FORBIDDEN - no binding may ever be generated
// system_router_app_wrapper: FORBIDDEN - no binding may ever be generated
// system_router_get_pages_wrapper: FORBIDDEN - no binding may ever be generated
// system_router_page_record_wrapper: FORBIDDEN - no binding may ever be generated
// unlink: restricted - not exported until context/ownership approved
// unregister_blockdriver: restricted - not exported until context/ownership approved
// vendor_hci_transport_register: FORBIDDEN - no binding may ever be generated
// watchface_manager_delete_watchface: restricted - not exported until context/ownership approved
// watchface_reset_watchface: restricted - not exported until context/ownership approved

