// Generated by `canopus target generate-rust-bindings`. DO NOT EDIT.
//
// target_id: xiaomi-band-11-4.100.155
// firmware : 4.100.155 (user-4.100.155-cn-202609041500)
// sha256   : ea0bdf1920cb30223d616432af00565ca67622e6468328f5eab155f8cdc2fb9f
// revision : 1
// input_digest: dcdfb81a1b366a34
//
// All firmware calls are `unsafe`; safe wrappers exist only
// where the ABI and ownership have been proven (architecture §12.1).

/// Converts a recovered Thumb entry or callable address into the only valid
/// indirect-call address. Target-private ABI adapters must use this instead
/// of transmuting raw firmware addresses directly.
#[inline(always)]
pub const fn canopus_thumb_callable(entry_or_callable: usize) -> usize {
    entry_or_callable | 1usize
}

// ---- recovered type layouts ----
// `#[repr(C, packed(N))]` + explicit padding reproduces the exact
// recovered byte layout and its target-declared alignment.
pub type canopus_interconnect_recv_cb = extern "C" fn(*mut core::ffi::c_void, i32, *const canopus_interconnect_message, *const u8) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct file_operations {
    pub open: *mut core::ffi::c_void, // +0x0
    pub close: *mut core::ffi::c_void, // +0x4
    pub read: *mut core::ffi::c_void, // +0x8
    pub write: *mut core::ffi::c_void, // +0xc
    pub lseek: *mut core::ffi::c_void, // +0x10
    pub ioctl: *mut core::ffi::c_void, // +0x14
    pub _tail: [u8; 0x18], // 24
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_order_record {
    pub app_name: [u8; 128], // +0x0
    pub _pad_80: [u8; 0x4], // 4
    pub flags: u32, // +0x84
    pub _tail: [u8; 0x4], // 4
}

pub type canopus_lvx_event_cb = extern "C" fn(*mut core::ffi::c_void) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct stock_timespec_t {
    pub tv_sec: i64, // +0x0
    pub tv_nsec: i32, // +0x8
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_thirdparty_message_content {
    pub message_id: u32, // +0x0
    pub message_kind: u16, // +0x4
    pub _pad_6: [u8; 0xa], // 10
    pub package_name: *mut core::ffi::c_void, // +0x10
    pub fingerprint_blob: *mut core::ffi::c_void, // +0x14
    pub payload_blob: *mut core::ffi::c_void, // +0x18
    pub _tail: [u8; 0x134], // 308
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct firmware_page_descriptor {
    pub parent_descriptor: *mut core::ffi::c_void, // +0x0
    pub _pad_4: [u8; 0xc], // 12
    pub page_name: *mut core::ffi::c_void, // +0x10
    pub page_id: u16, // +0x14
    pub app_id: u16, // +0x16
    pub flags: u16, // +0x18
    pub _pad_1a: [u8; 0x2], // 2
    pub scheduler_deadline: i32, // +0x1c
    pub scheduler_priority: i32, // +0x20
    pub async_destroy_state: u32, // +0x24
    pub lifecycle_state: u8, // +0x28
    pub layer: u8, // +0x29
    pub page_kind: u8, // +0x2a
    pub _pad_2b: [u8; 0x1], // 1
    pub activity_context: *mut core::ffi::c_void, // +0x2c
    pub root_object: *mut core::ffi::c_void, // +0x30
    pub on_signal: *mut core::ffi::c_void, // +0x34
    pub runtime_default_56: *mut core::ffi::c_void, // +0x38
    pub _pad_3c: [u8; 0x4], // 4
    pub registry_prev: *mut core::ffi::c_void, // +0x40
    pub registry_next: *mut core::ffi::c_void, // +0x44
    pub runtime_parent: *mut core::ffi::c_void, // +0x48
    pub on_create: *mut core::ffi::c_void, // +0x4c
    pub on_resume: *mut core::ffi::c_void, // +0x50
    pub on_foreground_data: *mut core::ffi::c_void, // +0x54
    pub extension_callback_88: *mut core::ffi::c_void, // +0x58
    pub on_pause: *mut core::ffi::c_void, // +0x5c
    pub on_stop: *mut core::ffi::c_void, // +0x60
    pub on_ui_destroy: *mut core::ffi::c_void, // +0x64
    pub extension_callback_104: *mut core::ffi::c_void, // +0x68
    pub extension_callback_108: *mut core::ffi::c_void, // +0x6c
    pub _tail: [u8; 0x8], // 8
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_interconnect_app_info {
    pub package_name: *mut core::ffi::c_void, // +0x0
    pub display_name: *mut core::ffi::c_void, // +0x4
    pub icon_file: *mut core::ffi::c_void, // +0x8
    pub extra: *mut core::ffi::c_void, // +0xc
    pub fingerprint: [u8; 20], // +0x10
}

#[repr(C, packed(8))]
#[derive(Copy, Clone, Debug)]
pub struct firmware_notification_message {
    pub message_id: u64, // +0x0
    pub repeat_count: u32, // +0x8
    pub title: *mut core::ffi::c_void, // +0xc
    pub source: *mut core::ffi::c_void, // +0x10
    pub body: *mut core::ffi::c_void, // +0x14
    pub auxiliary_text: *mut core::ffi::c_void, // +0x18
    pub small_icon_path: *mut core::ffi::c_void, // +0x1c
    pub large_icon_path: *mut core::ffi::c_void, // +0x20
    pub extension_text_36: *mut core::ffi::c_void, // +0x24
    pub extension_text_40: *mut core::ffi::c_void, // +0x28
    pub _pad_2c: [u8; 0x4], // 4
    pub timestamp: u64, // +0x30
    pub _pad_38: [u8; 0x4], // 4
    pub flags_60: [u8; 3], // +0x3c
    pub _pad_3f: [u8; 0x1], // 1
    pub action_callback: *mut core::ffi::c_void, // +0x40
    pub action_context: u32, // +0x44
    pub extension_72: u32, // +0x48
    pub extension_76: u32, // +0x4c
    pub open_callback: *mut core::ffi::c_void, // +0x50
    pub destroy_callback: *mut core::ffi::c_void, // +0x54
    pub start_reminder: u8, // +0x58
    pub flags_89: u8, // +0x59
    pub flags_90: u8, // +0x5a
    pub _pad_5b: [u8; 0x1], // 1
    pub callback_data: *mut core::ffi::c_void, // +0x5c
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct service_object {
    pub enabled_state: u8, // +0x0
    pub _pad_1: [u8; 0x3], // 3
    pub name: *mut core::ffi::c_void, // +0x4
    pub service_id: u8, // +0x8
    pub profile_group: u8, // +0x9
    pub _pad_a: [u8; 0x1a], // 26
    pub startup_cb: *mut core::ffi::c_void, // +0x24
    pub _pad_28: [u8; 0x8], // 8
    pub startup_eligibility_cb: *mut core::ffi::c_void, // +0x30
    pub get_profile_cb: *mut core::ffi::c_void, // +0x34
    pub cleanup_cb: *mut core::ffi::c_void, // +0x38
    pub _tail: [u8; 0x4], // 4
}

pub type canopus_interconnect_send_done = extern "C" fn(*mut core::ffi::c_void, i32, *const canopus_interconnect_message, *mut core::ffi::c_void) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_interconnect_message {
    pub r#type: u8, // +0x0
    pub _pad_1: [u8; 0x3], // 3
    pub length: u32, // +0x4
    pub _pad_8: [u8; 0x8], // 8
    pub value: *mut core::ffi::c_void, // +0x10
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct ordered_app_entry {
    pub app_name: *mut core::ffi::c_void, // +0x0
    pub _pad_4: [u8; 0x4], // 4
    pub enabled: u8, // +0x8
    pub hidden: u8, // +0x9
    pub _tail: [u8; 0x6], // 6
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_struct {
    pub name: [u8; 128], // +0x0
    pub flags: u8, // +0x80
    pub _tail: [u8; 0x3], // 3
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_record {
    pub app_id: u16, // +0x0
    pub _pad_2: [u8; 0x2], // 2
    pub display_name: *mut core::ffi::c_void, // +0x4
    pub package_name: *mut core::ffi::c_void, // +0x8
    pub icon_name: *mut core::ffi::c_void, // +0xc
    pub _pad_10: [u8; 0x8], // 8
    pub flags: u8, // +0x18
    pub _tail: [u8; 0x3], // 3
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_descriptor {
    pub registry_links: u64, // +0x0
    pub vtable: *mut core::ffi::c_void, // +0x8
    pub package_name: *mut core::ffi::c_void, // +0xc
    pub launcher_icon_resource: *mut core::ffi::c_void, // +0x10
    pub app_id: u16, // +0x14
    pub flags: u8, // +0x16
    pub _pad_17: [u8; 0x5], // 5
    pub owned_string_28: *mut core::ffi::c_void, // +0x1c
    pub owned_string_32: *mut core::ffi::c_void, // +0x20
    pub launcher_metadata_callback: *mut core::ffi::c_void, // +0x24
    pub _pad_28: [u8; 0x10], // 16
    pub page_registry: *mut core::ffi::c_void, // +0x38
    pub _pad_3c: [u8; 0xc], // 12
    pub hidden_flags: u8, // +0x48
    pub _tail: [u8; 0x7], // 7
}

// ---- runtime identity guard ----
/// Returns 0 when the running firmware matches this pack's
/// version + build identity, -1 otherwise. Call once before use.
pub fn canopus_identity_guard() -> i32 {
    const EXPECT_VERSION: &[u8] = b"4.100.155";
    const EXPECT_BUILD: &[u8] = b"user-4.100.155-cn-202609041500";
    if !identity_token_eq(0xca0a8a6, EXPECT_VERSION) { return -1; }
    if !identity_token_eq(0xca0a91e, EXPECT_BUILD) { return -1; }
    0
}

/// Compares an LF-, CR-, or NUL-terminated identity token.
fn identity_token_eq(addr: usize, expected: &[u8]) -> bool {
    let mut i = 0usize;
    while i <= expected.len() && i < 64 {
        let b = unsafe { *((addr + i) as *const u8) };
        if i < expected.len() {
            if b != expected[i] { return false; }
        } else {
            return b == 0 || b == b'\n' || b == b'\r';
        }
        i += 1;
    }
    false
}

// ---- typed firmware bindings (unsafe) ----
/// Recovered `sdp_unregister` at 0xc86f3d0. Thumb callable address 0xc86f3d1.
pub const CANOPUS_FW_SDP_UNREGISTER_CALLABLE: usize = canopus_thumb_callable(0xc86f3d1usize);

/// Recovered `lv_image_set_src` at 0xc3b2c28. Thumb callable address 0xc3b2c29.
pub const CANOPUS_FW_LV_IMAGE_SET_SRC_CALLABLE: usize = canopus_thumb_callable(0xc3b2c29usize);

/// Recovered `system_router_app_wrapper` at 0xc45be22. Thumb callable address 0xc45be23.
pub const CANOPUS_FW_SYSTEM_ROUTER_APP_WRAPPER_CALLABLE: usize = canopus_thumb_callable(0xc45be23usize);

/// Recovered `bt_pair_request_reply` at 0xc46a9c4. Thumb callable address 0xc46a9c5.
pub const CANOPUS_FW_BT_PAIR_REQUEST_REPLY_CALLABLE: usize = canopus_thumb_callable(0xc46a9c5usize);

/// Recovered `open` at 0xc342c54. Thumb callable address 0xc342c55.
pub const CANOPUS_FW_OPEN_CALLABLE: usize = canopus_thumb_callable(0xc342c55usize);

/// Recovered `sdp_commit` at 0xc86f2bc. Thumb callable address 0xc86f2bd.
pub const CANOPUS_FW_SDP_COMMIT_CALLABLE: usize = canopus_thumb_callable(0xc86f2bdusize);

/// Recovered `heap_malloc` at 0xc3513e8. Thumb callable address 0xc3513e9.
pub const CANOPUS_FW_HEAP_MALLOC_CALLABLE: usize = canopus_thumb_callable(0xc3513e9usize);

/// Recovered `lv_cache_drop` at 0xc8b8c9e. Thumb callable address 0xc8b8c9f.
pub const CANOPUS_FW_LV_CACHE_DROP_CALLABLE: usize = canopus_thumb_callable(0xc8b8c9fusize);

/// Recovered `lvx_list_item_add_content` at 0xc50fad0. Thumb callable address 0xc50fad1.
pub const CANOPUS_FW_LVX_LIST_ITEM_ADD_CONTENT_CALLABLE: usize = canopus_thumb_callable(0xc50fad1usize);

/// Recovered `lvx_label_create` at 0xc3ab300. Thumb callable address 0xc3ab301.
pub const CANOPUS_FW_LVX_LABEL_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc3ab301usize);

/// Recovered `lv_bar_create` at 0xc3ad7f4. Thumb callable address 0xc3ad7f5.
pub const CANOPUS_FW_LV_BAR_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc3ad7f5usize);

/// Recovered `lv_obj_move_to_index` at 0xc3846ac. Thumb callable address 0xc3846ad.
pub const CANOPUS_FW_LV_OBJ_MOVE_TO_INDEX_CALLABLE: usize = canopus_thumb_callable(0xc3846adusize);

/// Recovered `page_goto` at 0xc8ed770. Thumb callable address 0xc8ed771.
pub const CANOPUS_FW_PAGE_GOTO_CALLABLE: usize = canopus_thumb_callable(0xc8ed771usize);

/// Recovered `clock_gettime` at 0xc34d58c. Thumb callable address 0xc34d58d.
pub const CANOPUS_FW_CLOCK_GETTIME_CALLABLE: usize = canopus_thumb_callable(0xc34d58dusize);

/// Recovered `app_launcher_add` at 0xc547b54. Thumb callable address 0xc547b55.
pub const CANOPUS_FW_APP_LAUNCHER_ADD_CALLABLE: usize = canopus_thumb_callable(0xc547b55usize);

/// Recovered global `kmem_heap_slot` at 0x200b01c8.
pub const canopus_fw_kmem_heap_slot: usize = 0x200b01c8usize;

/// Recovered `heap_free` at 0xc34cd2c. Thumb callable address 0xc34cd2d.
pub const CANOPUS_FW_HEAP_FREE_CALLABLE: usize = canopus_thumb_callable(0xc34cd2dusize);

/// Recovered `lvx_list_item_update` at 0xc50ec5c. Thumb callable address 0xc50ec5d.
pub const CANOPUS_FW_LVX_LIST_ITEM_UPDATE_CALLABLE: usize = canopus_thumb_callable(0xc50ec5dusize);

/// Recovered `controller_crash_dump` at 0xc92c378. Thumb callable address 0xc92c379.
pub const CANOPUS_FW_CONTROLLER_CRASH_DUMP_CALLABLE: usize = canopus_thumb_callable(0xc92c379usize);

/// Recovered `lv_bar_set_value` at 0xc3ad8b4. Thumb callable address 0xc3ad8b5.
pub const CANOPUS_FW_LV_BAR_SET_VALUE_CALLABLE: usize = canopus_thumb_callable(0xc3ad8b5usize);

/// Recovered `kmem_free` at 0xc34ccb8. Thumb callable address 0xc34ccb9.
pub const CANOPUS_FW_KMEM_FREE_CALLABLE: usize = canopus_thumb_callable(0xc34ccb9usize);

/// Recovered `lvgl_posix_open` at 0xc3a6194. Thumb callable address 0xc3a6195.
pub const CANOPUS_FW_LVGL_POSIX_OPEN_CALLABLE: usize = canopus_thumb_callable(0xc3a6195usize);

/// Recovered `sem_wait` at 0xc358ce0. Thumb callable address 0xc358ce1.
pub const CANOPUS_FW_SEM_WAIT_CALLABLE: usize = canopus_thumb_callable(0xc358ce1usize);

/// Recovered global `umem_heap_slot` at 0x200b2590.
pub const canopus_fw_umem_heap_slot: usize = 0x200b2590usize;

/// Recovered `unlink` at 0xc33dbec. Thumb callable address 0xc33dbed.
pub const CANOPUS_FW_UNLINK_CALLABLE: usize = canopus_thumb_callable(0xc33dbedusize);

/// Recovered `lvx_object_create` at 0xc380686. Thumb callable address 0xc380687.
pub const CANOPUS_FW_LVX_OBJECT_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc380687usize);

/// Recovered `lv_obj_remove_style_all` at 0xc38583c. Thumb callable address 0xc38583d.
pub const CANOPUS_FW_LV_OBJ_REMOVE_STYLE_ALL_CALLABLE: usize = canopus_thumb_callable(0xc38583dusize);

/// Recovered `ioctl` at 0xc341e38. Thumb callable address 0xc341e39.
pub const CANOPUS_FW_IOCTL_CALLABLE: usize = canopus_thumb_callable(0xc341e39usize);

/// Recovered `bt_adapter_register` at 0xc46a38e. Thumb callable address 0xc46a38f.
pub const CANOPUS_FW_BT_ADAPTER_REGISTER_CALLABLE: usize = canopus_thumb_callable(0xc46a38fusize);

/// Recovered `lv_bar_set_range` at 0xc3ad920. Thumb callable address 0xc3ad921.
pub const CANOPUS_FW_LV_BAR_SET_RANGE_CALLABLE: usize = canopus_thumb_callable(0xc3ad921usize);

/// Recovered `lvx_object_align` at 0xc387788. Thumb callable address 0xc387789.
pub const CANOPUS_FW_LVX_OBJECT_ALIGN_CALLABLE: usize = canopus_thumb_callable(0xc387789usize);

/// Recovered `bt_queue_external` at 0xc863bb4. Thumb callable address 0xc863bb5.
pub const CANOPUS_FW_BT_QUEUE_EXTERNAL_CALLABLE: usize = canopus_thumb_callable(0xc863bb5usize);

/// Recovered `mm_memalign` at 0xc3507e8. Thumb callable address 0xc3507e9.
pub const CANOPUS_FW_MM_MEMALIGN_CALLABLE: usize = canopus_thumb_callable(0xc3507e9usize);

/// Recovered `lvx_image_set_scale` at 0xc3ae46e. Thumb callable address 0xc3ae46f.
pub const CANOPUS_FW_LVX_IMAGE_SET_SCALE_CALLABLE: usize = canopus_thumb_callable(0xc3ae46fusize);

/// Recovered `bt_adapter_get_state` at 0xc46a44c. Thumb callable address 0xc46a44d.
pub const CANOPUS_FW_BT_ADAPTER_GET_STATE_CALLABLE: usize = canopus_thumb_callable(0xc46a44dusize);

/// Recovered `bt_timer_cancel` at 0xc863000. Thumb callable address 0xc863001.
pub const CANOPUS_FW_BT_TIMER_CANCEL_CALLABLE: usize = canopus_thumb_callable(0xc863001usize);

/// Recovered `bt_l2cap_disconnect` at 0xc86f094. Thumb callable address 0xc86f095.
pub const CANOPUS_FW_BT_L2CAP_DISCONNECT_CALLABLE: usize = canopus_thumb_callable(0xc86f095usize);

/// Recovered `_lv_inv_area` at 0xc382428. Thumb callable address 0xc382429.
pub const CANOPUS_FW__LV_INV_AREA_CALLABLE: usize = canopus_thumb_callable(0xc382429usize);

/// Recovered `lseek` at 0xc33d510. Thumb callable address 0xc33d511.
pub const CANOPUS_FW_LSEEK_CALLABLE: usize = canopus_thumb_callable(0xc33d511usize);

/// Recovered `lvx_page_title_create` at 0xc89e7cc. Thumb callable address 0xc89e7cd.
pub const CANOPUS_FW_LVX_PAGE_TITLE_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc89e7cdusize);

/// Recovered `bt_socket_client_sendrecv` at 0xc46a218. Thumb callable address 0xc46a219.
pub const CANOPUS_FW_BT_SOCKET_CLIENT_SENDRECV_CALLABLE: usize = canopus_thumb_callable(0xc46a219usize);

/// Recovered `bt_timer_cancel_owned` at 0xc863048. Thumb callable address 0xc863049.
pub const CANOPUS_FW_BT_TIMER_CANCEL_OWNED_CALLABLE: usize = canopus_thumb_callable(0xc863049usize);

/// Recovered `lvx_label_set_long_mode` at 0xc3b3f5c. Thumb callable address 0xc3b3f5d.
pub const CANOPUS_FW_LVX_LABEL_SET_LONG_MODE_CALLABLE: usize = canopus_thumb_callable(0xc3b3f5dusize);

/// Recovered `lv_image_create` at 0xc3ae1d0. Thumb callable address 0xc3ae1d1.
pub const CANOPUS_FW_LV_IMAGE_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc3ae1d1usize);

/// Recovered `cache_d_clean_all` at 0xc93020a. Thumb callable address 0xc93020b.
pub const CANOPUS_FW_CACHE_D_CLEAN_ALL_CALLABLE: usize = canopus_thumb_callable(0xc93020busize);

/// Recovered global `gap_host_receive_slot` at 0x200bda80.
pub const canopus_fw_gap_host_receive_slot: usize = 0x200bda80usize;

/// Recovered `app_install` at 0xc6ab340. Thumb callable address 0xc6ab341.
pub const CANOPUS_FW_APP_INSTALL_CALLABLE: usize = canopus_thumb_callable(0xc6ab341usize);

/// Recovered `errno_location` at 0xc349538. Thumb callable address 0xc349539.
pub const CANOPUS_FW_ERRNO_LOCATION_CALLABLE: usize = canopus_thumb_callable(0xc349539usize);

/// Recovered `lvx_list_item_create` at 0xc50f4e4. Thumb callable address 0xc50f4e5.
pub const CANOPUS_FW_LVX_LIST_ITEM_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc50f4e5usize);

/// Recovered `cache_i_clean_invalidate_all` at 0xc0c181e. Thumb callable address 0xc0c181f.
pub const CANOPUS_FW_CACHE_I_CLEAN_INVALIDATE_ALL_CALLABLE: usize = canopus_thumb_callable(0xc0c181fusize);

/// Recovered `bt_buffer_new` at 0xc862ec2. Thumb callable address 0xc862ec3.
pub const CANOPUS_FW_BT_BUFFER_NEW_CALLABLE: usize = canopus_thumb_callable(0xc862ec3usize);

/// Recovered `lv_image_cache_drop` at 0xc3a3888. Thumb callable address 0xc3a3889.
pub const CANOPUS_FW_LV_IMAGE_CACHE_DROP_CALLABLE: usize = canopus_thumb_callable(0xc3a3889usize);

/// Recovered `lvx_object_add_flag` at 0xc38404c. Thumb callable address 0xc38404d.
pub const CANOPUS_FW_LVX_OBJECT_ADD_FLAG_CALLABLE: usize = canopus_thumb_callable(0xc38404dusize);

/// Recovered `lvx_object_set_size` at 0xc387ba8. Thumb callable address 0xc387ba9.
pub const CANOPUS_FW_LVX_OBJECT_SET_SIZE_CALLABLE: usize = canopus_thumb_callable(0xc387ba9usize);

/// Recovered `lv_obj_align_to` at 0xc3877b0. Thumb callable address 0xc3877b1.
pub const CANOPUS_FW_LV_OBJ_ALIGN_TO_CALLABLE: usize = canopus_thumb_callable(0xc3877b1usize);

/// Recovered `lv_timer_del` at 0xc3abe70. Thumb callable address 0xc3abe71.
pub const CANOPUS_FW_LV_TIMER_DEL_CALLABLE: usize = canopus_thumb_callable(0xc3abe71usize);

/// Recovered `bt_pair_display_reply` at 0xc46a9fe. Thumb callable address 0xc46a9ff.
pub const CANOPUS_FW_BT_PAIR_DISPLAY_REPLY_CALLABLE: usize = canopus_thumb_callable(0xc46a9ffusize);

/// Recovered `hidden_and_show_app_cb` at 0xc547988. Thumb callable address 0xc547989.
pub const CANOPUS_FW_HIDDEN_AND_SHOW_APP_CB_CALLABLE: usize = canopus_thumb_callable(0xc547989usize);

/// Recovered `lv_obj_clear_flag` at 0xc3840d8. Thumb callable address 0xc3840d9.
pub const CANOPUS_FW_LV_OBJ_CLEAR_FLAG_CALLABLE: usize = canopus_thumb_callable(0xc3840d9usize);

/// Recovered global `bt_shared_adapter` at 0x200c3148.
pub const canopus_fw_bt_shared_adapter: usize = 0x200c3148usize;

/// Recovered `rename` at 0xc33d79c. Thumb callable address 0xc33d79d.
pub const CANOPUS_FW_RENAME_CALLABLE: usize = canopus_thumb_callable(0xc33d79dusize);

/// Recovered `bt_get_bond_state` at 0xc46a884. Thumb callable address 0xc46a885.
pub const CANOPUS_FW_BT_GET_BOND_STATE_CALLABLE: usize = canopus_thumb_callable(0xc46a885usize);

/// Recovered `mm_mallinfo` at 0xc34f0a0. Thumb callable address 0xc34f0a1.
pub const CANOPUS_FW_MM_MALLINFO_CALLABLE: usize = canopus_thumb_callable(0xc34f0a1usize);

/// Recovered `bt_l2cap_connect` at 0xc86f010. Thumb callable address 0xc86f011.
pub const CANOPUS_FW_BT_L2CAP_CONNECT_CALLABLE: usize = canopus_thumb_callable(0xc86f011usize);

/// Recovered `lvx_notification_insert_message` at 0xc8f2ba0. Thumb callable address 0xc8f2ba1.
pub const CANOPUS_FW_LVX_NOTIFICATION_INSERT_MESSAGE_CALLABLE: usize = canopus_thumb_callable(0xc8f2ba1usize);

/// Recovered `lv_obj_set_width` at 0xc387b2e. Thumb callable address 0xc387b2f.
pub const CANOPUS_FW_LV_OBJ_SET_WIDTH_CALLABLE: usize = canopus_thumb_callable(0xc387b2fusize);

/// Recovered `bt_l2cap_submit_cid` at 0xc86f0bc. Thumb callable address 0xc86f0bd.
pub const CANOPUS_FW_BT_L2CAP_SUBMIT_CID_CALLABLE: usize = canopus_thumb_callable(0xc86f0bdusize);

/// Recovered `lvx_content_pad_bottom` at 0xc387c6e. Thumb callable address 0xc387c6f.
pub const CANOPUS_FW_LVX_CONTENT_PAD_BOTTOM_CALLABLE: usize = canopus_thumb_callable(0xc387c6fusize);

/// Recovered `write` at 0xc33dc4e. Thumb callable address 0xc33dc4f.
pub const CANOPUS_FW_WRITE_CALLABLE: usize = canopus_thumb_callable(0xc33dc4fusize);

/// Recovered `read` at 0xc33d784. Thumb callable address 0xc33d785.
pub const CANOPUS_FW_READ_CALLABLE: usize = canopus_thumb_callable(0xc33d785usize);

/// Recovered `bt_alloc` at 0xc351724. Thumb callable address 0xc351725.
pub const CANOPUS_FW_BT_ALLOC_CALLABLE: usize = canopus_thumb_callable(0xc351725usize);

/// Recovered `sem_post` at 0xc359150. Thumb callable address 0xc359151.
pub const CANOPUS_FW_SEM_POST_CALLABLE: usize = canopus_thumb_callable(0xc359151usize);

/// Recovered `app_lookup` at 0xc6ac53c. Thumb callable address 0xc6ac53d.
pub const CANOPUS_FW_APP_LOOKUP_CALLABLE: usize = canopus_thumb_callable(0xc6ac53dusize);

/// Recovered global `style_misans_medium_24` at 0x200c1568.
pub const canopus_fw_style_misans_medium_24: usize = 0x200c1568usize;

/// Recovered `bt_discovery_start` at 0xc46a472. Thumb callable address 0xc46a473.
pub const CANOPUS_FW_BT_DISCOVERY_START_CALLABLE: usize = canopus_thumb_callable(0xc46a473usize);

/// Recovered `close` at 0xc33818c. Thumb callable address 0xc33818d.
pub const CANOPUS_FW_CLOSE_CALLABLE: usize = canopus_thumb_callable(0xc33818dusize);

/// Recovered `cache_barrier` at 0xc91e532. Thumb callable address 0xc91e533.
pub const CANOPUS_FW_CACHE_BARRIER_CALLABLE: usize = canopus_thumb_callable(0xc91e533usize);

/// Recovered global `umem_heap_descriptor` at 0x3c356b40.
pub const canopus_fw_umem_heap_descriptor: usize = 0x3c356b40usize;

/// Recovered `protobuf_set_ordered_app_list` at 0xc54cb6c. Thumb callable address 0xc54cb6d.
pub const CANOPUS_FW_PROTOBUF_SET_ORDERED_APP_LIST_CALLABLE: usize = canopus_thumb_callable(0xc54cb6dusize);

/// Recovered `lv_obj_set_style_pad_top` at 0xc387c58. Thumb callable address 0xc387c59.
pub const CANOPUS_FW_LV_OBJ_SET_STYLE_PAD_TOP_CALLABLE: usize = canopus_thumb_callable(0xc387c59usize);

/// Recovered `service_manager_startup` at 0xc90d89c. Thumb callable address 0xc90d89d.
pub const CANOPUS_FW_SERVICE_MANAGER_STARTUP_CALLABLE: usize = canopus_thumb_callable(0xc90d89dusize);

/// Recovered `register_driver` at 0xc914f54. Thumb callable address 0xc914f55.
pub const CANOPUS_FW_REGISTER_DRIVER_CALLABLE: usize = canopus_thumb_callable(0xc914f55usize);

/// Recovered global `style_misans_medium_28` at 0x200c1574.
pub const canopus_fw_style_misans_medium_28: usize = 0x200c1574usize;

/// Recovered `lv_obj_set_style_pad_bottom` at 0xc387c6e. Thumb callable address 0xc387c6f.
pub const CANOPUS_FW_LV_OBJ_SET_STYLE_PAD_BOTTOM_CALLABLE: usize = canopus_thumb_callable(0xc387c6fusize);

/// Recovered `lv_obj_add_event_cb` at 0xc37fc1c. Thumb callable address 0xc37fc1d.
pub const CANOPUS_FW_LV_OBJ_ADD_EVENT_CB_CALLABLE: usize = canopus_thumb_callable(0xc37fc1dusize);

/// Recovered `lvx_label_set_text` at 0xc3b3948. Thumb callable address 0xc3b3949.
pub const CANOPUS_FW_LVX_LABEL_SET_TEXT_CALLABLE: usize = canopus_thumb_callable(0xc3b3949usize);

/// Recovered global `mpu_region_bitmap` at 0x200f5190.
pub const canopus_fw_mpu_region_bitmap: usize = 0x200f5190usize;

/// Recovered global `bt_l2cap_owner` at 0x200be890.
pub const canopus_fw_bt_l2cap_owner: usize = 0x200be890usize;

/// Recovered `bt_discovery_stop` at 0xc46a49a. Thumb callable address 0xc46a49b.
pub const CANOPUS_FW_BT_DISCOVERY_STOP_CALLABLE: usize = canopus_thumb_callable(0xc46a49busize);

/// Recovered `offload_property_apply` at 0xc468674. Thumb callable address 0xc468675.
pub const CANOPUS_FW_OFFLOAD_PROPERTY_APPLY_CALLABLE: usize = canopus_thumb_callable(0xc468675usize);

/// Recovered `lv_timer_create` at 0xc3abd20. Thumb callable address 0xc3abd21.
pub const CANOPUS_FW_LV_TIMER_CREATE_CALLABLE: usize = canopus_thumb_callable(0xc3abd21usize);

/// Recovered `lv_obj_set_local_style_prop` at 0xc3872b4. Thumb callable address 0xc3872b5.
pub const CANOPUS_FW_LV_OBJ_SET_LOCAL_STYLE_PROP_CALLABLE: usize = canopus_thumb_callable(0xc3872b5usize);

/// Recovered `gap_host_stock_receive` at 0xc863c88. Thumb callable address 0xc863c89.
pub const CANOPUS_FW_GAP_HOST_STOCK_RECEIVE_CALLABLE: usize = canopus_thumb_callable(0xc863c89usize);

/// Recovered `bt_free` at 0xc34cd2c. Thumb callable address 0xc34cd2d.
pub const CANOPUS_FW_BT_FREE_CALLABLE: usize = canopus_thumb_callable(0xc34cd2dusize);

/// Recovered `bt_adapter_unregister` at 0xc46a3f8. Thumb callable address 0xc46a3f9.
pub const CANOPUS_FW_BT_ADAPTER_UNREGISTER_CALLABLE: usize = canopus_thumb_callable(0xc46a3f9usize);

/// Recovered `lvx_style_apply` at 0xc4fbe54. Thumb callable address 0xc4fbe55.
pub const CANOPUS_FW_LVX_STYLE_APPLY_CALLABLE: usize = canopus_thumb_callable(0xc4fbe55usize);

/// Recovered `sdp_set_raw_attribute` at 0xc86f130. Thumb callable address 0xc86f131.
pub const CANOPUS_FW_SDP_SET_RAW_ATTRIBUTE_CALLABLE: usize = canopus_thumb_callable(0xc86f131usize);

/// Recovered `bt_queue_free` at 0xc858988. Thumb callable address 0xc858989.
pub const CANOPUS_FW_BT_QUEUE_FREE_CALLABLE: usize = canopus_thumb_callable(0xc858989usize);

/// Recovered `page_finish` at 0xc69b59c. Thumb callable address 0xc69b59d.
pub const CANOPUS_FW_PAGE_FINISH_CALLABLE: usize = canopus_thumb_callable(0xc69b59dusize);

/// Recovered `bt_timer_add` at 0xc8c7fe0. Thumb callable address 0xc8c7fe1.
pub const CANOPUS_FW_BT_TIMER_ADD_CALLABLE: usize = canopus_thumb_callable(0xc8c7fe1usize);

// ---- excluded symbols ----
// _lv_inv_area: restricted - not exported until context/ownership approved
// app_install: restricted - not exported until context/ownership approved
// app_launcher_add: restricted - not exported until context/ownership approved
// app_launcher_data_init: restricted - not exported until context/ownership approved
// app_launcher_del: restricted - not exported until context/ownership approved
// app_lookup: restricted - not exported until context/ownership approved
// bt_adapter_get_instance: restricted - not exported until context/ownership approved
// bt_adapter_get_scan_mode: restricted - not exported until context/ownership approved
// bt_adapter_get_state: restricted - not exported until context/ownership approved
// bt_adapter_register: restricted - not exported until context/ownership approved
// bt_adapter_register_a2dp_callbacks: restricted - not exported until context/ownership approved
// bt_adapter_register_hfp_ag_callbacks: restricted - not exported until context/ownership approved
// bt_adapter_set_scan_mode: restricted - not exported until context/ownership approved
// bt_adapter_unregister: restricted - not exported until context/ownership approved
// bt_alloc: restricted - not exported until context/ownership approved
// bt_buffer_new: restricted - not exported until context/ownership approved
// bt_create_bond_private: restricted - not exported until context/ownership approved
// bt_discovery_start: restricted - not exported until context/ownership approved
// bt_discovery_stop: restricted - not exported until context/ownership approved
// bt_free: restricted - not exported until context/ownership approved
// bt_get_bond_state: restricted - not exported until context/ownership approved
// bt_get_pairing_state: restricted - not exported until context/ownership approved
// bt_l2cap_connect: restricted - not exported until context/ownership approved
// bt_l2cap_disconnect: restricted - not exported until context/ownership approved
// bt_l2cap_submit_cid: restricted - not exported until context/ownership approved
// bt_pair_display_reply: restricted - not exported until context/ownership approved
// bt_pair_request_reply: restricted - not exported until context/ownership approved
// bt_queue_external: restricted - not exported until context/ownership approved
// bt_queue_free: restricted - not exported until context/ownership approved
// bt_remove_bond_private: restricted - not exported until context/ownership approved
// bt_socket_client_sendrecv: restricted - not exported until context/ownership approved
// bt_socket_server_receive: restricted - not exported until context/ownership approved
// bt_timer_add: restricted - not exported until context/ownership approved
// bt_timer_cancel: restricted - not exported until context/ownership approved
// bt_timer_cancel_owned: restricted - not exported until context/ownership approved
// cache_barrier: restricted - not exported until context/ownership approved
// cache_d_clean_all: restricted - not exported until context/ownership approved
// cache_i_clean_invalidate_all: restricted - not exported until context/ownership approved
// clock_gettime: restricted - not exported until context/ownership approved
// close: restricted - not exported until context/ownership approved
// controller_crash_dump: restricted - not exported until context/ownership approved
// core_bt_pair_request_callback: restricted - not exported until context/ownership approved
// driver_close_dispatch: restricted - not exported until context/ownership approved
// driver_ioctl_dispatch: restricted - not exported until context/ownership approved
// errno_location: restricted - not exported until context/ownership approved
// firmware_log: restricted - not exported until context/ownership approved
// gap_host_stock_receive: restricted - not exported until context/ownership approved
// heap_free: restricted - not exported until context/ownership approved
// heap_mallinfo: restricted - not exported until context/ownership approved
// heap_malloc: restricted - not exported until context/ownership approved
// heap_zalloc: restricted - not exported until context/ownership approved
// hfp_ag_connect: restricted - not exported until context/ownership approved
// hfp_ag_disconnect: restricted - not exported until context/ownership approved
// hidden_and_show_app_cb: restricted - not exported until context/ownership approved
// insmod: FORBIDDEN - no binding may ever be generated
// interconnect_close: restricted - not exported until context/ownership approved
// interconnect_connect: restricted - not exported until context/ownership approved
// interconnect_send: restricted - not exported until context/ownership approved
// ioctl: restricted - not exported until context/ownership approved
// kmem_free: restricted - not exported until context/ownership approved
// lseek: restricted - not exported until context/ownership approved
// lv_bar_create: restricted - not exported until context/ownership approved
// lv_bar_set_range: restricted - not exported until context/ownership approved
// lv_bar_set_value: restricted - not exported until context/ownership approved
// lv_cache_drop: restricted - not exported until context/ownership approved
// lv_event_get_code: restricted - not exported until context/ownership approved
// lv_event_get_user_data: restricted - not exported until context/ownership approved
// lv_image_cache_drop: restricted - not exported until context/ownership approved
// lv_image_create: restricted - not exported until context/ownership approved
// lv_image_set_src: restricted - not exported until context/ownership approved
// lv_obj_add_event_cb: restricted - not exported until context/ownership approved
// lv_obj_align_to: restricted - not exported until context/ownership approved
// lv_obj_clear_flag: restricted - not exported until context/ownership approved
// lv_obj_move_to_index: restricted - not exported until context/ownership approved
// lv_obj_remove_style_all: restricted - not exported until context/ownership approved
// lv_obj_set_hidden: restricted - not exported until context/ownership approved
// lv_obj_set_local_style_prop: restricted - not exported until context/ownership approved
// lv_obj_set_style_bg_opa: restricted - not exported until context/ownership approved
// lv_obj_set_style_pad_bottom: restricted - not exported until context/ownership approved
// lv_obj_set_style_pad_top: restricted - not exported until context/ownership approved
// lv_obj_set_width: restricted - not exported until context/ownership approved
// lv_timer_create: restricted - not exported until context/ownership approved
// lv_timer_del: restricted - not exported until context/ownership approved
// lvgl_posix_open: restricted - not exported until context/ownership approved
// lvx_content_pad_bottom: restricted - not exported until context/ownership approved
// lvx_image_set_scale: restricted - not exported until context/ownership approved
// lvx_label_create: restricted - not exported until context/ownership approved
// lvx_label_set_long_mode: restricted - not exported until context/ownership approved
// lvx_label_set_text: restricted - not exported until context/ownership approved
// lvx_list_item_add_content: restricted - not exported until context/ownership approved
// lvx_list_item_create: restricted - not exported until context/ownership approved
// lvx_list_item_update: restricted - not exported until context/ownership approved
// lvx_list_row_create: restricted - not exported until context/ownership approved
// lvx_list_row_trailing: restricted - not exported until context/ownership approved
// lvx_msgbox_create: restricted - not exported until context/ownership approved
// lvx_msgbox_set_content: restricted - not exported until context/ownership approved
// lvx_notification_insert_message: restricted - not exported until context/ownership approved
// lvx_object_add_flag: restricted - not exported until context/ownership approved
// lvx_object_align: restricted - not exported until context/ownership approved
// lvx_object_create: restricted - not exported until context/ownership approved
// lvx_object_delete: restricted - not exported until context/ownership approved
// lvx_object_set_size: restricted - not exported until context/ownership approved
// lvx_page_content_create: restricted - not exported until context/ownership approved
// lvx_page_title_create: restricted - not exported until context/ownership approved
// lvx_style_apply: restricted - not exported until context/ownership approved
// mm_mallinfo: restricted - not exported until context/ownership approved
// mm_memalign: restricted - not exported until context/ownership approved
// modhandle: restricted - not exported until context/ownership approved
// offload_property_apply: restricted - not exported until context/ownership approved
// open: restricted - not exported until context/ownership approved
// page_finish: restricted - not exported until context/ownership approved
// page_goto: restricted - not exported until context/ownership approved
// page_navigator_open_page: restricted - not exported until context/ownership approved
// protobuf_set_ordered_app_list: restricted - not exported until context/ownership approved
// pthread_create_internal: restricted - not exported until context/ownership approved
// quickapp_register_app: restricted - not exported until context/ownership approved
// read: restricted - not exported until context/ownership approved
// register_blockdriver: restricted - not exported until context/ownership approved
// register_driver: restricted - not exported until context/ownership approved
// rename: restricted - not exported until context/ownership approved
// rmmod: restricted - not exported until context/ownership approved
// sdp_builder_create: restricted - not exported until context/ownership approved
// sdp_commit: restricted - not exported until context/ownership approved
// sdp_set_raw_attribute: restricted - not exported until context/ownership approved
// sdp_unregister: restricted - not exported until context/ownership approved
// sem_post: restricted - not exported until context/ownership approved
// sem_trywait: restricted - not exported until context/ownership approved
// sem_wait: restricted - not exported until context/ownership approved
// service_manager_cleanup: restricted - not exported until context/ownership approved
// service_manager_get_profile: restricted - not exported until context/ownership approved
// service_manager_register: restricted - not exported until context/ownership approved
// service_manager_shutdown: restricted - not exported until context/ownership approved
// service_manager_startup: restricted - not exported until context/ownership approved
// sport_titlebar_dispatch: restricted - not exported until context/ownership approved
// system_router_app_wrapper: restricted - not exported until context/ownership approved
// system_router_get_pages_wrapper: restricted - not exported until context/ownership approved
// thirdparty_submit_message_content: restricted - not exported until context/ownership approved
// unlink: restricted - not exported until context/ownership approved
// unregister_blockdriver: restricted - not exported until context/ownership approved
// unregister_driver: restricted - not exported until context/ownership approved
// vendor_hci_transport_register: restricted - not exported until context/ownership approved
// watchface_manager_delete_watchface: restricted - not exported until context/ownership approved
// watchface_reset_watchface: restricted - not exported until context/ownership approved
// write: restricted - not exported until context/ownership approved

