// Generated by `canopus target generate-rust-bindings`. DO NOT EDIT.
//
// target_id: xiaomi-band-10-pro-3.101.030
// firmware : 3.101.030 (CONBINE_LTALM078_T3.101.030_06011854)
// sha256   : f701a84ffcafa67f4d4603ad8cd66a11e5442f27140f5af0982e0975dccd225b
// revision : 1
//
// All firmware calls are `unsafe`; safe wrappers exist only
// where the ABI and ownership have been proven (architecture §12.1).

// ---- recovered type layouts ----
// `#[repr(packed)]` + explicit padding reproduces the exact
// recovered byte layout even when fields are sparse.
#[repr(packed)]
#[derive(Copy, Clone, Debug)]
pub struct file_operations {
    pub open: *mut core::ffi::c_void, // +0x0
    pub close: *mut core::ffi::c_void, // +0x4
    pub read: *mut core::ffi::c_void, // +0x8
    pub write: *mut core::ffi::c_void, // +0xc
    pub _pad_10: [u8; 0x4], // 4
    pub ioctl: *mut core::ffi::c_void, // +0x14
}

#[repr(packed)]
#[derive(Copy, Clone, Debug)]
pub struct launcher_order_record {
    pub app_name: [u8; 128], // +0x0
    pub _pad_80: [u8; 0x4], // 4
    pub flags: u32, // +0x84
    pub _tail: [u8; 0x4], // 4
}

#[repr(packed)]
#[derive(Copy, Clone, Debug)]
pub struct stock_timespec_t {
    pub tv_sec: i32, // +0x0
    pub tv_nsec: i32, // +0x4
}

#[repr(packed)]
#[derive(Copy, Clone, Debug)]
pub struct service_object {
    pub enabled_state: u8, // +0x0
    pub _pad_1: [u8; 0x3], // 3
    pub name: *mut core::ffi::c_void, // +0x4
    pub service_id: u8, // +0x8
    pub profile_group: u8, // +0x9
    pub _pad_a: [u8; 0x1a], // 26
    pub startup_cb: *mut core::ffi::c_void, // +0x24
    pub _pad_28: [u8; 0x8], // 8
    pub startup_eligibility_cb: *mut core::ffi::c_void, // +0x30
    pub get_profile_cb: *mut core::ffi::c_void, // +0x34
    pub cleanup_cb: *mut core::ffi::c_void, // +0x38
    pub _tail: [u8; 0x4], // 4
}

#[repr(packed)]
#[derive(Copy, Clone, Debug)]
pub struct ordered_app_entry {
    pub app_name: *mut core::ffi::c_void, // +0x0
    pub _pad_4: [u8; 0x4], // 4
    pub enabled: u8, // +0x8
    pub hidden: u8, // +0x9
    pub _tail: [u8; 0x6], // 6
}

#[repr(packed)]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_struct {
    pub name: [u8; 128], // +0x0
    pub flags: u8, // +0x80
    pub _tail: [u8; 0x3], // 3
}

#[repr(packed)]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_record {
    pub app_id: u16, // +0x0
    pub _pad_2: [u8; 0x2], // 2
    pub icon_handle: *mut core::ffi::c_void, // +0x4
    pub name: *mut core::ffi::c_void, // +0x8
    pub icon_name: *mut core::ffi::c_void, // +0xc
    pub _pad_10: [u8; 0x4], // 4
    pub flags: u8, // +0x14
    pub _tail: [u8; 0x3], // 3
}

#[repr(packed)]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_descriptor {
    pub reserved0: u64, // +0x0
    pub name: *mut core::ffi::c_void, // +0x8
    pub icon: *mut core::ffi::c_void, // +0xc
    pub app_id: u16, // +0x10
    pub flags: u8, // +0x12
    pub _pad_13: [u8; 0x9], // 9
    pub icon_resolver: *mut core::ffi::c_void, // +0x1c
    pub _pad_20: [u8; 0x1c], // 28
    pub hidden_flags: u8, // +0x3c
    pub _tail: [u8; 0x3], // 3
}

// ---- runtime identity guard ----
/// Returns 0 when the running firmware matches this pack's
/// version + build identity, -1 otherwise. Call once before use.
pub fn canopus_identity_guard() -> i32 {
    const EXPECT_VERSION: &[u8] = b"3.101.030";
    const EXPECT_BUILD: &[u8] = b"CONBINE_LTALM078_T3.101.030_06011854";
    if !c_str_eq(0x0C0C0810, EXPECT_VERSION) { return -1; }
    if !c_str_eq(0x0C0C0850, EXPECT_BUILD) { return -1; }
    0
}

/// Compares a NUL-terminated string at `addr` to `expected`.
fn c_str_eq(addr: usize, expected: &[u8]) -> bool {
    let mut i = 0usize;
    while i <= expected.len() && i < 64 {
        let b = unsafe { *((addr + i) as *const u8) };
        if i < expected.len() {
            if b != expected[i] { return false; }
        } else {
            return b == 0;
        }
        i += 1;
    }
    false
}

// ---- typed firmware bindings (unsafe) ----
/// Recovered `clock_gettime` at 0x0C1EC8B4. Thumb callable address 0x0C1EC8B5.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_clock_gettime(a0: u32, a1: *const stock_timespec_t) -> i32 {
    let f: extern "C" fn(u32, *const stock_timespec_t) -> i32 = unsafe { core::mem::transmute(0x0C1EC8B5usize) };
    f(a0, a1)
}

/// Recovered `register_driver` at 0x0C1A0D50. Thumb callable address 0x0C1A0D51.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_register_driver(a0: *const u8, a1: *const core::ffi::c_void, a2: u32, a3: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*const u8, *const core::ffi::c_void, u32, *mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(0x0C1A0D51usize) };
    f(a0, a1, a2, a3)
}

/// Recovered `unregister_driver` at 0x0C1A0E1C. Thumb callable address 0x0C1A0E1D.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_unregister_driver(a0: *const u8) -> i32 {
    let f: extern "C" fn(*const u8) -> i32 = unsafe { core::mem::transmute(0x0C1A0E1Dusize) };
    f(a0)
}

// ---- excluded symbols ----
// app_launcher_add: restricted - not exported until context/ownership approved
// app_launcher_data_init: restricted - not exported until context/ownership approved
// app_launcher_del: restricted - not exported until context/ownership approved
// bt_adapter_register_a2dp_callbacks: FORBIDDEN - no binding may ever be generated
// bt_adapter_register_hfp_ag_callbacks: FORBIDDEN - no binding may ever be generated
// bt_socket_server_receive: FORBIDDEN - no binding may ever be generated
// btsnoop_avdtp_recognizer: FORBIDDEN - no binding may ever be generated
// controller_crash_dump: FORBIDDEN - no binding may ever be generated
// driver_close_dispatch: restricted - not exported until context/ownership approved
// driver_ioctl_dispatch: restricted - not exported until context/ownership approved
// driver_open_dispatch: restricted - not exported until context/ownership approved
// driver_read_dispatch: restricted - not exported until context/ownership approved
// driver_write_dispatch: FORBIDDEN - no binding may ever be generated
// firmware_log: restricted - not exported until context/ownership approved
// heap_free: restricted - not exported until context/ownership approved
// heap_mallinfo: restricted - not exported until context/ownership approved
// heap_malloc: restricted - not exported until context/ownership approved
// heap_zalloc: restricted - not exported until context/ownership approved
// hfp_ag_connect: FORBIDDEN - no binding may ever be generated
// hfp_ag_disconnect: FORBIDDEN - no binding may ever be generated
// hidden_and_show_app_cb: restricted - not exported until context/ownership approved
// offload_property_apply: FORBIDDEN - no binding may ever be generated
// protobuf_set_ordered_app_list: restricted - not exported until context/ownership approved
// pthread_create_internal: FORBIDDEN - no binding may ever be generated
// public_work_queue: FORBIDDEN - no binding may ever be generated
// register_blockdriver: restricted - not exported until context/ownership approved
// sem_post: restricted - not exported until context/ownership approved
// sem_trywait: restricted - not exported until context/ownership approved
// sem_wait: restricted - not exported until context/ownership approved
// service_manager_cleanup: FORBIDDEN - no binding may ever be generated
// service_manager_get_profile: restricted - not exported until context/ownership approved
// service_manager_register: restricted - not exported until context/ownership approved
// service_manager_shutdown: restricted - not exported until context/ownership approved
// service_manager_startup: restricted - not exported until context/ownership approved
// unregister_blockdriver: restricted - not exported until context/ownership approved
// vendor_hci_transport_register: FORBIDDEN - no binding may ever be generated

