// Generated by `canopus target generate-rust-bindings`. DO NOT EDIT.
//
// target_id: xiaomi-band-9-pro-3.1.175
// firmware : 3.1.175 (CONBINE_LTALM054_T1175_04141021_release_5793)
// sha256   : 4f43b325addd6d9e6e7c7e2a4d00ffe3f23d5fb1560d8fe503544002ac1f516b
// revision : 1
// input_digest: 995430cc031f4f8a
//
// All firmware calls are `unsafe`; safe wrappers exist only
// where the ABI and ownership have been proven (architecture §12.1).

/// Converts a recovered Thumb entry or callable address into the only valid
/// indirect-call address. Target-private ABI adapters must use this instead
/// of transmuting raw firmware addresses directly.
#[inline(always)]
pub const fn canopus_thumb_callable(entry_or_callable: usize) -> usize {
    entry_or_callable | 1usize
}

// ---- recovered type layouts ----
// `#[repr(C, packed(N))]` + explicit padding reproduces the exact
// recovered byte layout and its target-declared alignment.
pub type canopus_interconnect_recv_cb = extern "C" fn(*mut core::ffi::c_void, i32, *const canopus_interconnect_message, *const u8) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct file_operations {
    pub open: *mut core::ffi::c_void, // +0x0
    pub close: *mut core::ffi::c_void, // +0x4
    pub read: *mut core::ffi::c_void, // +0x8
    pub write: *mut core::ffi::c_void, // +0xc
    pub _pad_10: [u8; 0x4], // 4
    pub ioctl: *mut core::ffi::c_void, // +0x14
    pub _tail: [u8; 0x18], // 24
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_order_record {
    pub app_name: [u8; 128], // +0x0
    pub _pad_80: [u8; 0x4], // 4
    pub flags: u32, // +0x84
    pub _tail: [u8; 0x4], // 4
}

pub type canopus_lvx_event_cb = extern "C" fn(*mut core::ffi::c_void) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct stock_timespec_t {
    pub tv_sec: i64, // +0x0
    pub tv_nsec: i32, // +0x8
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct firmware_page_descriptor {
    pub parent_descriptor: *mut core::ffi::c_void, // +0x0
    pub _pad_4: [u8; 0xc], // 12
    pub page_name: *mut core::ffi::c_void, // +0x10
    pub page_id: u16, // +0x14
    pub app_id: u16, // +0x16
    pub flags: u16, // +0x18
    pub _pad_1a: [u8; 0x2], // 2
    pub scheduler_deadline: i32, // +0x1c
    pub scheduler_priority: i32, // +0x20
    pub async_destroy_state: u32, // +0x24
    pub lifecycle_state: u8, // +0x28
    pub layer: u8, // +0x29
    pub page_kind: u8, // +0x2a
    pub _pad_2b: [u8; 0x1], // 1
    pub activity_context: *mut core::ffi::c_void, // +0x2c
    pub root_object: *mut core::ffi::c_void, // +0x30
    pub on_signal: *mut core::ffi::c_void, // +0x34
    pub runtime_default_56: *mut core::ffi::c_void, // +0x38
    pub _pad_3c: [u8; 0x4], // 4
    pub registry_prev: *mut core::ffi::c_void, // +0x40
    pub registry_next: *mut core::ffi::c_void, // +0x44
    pub runtime_parent: *mut core::ffi::c_void, // +0x48
    pub on_create: *mut core::ffi::c_void, // +0x4c
    pub on_resume: *mut core::ffi::c_void, // +0x50
    pub on_foreground_data: *mut core::ffi::c_void, // +0x54
    pub on_pause: *mut core::ffi::c_void, // +0x58
    pub on_destroy: *mut core::ffi::c_void, // +0x5c
    pub on_ui_destroy: *mut core::ffi::c_void, // +0x60
    pub extension_callback_100: *mut core::ffi::c_void, // +0x64
    pub extension_callback_104: *mut core::ffi::c_void, // +0x68
    pub extension_callback_108: *mut core::ffi::c_void, // +0x6c
    pub _tail: [u8; 0x4], // 4
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_interconnect_app_info {
    pub package_name: *mut core::ffi::c_void, // +0x0
    pub display_name: *mut core::ffi::c_void, // +0x4
    pub icon_file: *mut core::ffi::c_void, // +0x8
    pub extra: *mut core::ffi::c_void, // +0xc
    pub fingerprint: [u8; 20], // +0x10
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct firmware_notification_message {
    pub message_id: u64, // +0x0
    pub repeat_count: u32, // +0x8
    pub title: *mut core::ffi::c_void, // +0xc
    pub source: *mut core::ffi::c_void, // +0x10
    pub body: *mut core::ffi::c_void, // +0x14
    pub auxiliary_text: *mut core::ffi::c_void, // +0x18
    pub small_icon_path: *mut core::ffi::c_void, // +0x1c
    pub large_icon_path: *mut core::ffi::c_void, // +0x20
    pub extension_text_36: *mut core::ffi::c_void, // +0x24
    pub extension_text_40: *mut core::ffi::c_void, // +0x28
    pub timestamp: u32, // +0x2c
    pub _pad_30: [u8; 0x8], // 8
    pub action_callback: *mut core::ffi::c_void, // +0x38
    pub action_context: u32, // +0x3c
    pub extension_64: u32, // +0x40
    pub extension_68: u32, // +0x44
    pub open_callback: *mut core::ffi::c_void, // +0x48
    pub destroy_callback: *mut core::ffi::c_void, // +0x4c
    pub start_reminder: u8, // +0x50
    pub flags_81: u8, // +0x51
    pub flags_82: u8, // +0x52
    pub _pad_53: [u8; 0x1], // 1
    pub callback_data: *mut core::ffi::c_void, // +0x54
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct service_object {
    pub enabled_state: u8, // +0x0
    pub _pad_1: [u8; 0x3], // 3
    pub name: *mut core::ffi::c_void, // +0x4
    pub service_id: u8, // +0x8
    pub profile_group: u8, // +0x9
    pub _pad_a: [u8; 0x1a], // 26
    pub startup_cb: *mut core::ffi::c_void, // +0x24
    pub _pad_28: [u8; 0x8], // 8
    pub startup_eligibility_cb: *mut core::ffi::c_void, // +0x30
    pub get_profile_cb: *mut core::ffi::c_void, // +0x34
    pub cleanup_cb: *mut core::ffi::c_void, // +0x38
    pub _tail: [u8; 0x4], // 4
}

pub type canopus_interconnect_send_done = extern "C" fn(*mut core::ffi::c_void, i32, *const canopus_interconnect_message, *mut core::ffi::c_void) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_interconnect_message {
    pub r#type: u8, // +0x0
    pub _pad_1: [u8; 0x3], // 3
    pub length: u32, // +0x4
    pub _pad_8: [u8; 0x8], // 8
    pub value: *mut core::ffi::c_void, // +0x10
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct ordered_app_entry {
    pub app_name: *mut core::ffi::c_void, // +0x0
    pub _pad_4: [u8; 0x4], // 4
    pub enabled: u8, // +0x8
    pub hidden: u8, // +0x9
    pub _tail: [u8; 0x6], // 6
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_struct {
    pub name: [u8; 128], // +0x0
    pub flags: u8, // +0x80
    pub _tail: [u8; 0x3], // 3
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_record {
    pub app_id: u16, // +0x0
    pub _pad_2: [u8; 0x2], // 2
    pub icon_handle: *mut core::ffi::c_void, // +0x4
    pub name: *mut core::ffi::c_void, // +0x8
    pub icon_name: *mut core::ffi::c_void, // +0xc
    pub _pad_10: [u8; 0x4], // 4
    pub flags: u8, // +0x14
    pub _tail: [u8; 0x3], // 3
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_descriptor {
    pub registry_links: u64, // +0x0
    pub package_name: *mut core::ffi::c_void, // +0x8
    pub launcher_icon_resource: *mut core::ffi::c_void, // +0xc
    pub app_id: u16, // +0x10
    pub flags: u16, // +0x12
    pub owned_string_20: *mut core::ffi::c_void, // +0x14
    pub owned_string_24: *mut core::ffi::c_void, // +0x18
    pub launcher_metadata_callback: *mut core::ffi::c_void, // +0x1c
    pub _pad_20: [u8; 0xc], // 12
    pub page_registry: *mut core::ffi::c_void, // +0x2c
    pub _pad_30: [u8; 0x8], // 8
    pub hidden_flags: u8, // +0x38
    pub _tail: [u8; 0x3], // 3
}

// ---- runtime identity guard ----
/// Returns 0 when the running firmware matches this pack's
/// version + build identity, -1 otherwise. Call once before use.
pub fn canopus_identity_guard() -> i32 {
    const EXPECT_VERSION: &[u8] = b"3.1.175";
    const EXPECT_BUILD: &[u8] = b"CONBINE_LTALM054_T1175_04141021_release_5793";
    if !c_str_eq(0x0C080810, EXPECT_VERSION) { return -1; }
    if !c_str_eq(0x0C080850, EXPECT_BUILD) { return -1; }
    0
}

/// Compares a NUL-terminated string at `addr` to `expected`.
fn c_str_eq(addr: usize, expected: &[u8]) -> bool {
    let mut i = 0usize;
    while i <= expected.len() && i < 64 {
        let b = unsafe { *((addr + i) as *const u8) };
        if i < expected.len() {
            if b != expected[i] { return false; }
        } else {
            return b == 0;
        }
        i += 1;
    }
    false
}

// ---- typed firmware bindings (unsafe) ----
/// Recovered `lvx_object_set_size` at 0x0C23DDE0. Thumb callable address 0x0C23DDE1.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_object_set_size(a0: *mut core::ffi::c_void, a1: i32, a2: i32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, i32, i32) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C23DDE1usize)) };
    f(a0, a1, a2);
}

/// Recovered `lvx_page_title_create` at 0x0C2781D4. Thumb callable address 0x0C2781D5.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_page_title_create(a0: *mut core::ffi::c_void, a1: *const u8, a2: u32, a3: canopus_lvx_event_cb, a4: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, u32, canopus_lvx_event_cb, *mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C2781D5usize)) };
    f(a0, a1, a2, a3, a4)
}

/// Recovered `lvx_align_to` at 0x0C240CE8. Thumb callable address 0x0C240CE9.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_align_to(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void, a2: u32, a3: i32, a4: i32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void, u32, i32, i32) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C240CE9usize)) };
    f(a0, a1, a2, a3, a4);
}

/// Recovered `interconnect_close` at 0x0C4F7170. Thumb callable address 0x0C4F7171.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_interconnect_close(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C4F7171usize)) };
    f(a0)
}

/// Recovered `bt_remove_bond` at 0x0C3BFE98. Thumb callable address 0x0C3BFE99.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_remove_bond(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C3BFE99usize)) };
    f(a0, a1)
}

/// Recovered `mm_free` at 0x0C0F19DC. Thumb callable address 0x0C0F19DD.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_mm_free(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C0F19DDusize)) };
    f(a0, a1);
}

/// Recovered `mpu_region_configure` at 0x0C51D758. Thumb callable address 0x0C51D759.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_mpu_region_configure(a0: u32, a1: u32, a2: u32, a3: u32, a4: u32) -> i32 {
    let f: extern "C" fn(u32, u32, u32, u32, u32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C51D759usize)) };
    f(a0, a1, a2, a3, a4)
}

/// Recovered `bt_discovery_stop` at 0x0C3C002C. Thumb callable address 0x0C3C002D.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_discovery_stop(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C3C002Dusize)) };
    f(a0)
}

/// Recovered `write` at 0x0C380106. Thumb callable address 0x0C380107.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_write(a0: i32, a1: *const core::ffi::c_void, a2: u32) -> i32 {
    let f: extern "C" fn(i32, *const core::ffi::c_void, u32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C380107usize)) };
    f(a0, a1, a2)
}

/// Recovered `mm_alloc` at 0x0C0F24E0. Thumb callable address 0x0C0F24E1.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_mm_alloc(a0: u32) -> *mut core::ffi::c_void {
    let f: extern "C" fn(u32) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C0F24E1usize)) };
    f(a0)
}

/// Recovered `unlink` at 0x0C3800E8. Thumb callable address 0x0C3800E9.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_unlink(a0: *const u8) -> i32 {
    let f: extern "C" fn(*const u8) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C3800E9usize)) };
    f(a0)
}

/// Recovered `mm_memalign_default` at 0x0C0F21EC. Thumb callable address 0x0C0F21ED.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_mm_memalign_default(a0: u32, a1: u32) -> *mut core::ffi::c_void {
    let f: extern "C" fn(u32, u32) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C0F21EDusize)) };
    f(a0, a1)
}

/// Recovered `app_install` at 0x0C44B5D0. Thumb callable address 0x0C44B5D1.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_app_install(a0: *const launcher_app_descriptor, a1: *const *const firmware_page_descriptor, a2: u32) -> i32 {
    let f: extern "C" fn(*const launcher_app_descriptor, *const *const firmware_page_descriptor, u32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C44B5D1usize)) };
    f(a0, a1, a2)
}

/// Recovered `bt_pair_request_reply` at 0x0C3BFD48. Thumb callable address 0x0C3BFD49.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_pair_request_reply(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C3BFD49usize)) };
    f(a0)
}

/// Recovered `lvx_timer_create` at 0x0C25CB8C. Thumb callable address 0x0C25CB8D.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_timer_create(a0: canopus_lvx_event_cb, a1: u32, a2: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(canopus_lvx_event_cb, u32, *mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C25CB8Dusize)) };
    f(a0, a1, a2)
}

/// Recovered `mpu_region_allocate` at 0x0C51D8D0. Thumb callable address 0x0C51D8D1.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_mpu_region_allocate() -> u32 {
    let f: extern "C" fn() -> u32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C51D8D1usize)) };
    f()
}

/// Recovered `lvx_label_set_text` at 0x0C266C28. Thumb callable address 0x0C266C29.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_label_set_text(a0: *mut core::ffi::c_void, a1: *const u8) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C266C29usize)) };
    f(a0, a1);
}

/// Recovered `read` at 0x0C37F9EA. Thumb callable address 0x0C37F9EB.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_read(a0: i32, a1: *mut core::ffi::c_void, a2: u32) -> i32 {
    let f: extern "C" fn(i32, *mut core::ffi::c_void, u32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C37F9EBusize)) };
    f(a0, a1, a2)
}

/// Recovered `app_lookup` at 0x0C449334. Thumb callable address 0x0C449335.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_app_lookup(a0: u16) -> *mut core::ffi::c_void {
    let f: extern "C" fn(u16) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C449335usize)) };
    f(a0)
}

/// Recovered `app_launcher_add` at 0x0C2A7CB8. Thumb callable address 0x0C2A7CB9.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_app_launcher_add(a0: u16) -> i32 {
    let f: extern "C" fn(u16) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C2A7CB9usize)) };
    f(a0)
}

/// Recovered `close` at 0x0C37EFF8. Thumb callable address 0x0C37EFF9.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_close(a0: i32) -> i32 {
    let f: extern "C" fn(i32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C37EFF9usize)) };
    f(a0)
}

/// Recovered `mm_free_default` at 0x0C0F1B00. Thumb callable address 0x0C0F1B01.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_mm_free_default(a0: *mut core::ffi::c_void) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C0F1B01usize)) };
    f(a0);
}

/// Recovered `bt_create_bond` at 0x0C3BFDE0. Thumb callable address 0x0C3BFDE1.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_create_bond(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C3BFDE1usize)) };
    f(a0, a1)
}

/// Recovered `interconnect_connect` at 0x0C1134D4. Thumb callable address 0x0C1134D5.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_interconnect_connect(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void, a2: *const u8, a3: *const u8, a4: canopus_interconnect_recv_cb) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void, *const u8, *const u8, canopus_interconnect_recv_cb) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C1134D5usize)) };
    f(a0, a1, a2, a3, a4)
}

/// Recovered `lvx_list_row_set_trailing` at 0x0C272E1C. Thumb callable address 0x0C272E1D.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_list_row_set_trailing(a0: *mut core::ffi::c_void, a1: u8, a2: u8) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, u8, u8) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C272E1Dusize)) };
    f(a0, a1, a2)
}

/// Recovered `unregister_driver` at 0x0C381C00. Thumb callable address 0x0C381C01.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_unregister_driver(a0: *const u8) -> i32 {
    let f: extern "C" fn(*const u8) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C381C01usize)) };
    f(a0)
}

// lvx_list_row_update: skipped (argument type not mappable)
/// Recovered `register_driver` at 0x0C4F0108. Thumb callable address 0x0C4F0109.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_register_driver(a0: *const u8, a1: *const core::ffi::c_void, a2: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*const u8, *const core::ffi::c_void, *mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C4F0109usize)) };
    f(a0, a1, a2)
}

/// Recovered `bt_discovery_start` at 0x0C3BFFC0. Thumb callable address 0x0C3BFFC1.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_discovery_start(a0: *mut core::ffi::c_void, a1: i32) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, i32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C3BFFC1usize)) };
    f(a0, a1)
}

// open: skipped (argument type not mappable)
/// Recovered `page_goto` at 0x0C49E7CC. Thumb callable address 0x0C49E7CD.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_page_goto(a0: u32, a1: u32, a2: u32, a3: u32) -> i32 {
    let f: extern "C" fn(u32, u32, u32, u32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C49E7CDusize)) };
    f(a0, a1, a2, a3)
}

/// Recovered `lvx_object_align` at 0x0C23DE6A. Thumb callable address 0x0C23DE6B.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_object_align(a0: *mut core::ffi::c_void, a1: u32, a2: i32, a3: i32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, u32, i32, i32) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C23DE6Busize)) };
    f(a0, a1, a2, a3);
}

/// Recovered `clock_gettime` at 0x0C0BBB10. Thumb callable address 0x0C0BBB11.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_clock_gettime(a0: u32, a1: *const stock_timespec_t) -> i32 {
    let f: extern "C" fn(u32, *const stock_timespec_t) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C0BBB11usize)) };
    f(a0, a1)
}

/// Recovered `quickapp_register_app` at 0x0C2C655C. Thumb callable address 0x0C2C655D.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_quickapp_register_app(a0: u16, a1: *const canopus_interconnect_app_info) -> i32 {
    let f: extern "C" fn(u16, *const canopus_interconnect_app_info) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C2C655Dusize)) };
    f(a0, a1)
}

/// Recovered `errno_location` at 0x0C0E4B6C. Thumb callable address 0x0C0E4B6D.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_errno_location() -> *const i32 {
    let f: extern "C" fn() -> *const i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C0E4B6Dusize)) };
    f()
}

/// Recovered `page_finish` at 0x0C44FC90. Thumb callable address 0x0C44FC91.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_page_finish(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C44FC91usize)) };
    f(a0)
}

/// Recovered `manager_delete_watchface` at 0x0C44F470. Thumb callable address 0x0C44F471.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_manager_delete_watchface(a0: *const u8) -> i32 {
    let f: extern "C" fn(*const u8) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C44F471usize)) };
    f(a0)
}

/// Recovered `bt_pair_display_reply` at 0x0C3BFD94. Thumb callable address 0x0C3BFD95.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_pair_display_reply(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C3BFD95usize)) };
    f(a0)
}

/// Recovered `lvx_timer_delete` at 0x0C25B4B8. Thumb callable address 0x0C25B4B9.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_timer_delete(a0: *mut core::ffi::c_void) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C25B4B9usize)) };
    f(a0);
}

/// Recovered `lvx_notification_insert_message` at 0x0C4F1C44. Thumb callable address 0x0C4F1C45.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_notification_insert_message(a0: *const firmware_notification_message) -> i32 {
    let f: extern "C" fn(*const firmware_notification_message) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C4F1C45usize)) };
    f(a0)
}

/// Recovered global `interconnect_loop` at 0x200C9D28.
pub const canopus_fw_interconnect_loop: usize = 0x200C9D28usize;

/// Recovered `lvx_event_add` at 0x0C244F3C. Thumb callable address 0x0C244F3D.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_event_add(a0: *mut core::ffi::c_void, a1: canopus_lvx_event_cb, a2: u32, a3: *mut core::ffi::c_void) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, canopus_lvx_event_cb, u32, *mut core::ffi::c_void) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C244F3Dusize)) };
    f(a0, a1, a2, a3);
}

/// Recovered `bt_adapter_get_instance` at 0x0C3BCAA8. Thumb callable address 0x0C3BCAA9.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_adapter_get_instance() -> *mut core::ffi::c_void {
    let f: extern "C" fn() -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C3BCAA9usize)) };
    f()
}

/// Recovered `lvx_label_create` at 0x0C261660. Thumb callable address 0x0C261661.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_label_create(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C261661usize)) };
    f(a0)
}

/// Recovered `interconnect_send` at 0x0C114044. Thumb callable address 0x0C114045.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_interconnect_send(a0: *mut core::ffi::c_void, a1: *const u8, a2: *const canopus_interconnect_message, a3: canopus_interconnect_send_done, a4: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, *const canopus_interconnect_message, canopus_interconnect_send_done, *mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C114045usize)) };
    f(a0, a1, a2, a3, a4)
}

/// Recovered `rename` at 0x0C37FA24. Thumb callable address 0x0C37FA25.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_rename(a0: *const u8, a1: *const u8) -> i32 {
    let f: extern "C" fn(*const u8, *const u8) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C37FA25usize)) };
    f(a0, a1)
}

/// Recovered `lvx_style_apply` at 0x0C371CA0. Thumb callable address 0x0C371CA1.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_style_apply(a0: *mut core::ffi::c_void, a1: *const core::ffi::c_void, a2: u32, a3: u32) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const core::ffi::c_void, u32, u32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C371CA1usize)) };
    f(a0, a1, a2, a3)
}

/// Recovered `lvx_list_row_create` at 0x0C2D9C08. Thumb callable address 0x0C2D9C09.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_list_row_create(a0: *mut core::ffi::c_void, a1: *const u8) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C2D9C09usize)) };
    f(a0, a1)
}

/// Recovered `mpu_region_release` at 0x0C51D928. Thumb callable address 0x0C51D929.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_mpu_region_release(a0: u32) -> () {
    let f: extern "C" fn(u32) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C51D929usize)) };
    f(a0);
}

/// Recovered `lvx_object_add_flag` at 0x0C23E8F8. Thumb callable address 0x0C23E8F9.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_object_add_flag(a0: *mut core::ffi::c_void, a1: u32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, u32) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C23E8F9usize)) };
    f(a0, a1);
}

/// Recovered `lvx_list_row_trailing` at 0x0C272C8E. Thumb callable address 0x0C272C8F.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_list_row_trailing(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C272C8Fusize)) };
    f(a0)
}

