// Generated by `canopus target generate-rust-bindings`. DO NOT EDIT.
//
// target_id: xiaomi-band-11-4.100.108
// firmware : 4.100.108 (user-4.100.108-cn-202607230300)
// sha256   : 9315ca353f624cec25dfcfc98a95ba959e2d7b24573bf1d6adf16ea10341bd99
// revision : 1
// input_digest: e2e6c63535137366
//
// All firmware calls are `unsafe`; safe wrappers exist only
// where the ABI and ownership have been proven (architecture §12.1).

/// Converts a recovered Thumb entry or callable address into the only valid
/// indirect-call address. Target-private ABI adapters must use this instead
/// of transmuting raw firmware addresses directly.
#[inline(always)]
pub const fn canopus_thumb_callable(entry_or_callable: usize) -> usize {
    entry_or_callable | 1usize
}

// ---- runtime identity guard ----
/// Returns 0 when the running firmware matches this pack's
/// version + build identity, -1 otherwise. Call once before use.
pub fn canopus_identity_guard() -> i32 {
    const EXPECT_VERSION: &[u8] = b"4.100.108";
    const EXPECT_BUILD: &[u8] = b"user-4.100.108-cn-202607230300";
    if !c_str_eq(0xCA0044D, EXPECT_VERSION) { return -1; }
    if !c_str_eq(0xCA004D6, EXPECT_BUILD) { return -1; }
    0
}

/// Compares a NUL-terminated string at `addr` to `expected`.
fn c_str_eq(addr: usize, expected: &[u8]) -> bool {
    let mut i = 0usize;
    while i <= expected.len() && i < 64 {
        let b = unsafe { *((addr + i) as *const u8) };
        if i < expected.len() {
            if b != expected[i] { return false; }
        } else {
            return b == 0;
        }
        i += 1;
    }
    false
}

// ---- typed firmware bindings (unsafe) ----
/// Recovered `sem_post` at 0xc359980. Thumb callable address 0xc359981.
pub const CANOPUS_FW_SEM_POST_CALLABLE: usize = canopus_thumb_callable(0xc359981usize);

/// Recovered `app_install` at 0xc6a6bf8. Thumb callable address 0xc6a6bf9.
pub const CANOPUS_FW_APP_INSTALL_CALLABLE: usize = canopus_thumb_callable(0xc6a6bf9usize);

/// Recovered `controller_crash_dump` at 0xc926ee8. Thumb callable address 0xc926ee9.
pub const CANOPUS_FW_CONTROLLER_CRASH_DUMP_CALLABLE: usize = canopus_thumb_callable(0xc926ee9usize);

/// Recovered `rename` at 0xc33d6c4. Thumb callable address 0xc33d6c5.
pub const CANOPUS_FW_RENAME_CALLABLE: usize = canopus_thumb_callable(0xc33d6c5usize);

/// Recovered `protobuf_set_ordered_app_list` at 0xc5490b4. Thumb callable address 0xc5490b5.
pub const CANOPUS_FW_PROTOBUF_SET_ORDERED_APP_LIST_CALLABLE: usize = canopus_thumb_callable(0xc5490b5usize);

/// Recovered `lv_image_set_src` at 0xc3b2a5c. Thumb callable address 0xc3b2a5d.
pub const CANOPUS_FW_LV_IMAGE_SET_SRC_CALLABLE: usize = canopus_thumb_callable(0xc3b2a5dusize);

/// Recovered `ioctl` at 0xc341b98. Thumb callable address 0xc341b99.
pub const CANOPUS_FW_IOCTL_CALLABLE: usize = canopus_thumb_callable(0xc341b99usize);

/// Recovered `unlink` at 0xc33caf8. Thumb callable address 0xc33caf9.
pub const CANOPUS_FW_UNLINK_CALLABLE: usize = canopus_thumb_callable(0xc33caf9usize);

/// Recovered `sem_trywait` at 0xc359470. Thumb callable address 0xc359471.
pub const CANOPUS_FW_SEM_TRYWAIT_CALLABLE: usize = canopus_thumb_callable(0xc359471usize);

/// Recovered `sem_wait` at 0xc359510. Thumb callable address 0xc359511.
pub const CANOPUS_FW_SEM_WAIT_CALLABLE: usize = canopus_thumb_callable(0xc359511usize);

// ---- excluded symbols ----
// app_install: restricted - not exported until context/ownership approved
// controller_crash_dump: restricted - not exported until context/ownership approved
// ioctl: restricted - not exported until context/ownership approved
// lv_image_set_src: restricted - not exported until context/ownership approved
// protobuf_set_ordered_app_list: restricted - not exported until context/ownership approved
// rename: restricted - not exported until context/ownership approved
// sem_post: restricted - not exported until context/ownership approved
// sem_trywait: restricted - not exported until context/ownership approved
// sem_wait: restricted - not exported until context/ownership approved
// unlink: restricted - not exported until context/ownership approved

