// Generated by `canopus target generate-rust-bindings`. DO NOT EDIT.
//
// target_id: xiaomi-band-10-pro-3.101.036
// firmware : 3.101.036 (CONBINE_LTALM078_T3.101.036_06242053)
// sha256   : 662d67f5e247e31e194d3161024890ba93b9d29d70b290fadb9aac8ce8ec3c81
// revision : 2
// input_digest: bfeef8ec3d7e21c1
//
// All firmware calls are `unsafe`; safe wrappers exist only
// where the ABI and ownership have been proven (architecture §12.1).

/// Converts a recovered Thumb entry or callable address into the only valid
/// indirect-call address. Target-private ABI adapters must use this instead
/// of transmuting raw firmware addresses directly.
#[inline(always)]
pub const fn canopus_thumb_callable(entry_or_callable: usize) -> usize {
    entry_or_callable | 1usize
}

// ---- recovered type layouts ----
// `#[repr(C, packed(N))]` + explicit padding reproduces the exact
// recovered byte layout and its target-declared alignment.
pub type canopus_interconnect_recv_cb = extern "C" fn(*mut core::ffi::c_void, i32, *const canopus_interconnect_message, *const u8) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct file_operations {
    pub open: *mut core::ffi::c_void, // +0x0
    pub close: *mut core::ffi::c_void, // +0x4
    pub read: *mut core::ffi::c_void, // +0x8
    pub write: *mut core::ffi::c_void, // +0xc
    pub _pad_10: [u8; 0x4], // 4
    pub ioctl: *mut core::ffi::c_void, // +0x14
    pub _tail: [u8; 0x18], // 24
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_order_record {
    pub app_name: [u8; 128], // +0x0
    pub _pad_80: [u8; 0x4], // 4
    pub flags: u32, // +0x84
    pub _tail: [u8; 0x4], // 4
}

pub type canopus_lvx_event_cb = extern "C" fn(*mut core::ffi::c_void) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct stock_timespec_t {
    pub tv_sec: i64, // +0x0
    pub tv_nsec: i32, // +0x8
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct firmware_page_descriptor {
    pub parent_descriptor: *mut core::ffi::c_void, // +0x0
    pub _pad_4: [u8; 0xc], // 12
    pub page_name: *mut core::ffi::c_void, // +0x10
    pub page_id: u16, // +0x14
    pub app_id: u16, // +0x16
    pub flags: u16, // +0x18
    pub _pad_1a: [u8; 0x2], // 2
    pub scheduler_deadline: i32, // +0x1c
    pub scheduler_priority: i32, // +0x20
    pub async_destroy_state: u32, // +0x24
    pub lifecycle_state: u8, // +0x28
    pub layer: u8, // +0x29
    pub page_kind: u8, // +0x2a
    pub _pad_2b: [u8; 0x1], // 1
    pub activity_context: *mut core::ffi::c_void, // +0x2c
    pub root_object: *mut core::ffi::c_void, // +0x30
    pub on_signal: *mut core::ffi::c_void, // +0x34
    pub runtime_default_56: *mut core::ffi::c_void, // +0x38
    pub _pad_3c: [u8; 0x4], // 4
    pub registry_prev: *mut core::ffi::c_void, // +0x40
    pub registry_next: *mut core::ffi::c_void, // +0x44
    pub runtime_parent: *mut core::ffi::c_void, // +0x48
    pub on_create: *mut core::ffi::c_void, // +0x4c
    pub on_resume: *mut core::ffi::c_void, // +0x50
    pub on_foreground_data: *mut core::ffi::c_void, // +0x54
    pub on_pause: *mut core::ffi::c_void, // +0x58
    pub on_destroy: *mut core::ffi::c_void, // +0x5c
    pub on_ui_destroy: *mut core::ffi::c_void, // +0x60
    pub extension_callback_100: *mut core::ffi::c_void, // +0x64
    pub extension_callback_104: *mut core::ffi::c_void, // +0x68
    pub extension_callback_108: *mut core::ffi::c_void, // +0x6c
    pub _tail: [u8; 0x4], // 4
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_interconnect_app_info {
    pub package_name: *mut core::ffi::c_void, // +0x0
    pub display_name: *mut core::ffi::c_void, // +0x4
    pub icon_file: *mut core::ffi::c_void, // +0x8
    pub extra: *mut core::ffi::c_void, // +0xc
    pub fingerprint: [u8; 20], // +0x10
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct firmware_notification_message {
    pub message_id: u64, // +0x0
    pub repeat_count: u32, // +0x8
    pub title: *mut core::ffi::c_void, // +0xc
    pub source: *mut core::ffi::c_void, // +0x10
    pub body: *mut core::ffi::c_void, // +0x14
    pub auxiliary_text: *mut core::ffi::c_void, // +0x18
    pub small_icon_path: *mut core::ffi::c_void, // +0x1c
    pub large_icon_path: *mut core::ffi::c_void, // +0x20
    pub extension_text_36: *mut core::ffi::c_void, // +0x24
    pub extension_text_40: *mut core::ffi::c_void, // +0x28
    pub timestamp: u32, // +0x2c
    pub _pad_30: [u8; 0x8], // 8
    pub action_callback: *mut core::ffi::c_void, // +0x38
    pub action_context: u32, // +0x3c
    pub extension_64: u32, // +0x40
    pub extension_68: u32, // +0x44
    pub open_callback: *mut core::ffi::c_void, // +0x48
    pub destroy_callback: *mut core::ffi::c_void, // +0x4c
    pub start_reminder: u8, // +0x50
    pub flags_81: u8, // +0x51
    pub flags_82: u8, // +0x52
    pub _pad_53: [u8; 0x1], // 1
    pub callback_data: *mut core::ffi::c_void, // +0x54
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct service_object {
    pub enabled_state: u8, // +0x0
    pub _pad_1: [u8; 0x3], // 3
    pub name: *mut core::ffi::c_void, // +0x4
    pub service_id: u8, // +0x8
    pub profile_group: u8, // +0x9
    pub _pad_a: [u8; 0x1a], // 26
    pub startup_cb: *mut core::ffi::c_void, // +0x24
    pub _pad_28: [u8; 0x8], // 8
    pub startup_eligibility_cb: *mut core::ffi::c_void, // +0x30
    pub get_profile_cb: *mut core::ffi::c_void, // +0x34
    pub cleanup_cb: *mut core::ffi::c_void, // +0x38
    pub _tail: [u8; 0x4], // 4
}

pub type canopus_interconnect_send_done = extern "C" fn(*mut core::ffi::c_void, i32, *const canopus_interconnect_message, *mut core::ffi::c_void) -> ();
#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct canopus_interconnect_message {
    pub r#type: u8, // +0x0
    pub _pad_1: [u8; 0x3], // 3
    pub length: u32, // +0x4
    pub _pad_8: [u8; 0x8], // 8
    pub value: *mut core::ffi::c_void, // +0x10
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct ordered_app_entry {
    pub app_name: *mut core::ffi::c_void, // +0x0
    pub _pad_4: [u8; 0x4], // 4
    pub enabled: u8, // +0x8
    pub hidden: u8, // +0x9
    pub _tail: [u8; 0x6], // 6
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_struct {
    pub name: [u8; 128], // +0x0
    pub flags: u8, // +0x80
    pub _tail: [u8; 0x3], // 3
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_record {
    pub app_id: u16, // +0x0
    pub _pad_2: [u8; 0x2], // 2
    pub icon_handle: *mut core::ffi::c_void, // +0x4
    pub name: *mut core::ffi::c_void, // +0x8
    pub icon_name: *mut core::ffi::c_void, // +0xc
    pub _pad_10: [u8; 0x4], // 4
    pub flags: u8, // +0x14
    pub _tail: [u8; 0x3], // 3
}

#[repr(C, packed(4))]
#[derive(Copy, Clone, Debug)]
pub struct launcher_app_descriptor {
    pub registry_links: u64, // +0x0
    pub package_name: *mut core::ffi::c_void, // +0x8
    pub launcher_icon_resource: *mut core::ffi::c_void, // +0xc
    pub app_id: u16, // +0x10
    pub flags: u8, // +0x12
    pub _pad_13: [u8; 0x1], // 1
    pub owned_string_20: *mut core::ffi::c_void, // +0x14
    pub owned_string_24: *mut core::ffi::c_void, // +0x18
    pub launcher_metadata_callback: *mut core::ffi::c_void, // +0x1c
    pub _pad_20: [u8; 0x10], // 16
    pub page_registry: *mut core::ffi::c_void, // +0x30
    pub _pad_34: [u8; 0x8], // 8
    pub hidden_flags: u8, // +0x3c
    pub _tail: [u8; 0x3], // 3
}

// ---- runtime identity guard ----
/// Returns 0 when the running firmware matches this pack's
/// version + build identity, -1 otherwise. Call once before use.
pub fn canopus_identity_guard() -> i32 {
    const EXPECT_VERSION: &[u8] = b"3.101.036";
    const EXPECT_BUILD: &[u8] = b"CONBINE_LTALM078_T3.101.036_06242053";
    if !c_str_eq(0x0C0C0810, EXPECT_VERSION) { return -1; }
    if !c_str_eq(0x0C0C0850, EXPECT_BUILD) { return -1; }
    0
}

/// Compares a NUL-terminated string at `addr` to `expected`.
fn c_str_eq(addr: usize, expected: &[u8]) -> bool {
    let mut i = 0usize;
    while i <= expected.len() && i < 64 {
        let b = unsafe { *((addr + i) as *const u8) };
        if i < expected.len() {
            if b != expected[i] { return false; }
        } else {
            return b == 0;
        }
        i += 1;
    }
    false
}

// ---- typed firmware bindings (unsafe) ----
/// Recovered `app_install` at 0xca51a54. Thumb callable address 0xca51a55.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_app_install(a0: *const launcher_app_descriptor, a1: *const *const firmware_page_descriptor, a2: u32) -> i32 {
    let f: extern "C" fn(*const launcher_app_descriptor, *const *const firmware_page_descriptor, u32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0xca51a55usize)) };
    f(a0, a1, a2)
}

/// Recovered `bt_adapter_get_state` at 0x0C398DF0. Thumb callable address 0x0C398DF1.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_adapter_get_state(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C398DF1usize)) };
    f(a0)
}

/// Recovered `lvx_style_apply` at 0xc49eb80. Thumb callable address 0xc49eb81.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_style_apply(a0: *mut core::ffi::c_void, a1: *const core::ffi::c_void, a2: u32, a3: u32) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const core::ffi::c_void, u32, u32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0xc49eb81usize)) };
    f(a0, a1, a2, a3)
}

/// Recovered `lvx_msgbox_create` at 0xc4a93c0. Thumb callable address 0xc4a93c1.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_msgbox_create(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0xc4a93c1usize)) };
    f(a0, a1)
}

/// Recovered `lvx_page_content_create` at 0xca4e990. Thumb callable address 0xca4e991.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_page_content_create(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0xca4e991usize)) };
    f(a0)
}

/// Recovered `register_driver` at 0xc1a0d50. Thumb callable address 0xc1a0d51.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_register_driver(a0: *const u8, a1: *const core::ffi::c_void, a2: u32, a3: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*const u8, *const core::ffi::c_void, u32, *mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0xc1a0d51usize)) };
    f(a0, a1, a2, a3)
}

/// Recovered `app_lookup` at 0xca5107c. Thumb callable address 0xca5107d.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_app_lookup(a0: u16) -> *mut core::ffi::c_void {
    let f: extern "C" fn(u16) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0xca5107dusize)) };
    f(a0)
}

/// Recovered `write` at 0xc1c31c8. Thumb callable address 0xc1c31c9.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_write(a0: i32, a1: *const core::ffi::c_void, a2: u32) -> i32 {
    let f: extern "C" fn(i32, *const core::ffi::c_void, u32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0xc1c31c9usize)) };
    f(a0, a1, a2)
}

/// Recovered `bt_adapter_unregister` at 0x0C398D4C. Thumb callable address 0x0C398D4D.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_adapter_unregister(a0: *mut core::ffi::c_void, a1: u32) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, u32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C398D4Dusize)) };
    f(a0, a1)
}

/// Recovered `interconnect_connect` at 0x0C2D20F4. Thumb callable address 0x0C2D20F5.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_interconnect_connect(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void, a2: *const u8, a3: canopus_interconnect_recv_cb) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void, *const u8, canopus_interconnect_recv_cb) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C2D20F5usize)) };
    f(a0, a1, a2, a3)
}

/// Recovered `lvx_object_set_size` at 0xc588e78. Thumb callable address 0xc588e79.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_object_set_size(a0: *mut core::ffi::c_void, a1: i32, a2: i32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, i32, i32) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0xc588e79usize)) };
    f(a0, a1, a2);
}

/// Recovered `bt_adapter_get_scan_mode` at 0x0C39F068. Thumb callable address 0x0C39F069.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_adapter_get_scan_mode() -> i32 {
    let f: extern "C" fn() -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C39F069usize)) };
    f()
}

/// Recovered `lvx_page_title_create` at 0xc4a99ac. Thumb callable address 0xc4a99ad.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_page_title_create(a0: *mut core::ffi::c_void, a1: *const u8, a2: u32, a3: canopus_lvx_event_cb, a4: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, u32, canopus_lvx_event_cb, *mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0xc4a99adusize)) };
    f(a0, a1, a2, a3, a4)
}

/// Recovered `app_launcher_add` at 0xc4f2c4c. Thumb callable address 0xc4f2c4d.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_app_launcher_add(a0: u16) -> i32 {
    let f: extern "C" fn(u16) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0xc4f2c4dusize)) };
    f(a0)
}

/// Recovered `open` at 0xc1c15b0. Thumb callable address 0xc1c15b1.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_open(a0: *const u8, a1: i32) -> i32 {
    let f: extern "C" fn(*const u8, i32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0xc1c15b1usize)) };
    f(a0, a1)
}

/// Recovered `lvx_msgbox_set_content` at 0xc4a9418. Thumb callable address 0xc4a9419.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_msgbox_set_content(a0: *mut core::ffi::c_void, a1: u32, a2: *const u8, a3: *const u8, a4: *const u8, a5: *const core::ffi::c_void, a6: u32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, u32, *const u8, *const u8, *const u8, *const core::ffi::c_void, u32) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0xc4a9419usize)) };
    f(a0, a1, a2, a3, a4, a5, a6);
}

/// Recovered `interconnect_close` at 0x0C2D2258. Thumb callable address 0x0C2D2259.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_interconnect_close(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C2D2259usize)) };
    f(a0)
}

/// Recovered `quickapp_register_app` at 0x0C528390. Thumb callable address 0x0C528391.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_quickapp_register_app(a0: u16, a1: *const canopus_interconnect_app_info) -> i32 {
    let f: extern "C" fn(u16, *const canopus_interconnect_app_info) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C528391usize)) };
    f(a0, a1)
}

/// Recovered `bt_pair_display_reply` at 0x0C399860. Thumb callable address 0x0C399861.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_pair_display_reply(a0: *mut core::ffi::c_void, a1: *const u8, a2: i32, a3: i32) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, i32, i32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C399861usize)) };
    f(a0, a1, a2, a3)
}

/// Recovered `lv_obj_set_hidden` at 0xc5879b8. Thumb callable address 0xc5879b9.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lv_obj_set_hidden(a0: *mut core::ffi::c_void, a1: u32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, u32) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0xc5879b9usize)) };
    f(a0, a1);
}

/// Recovered `close` at 0xc1aab70. Thumb callable address 0xc1aab71.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_close(a0: i32) -> i32 {
    let f: extern "C" fn(i32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0xc1aab71usize)) };
    f(a0)
}

/// Recovered `page_goto` at 0xca53aa0. Thumb callable address 0xca53aa1.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_page_goto(a0: u32, a1: u32, a2: u32, a3: u32) -> i32 {
    let f: extern "C" fn(u32, u32, u32, u32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0xca53aa1usize)) };
    f(a0, a1, a2, a3)
}

/// Recovered `bt_adapter_register` at 0x0C398CE4. Thumb callable address 0x0C398CE5.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_adapter_register(a0: *mut core::ffi::c_void, a1: *const u32) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C398CE5usize)) };
    f(a0, a1)
}

/// Recovered `page_finish` at 0xca53130. Thumb callable address 0xca53131.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_page_finish(a0: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0xca53131usize)) };
    f(a0)
}

/// Recovered `lvx_list_item_update` at 0xc4a7bec. Thumb callable address 0xc4a7bed.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_list_item_update(a0: *mut core::ffi::c_void, a1: *const u8, a2: *const u8, a3: *const u8, a4: i32, a5: u8) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, *const u8, *const u8, i32, u8) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0xc4a7bedusize)) };
    f(a0, a1, a2, a3, a4, a5)
}

/// Recovered `lvx_list_row_trailing` at 0xc4a7f48. Thumb callable address 0xc4a7f49.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_list_row_trailing(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0xc4a7f49usize)) };
    f(a0)
}

/// Recovered `lv_obj_add_event_cb` at 0xc5881a8. Thumb callable address 0xc5881a9.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lv_obj_add_event_cb(a0: *mut core::ffi::c_void, a1: canopus_lvx_event_cb, a2: u32, a3: *mut core::ffi::c_void) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, canopus_lvx_event_cb, u32, *mut core::ffi::c_void) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0xc5881a9usize)) };
    f(a0, a1, a2, a3);
}

/// Recovered `lv_obj_align_to` at 0xc588500. Thumb callable address 0xc588501.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lv_obj_align_to(a0: *mut core::ffi::c_void, a1: *mut core::ffi::c_void, a2: u32, a3: i32, a4: i32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void, u32, i32, i32) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0xc588501usize)) };
    f(a0, a1, a2, a3, a4);
}

/// Recovered global `interconnect_loop` at 0x20121F80.
pub const canopus_fw_interconnect_loop: usize = 0x20121F80usize;

/// Recovered `read` at 0xc1c1e24. Thumb callable address 0xc1c1e25.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_read(a0: i32, a1: *mut core::ffi::c_void, a2: u32) -> i32 {
    let f: extern "C" fn(i32, *mut core::ffi::c_void, u32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0xc1c1e25usize)) };
    f(a0, a1, a2)
}

/// Recovered `lv_event_get_code` at 0xc588f58. Thumb callable address 0xc588f59.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lv_event_get_code(a0: *mut core::ffi::c_void) -> u32 {
    let f: extern "C" fn(*mut core::ffi::c_void) -> u32 = unsafe { core::mem::transmute(canopus_thumb_callable(0xc588f59usize)) };
    f(a0)
}

/// Recovered `lv_event_get_user_data` at 0xc588238. Thumb callable address 0xc588239.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lv_event_get_user_data(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0xc588239usize)) };
    f(a0)
}

/// Recovered `unregister_driver` at 0xc1a0e1c. Thumb callable address 0xc1a0e1d.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_unregister_driver(a0: *const u8) -> i32 {
    let f: extern "C" fn(*const u8) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0xc1a0e1dusize)) };
    f(a0)
}

/// Recovered `lvx_notification_insert_message` at 0xca81fb8. Thumb callable address 0xca81fb9.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_notification_insert_message(a0: *const firmware_notification_message) -> i32 {
    let f: extern "C" fn(*const firmware_notification_message) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0xca81fb9usize)) };
    f(a0)
}

/// Recovered `lvx_object_delete` at 0xc588ed8. Thumb callable address 0xc588ed9.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_object_delete(a0: *mut core::ffi::c_void) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0xc588ed9usize)) };
    f(a0);
}

/// Recovered `bt_adapter_get_instance` at 0x0CA28770. Thumb callable address 0x0CA28771.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_adapter_get_instance() -> *mut core::ffi::c_void {
    let f: extern "C" fn() -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0x0CA28771usize)) };
    f()
}

/// Recovered `lvx_label_set_text` at 0xc587f50. Thumb callable address 0xc587f51.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_label_set_text(a0: *mut core::ffi::c_void, a1: *const u8) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0xc587f51usize)) };
    f(a0, a1);
}

/// Recovered `lvx_label_create` at 0xc589060. Thumb callable address 0xc589061.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_label_create(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0xc589061usize)) };
    f(a0)
}

/// Recovered global `style_misans_demibold_32` at 0x2010A02C.
pub const canopus_fw_style_misans_demibold_32: usize = 0x2010A02Cusize;

/// Recovered `bt_get_pairing_state` at 0x0C39F948. Thumb callable address 0x0C39F949.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_get_pairing_state(a0: *const u8, a1: u32) -> u32 {
    let f: extern "C" fn(*const u8, u32) -> u32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C39F949usize)) };
    f(a0, a1)
}

/// Recovered `lvx_object_align` at 0xc587c10. Thumb callable address 0xc587c11.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_object_align(a0: *mut core::ffi::c_void, a1: u32, a2: i32, a3: i32) -> () {
    let f: extern "C" fn(*mut core::ffi::c_void, u32, i32, i32) -> () = unsafe { core::mem::transmute(canopus_thumb_callable(0xc587c11usize)) };
    f(a0, a1, a2, a3);
}

/// Recovered `bt_pair_request_reply` at 0x0C39989C. Thumb callable address 0x0C39989D.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_bt_pair_request_reply(a0: *mut core::ffi::c_void, a1: *const u8, a2: i32) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, i32) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C39989Dusize)) };
    f(a0, a1, a2)
}

/// Recovered `lvx_list_row_create` at 0xc52b78c. Thumb callable address 0xc52b78d.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_lvx_list_row_create(a0: *mut core::ffi::c_void, a1: *const u8, a2: *const u8, a3: u8) -> *mut core::ffi::c_void {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, *const u8, u8) -> *mut core::ffi::c_void = unsafe { core::mem::transmute(canopus_thumb_callable(0xc52b78dusize)) };
    f(a0, a1, a2, a3)
}

/// Recovered `clock_gettime` at 0xc1ec8b4. Thumb callable address 0xc1ec8b5.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_clock_gettime(a0: u32, a1: *const stock_timespec_t) -> i32 {
    let f: extern "C" fn(u32, *const stock_timespec_t) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0xc1ec8b5usize)) };
    f(a0, a1)
}

/// Recovered `interconnect_send` at 0x0C2D2184. Thumb callable address 0x0C2D2185.
#[allow(non_snake_case)]
#[allow(clippy::missing_safety_doc)]
pub unsafe fn canopus_fw_interconnect_send(a0: *mut core::ffi::c_void, a1: *const u8, a2: *const canopus_interconnect_message, a3: canopus_interconnect_send_done, a4: *mut core::ffi::c_void) -> i32 {
    let f: extern "C" fn(*mut core::ffi::c_void, *const u8, *const canopus_interconnect_message, canopus_interconnect_send_done, *mut core::ffi::c_void) -> i32 = unsafe { core::mem::transmute(canopus_thumb_callable(0x0C2D2185usize)) };
    f(a0, a1, a2, a3, a4)
}

// ---- excluded symbols ----
// app_launcher_data_init: restricted - not exported until context/ownership approved
// app_launcher_del: restricted - not exported until context/ownership approved
// bt_adapter_register_a2dp_callbacks: FORBIDDEN - no binding may ever be generated
// bt_adapter_register_hfp_ag_callbacks: FORBIDDEN - no binding may ever be generated
// bt_socket_server_receive: FORBIDDEN - no binding may ever be generated
// btsnoop_avdtp_recognizer: FORBIDDEN - no binding may ever be generated
// controller_crash_dump: FORBIDDEN - no binding may ever be generated
// driver_close_dispatch: restricted - not exported until context/ownership approved
// driver_ioctl_dispatch: restricted - not exported until context/ownership approved
// driver_open_dispatch: restricted - not exported until context/ownership approved
// driver_read_dispatch: restricted - not exported until context/ownership approved
// driver_write_dispatch: FORBIDDEN - no binding may ever be generated
// errno_location: restricted - not exported until context/ownership approved
// firmware_log: restricted - not exported until context/ownership approved
// heap_free: restricted - not exported until context/ownership approved
// heap_mallinfo: restricted - not exported until context/ownership approved
// heap_malloc: restricted - not exported until context/ownership approved
// heap_zalloc: restricted - not exported until context/ownership approved
// hfp_ag_connect: FORBIDDEN - no binding may ever be generated
// hfp_ag_disconnect: FORBIDDEN - no binding may ever be generated
// hidden_and_show_app_cb: restricted - not exported until context/ownership approved
// insmod: restricted - not exported until context/ownership approved
// lv_timer_create: restricted - not exported until context/ownership approved
// lv_timer_del: restricted - not exported until context/ownership approved
// modhandle: restricted - not exported until context/ownership approved
// offload_property_apply: FORBIDDEN - no binding may ever be generated
// page_navigator_open_page: FORBIDDEN - no binding may ever be generated
// protobuf_set_ordered_app_list: restricted - not exported until context/ownership approved
// pthread_create_internal: FORBIDDEN - no binding may ever be generated
// public_work_queue: FORBIDDEN - no binding may ever be generated
// register_blockdriver: restricted - not exported until context/ownership approved
// rename: restricted - not exported until context/ownership approved
// rmmod: restricted - not exported until context/ownership approved
// sem_post: restricted - not exported until context/ownership approved
// sem_trywait: restricted - not exported until context/ownership approved
// sem_wait: restricted - not exported until context/ownership approved
// service_manager_cleanup: FORBIDDEN - no binding may ever be generated
// service_manager_get_profile: restricted - not exported until context/ownership approved
// service_manager_register: restricted - not exported until context/ownership approved
// service_manager_shutdown: restricted - not exported until context/ownership approved
// service_manager_startup: restricted - not exported until context/ownership approved
// sport_titlebar_dispatch: FORBIDDEN - no binding may ever be generated
// sport_titlebar_lifecycle_reset: FORBIDDEN - no binding may ever be generated
// system_router_app_wrapper: FORBIDDEN - no binding may ever be generated
// system_router_get_pages_wrapper: FORBIDDEN - no binding may ever be generated
// system_router_page_record_wrapper: FORBIDDEN - no binding may ever be generated
// unlink: restricted - not exported until context/ownership approved
// unregister_blockdriver: restricted - not exported until context/ownership approved
// vendor_hci_transport_register: FORBIDDEN - no binding may ever be generated
// watchface_manager_delete_watchface: restricted - not exported until context/ownership approved

