// Generated by tools/generate_target_private_symbols.py. DO NOT EDIT.
//
// target_id: xiaomi-band-11-4.100.108
// firmware_sha256: 9315ca353f624cec25dfcfc98a95ba959e2d7b24573bf1d6adf16ea10341bd99
// Source: targets/<target-id>/symbols/*.json.

#![allow(dead_code)]
#![allow(clippy::missing_safety_doc)]

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub struct TargetPrivateSymbolRecord {
    pub name: &'static str,
    pub kind: &'static str,
    pub entry: usize,
    pub callable: usize,
    pub status: &'static str,
    pub policy: &'static str,
    pub prototype: &'static str,
}

pub const TARGET_ID: &str = "xiaomi-band-11-4.100.108";
pub const FIRMWARE_SHA256: &str =
    "9315ca353f624cec25dfcfc98a95ba959e2d7b24573bf1d6adf16ea10341bd99";

pub const RECORDS: &[TargetPrivateSymbolRecord] = &[
    TargetPrivateSymbolRecord {
        name: "page_finish",
        kind: "function",
        entry: 0xc4669e8usize,
        callable: 0xc4669e9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int32_t(void *page_descriptor)",
    },
    TargetPrivateSymbolRecord {
        name: "page_goto",
        kind: "function",
        entry: 0xc55ad88usize,
        callable: 0xc55ad89usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int32_t(uint32_t page_key, uint32_t start_data, uint32_t param, uint32_t callbacks)",
    },
    TargetPrivateSymbolRecord {
        name: "page_navigator_open_page",
        kind: "function",
        entry: 0xc633724usize,
        callable: 0xc633725usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "",
    },
    TargetPrivateSymbolRecord {
        name: "system_router_app_wrapper",
        kind: "function",
        entry: 0xc45aac6usize,
        callable: 0xc45aac7usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "",
    },
    TargetPrivateSymbolRecord {
        name: "system_router_get_pages_wrapper",
        kind: "function",
        entry: 0xc8dbc88usize,
        callable: 0xc8dbc89usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "",
    },
    TargetPrivateSymbolRecord {
        name: "app_install",
        kind: "function",
        entry: 0xc6a6bf8usize,
        callable: 0xc6a6bf9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(const launcher_app_descriptor *, const firmware_page_descriptor *const *, uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_adapter_get_instance",
        kind: "function",
        entry: 0xc56ad98usize,
        callable: 0xc56ad99usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *()",
    },
    TargetPrivateSymbolRecord {
        name: "bt_adapter_get_scan_mode",
        kind: "function",
        entry: 0xc6668e8usize,
        callable: 0xc6668e9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int32()",
    },
    TargetPrivateSymbolRecord {
        name: "bt_adapter_get_state",
        kind: "function",
        entry: 0xc469f04usize,
        callable: 0xc469f05usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int32(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_adapter_register",
        kind: "function",
        entry: 0xc469e46usize,
        callable: 0xc469e47usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int32(void *, const uint32_t *)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_adapter_unregister",
        kind: "function",
        entry: 0xc469eb0usize,
        callable: 0xc469eb1usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int32(void *, uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_get_pairing_state",
        kind: "function",
        entry: 0xc43e7b6usize,
        callable: 0xc43e7b7usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "uint32(const uint8_t *, uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_l2cap_connect",
        kind: "function",
        entry: 0xc3a8e44usize,
        callable: 0xc3a8e45usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "uint32_t(const void *)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_pair_display_reply",
        kind: "function",
        entry: 0xc46a8aausize,
        callable: 0xc46a8abusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int32(void *, const uint8_t *, int32_t, int32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_pair_request_reply",
        kind: "function",
        entry: 0xc46a47cusize,
        callable: 0xc46a47dusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int32(void *, const uint8_t *, int32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "core_bt_pair_request_callback",
        kind: "function",
        entry: 0xc4fbbe4usize,
        callable: 0xc4fbbe5usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *, const uint8_t *)",
    },
    TargetPrivateSymbolRecord {
        name: "offload_property_apply",
        kind: "function",
        entry: 0xc4681d8usize,
        callable: 0xc4681d9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_adapter_register_a2dp_callbacks",
        kind: "function",
        entry: 0xc8a7be4usize,
        callable: 0xc8a7be5usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *, const void *)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_adapter_register_hfp_ag_callbacks",
        kind: "function",
        entry: 0xc8a79c0usize,
        callable: 0xc8a79c1usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *, const void *)",
    },
    TargetPrivateSymbolRecord {
        name: "hfp_ag_connect",
        kind: "function",
        entry: 0xc46b890usize,
        callable: 0xc46b891usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *, const void *)",
    },
    TargetPrivateSymbolRecord {
        name: "hfp_ag_disconnect",
        kind: "function",
        entry: 0xc536510usize,
        callable: 0xc536511usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *, const void *)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_socket_server_receive",
        kind: "function",
        entry: 0xc54a65cusize,
        callable: 0xc54a65dusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "internal",
    },
    TargetPrivateSymbolRecord {
        name: "btsnoop_avdtp_recognizer",
        kind: "function",
        entry: 0xc4765e8usize,
        callable: 0xc4765e9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "internal",
    },
    TargetPrivateSymbolRecord {
        name: "controller_crash_dump",
        kind: "function",
        entry: 0xc926ee8usize,
        callable: 0xc926ee9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void)",
    },
    TargetPrivateSymbolRecord {
        name: "vendor_hci_transport_register",
        kind: "function",
        entry: 0xc6c4280usize,
        callable: 0xc6c4281usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(int, char)",
    },
    TargetPrivateSymbolRecord {
        name: "app_launcher_add",
        kind: "function",
        entry: 0xc3c2cccusize,
        callable: 0xc3c2ccdusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(uint16_t app_id)",
    },
    TargetPrivateSymbolRecord {
        name: "app_launcher_data_init",
        kind: "function",
        entry: 0xc344628usize,
        callable: 0xc344629usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void)",
    },
    TargetPrivateSymbolRecord {
        name: "app_launcher_del",
        kind: "function",
        entry: 0xc573204usize,
        callable: 0xc573205usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(uint16_t)",
    },
    TargetPrivateSymbolRecord {
        name: "hidden_and_show_app_cb",
        kind: "function",
        entry: 0xc545e50usize,
        callable: 0xc545e51usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(launcher_msg_t *)",
    },
    TargetPrivateSymbolRecord {
        name: "protobuf_set_ordered_app_list",
        kind: "function",
        entry: 0xc5490b4usize,
        callable: 0xc5490b5usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(ordered_app_list_t *)",
    },
    TargetPrivateSymbolRecord {
        name: "interconnect_close",
        kind: "function",
        entry: 0xc902a9cusize,
        callable: 0xc902a9dusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "interconnect_connect",
        kind: "function",
        entry: 0xc3f4230usize,
        callable: 0xc3f4231usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *, void *, const char *, canopus_interconnect_recv_cb)",
    },
    TargetPrivateSymbolRecord {
        name: "interconnect_send",
        kind: "function",
        entry: 0xc368810usize,
        callable: 0xc368811usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *, const char *, const canopus_interconnect_message *, canopus_interconnect_send_done, void *)",
    },
    TargetPrivateSymbolRecord {
        name: "quickapp_register_app",
        kind: "function",
        entry: 0xc528c5cusize,
        callable: 0xc528c5dusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(uint16_t, const canopus_interconnect_app_info *)",
    },
    TargetPrivateSymbolRecord {
        name: "thirdparty_submit_message_content",
        kind: "function",
        entry: 0xc93d2b0usize,
        callable: 0xc93d2b1usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(const void *, uint32_t, uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "insmod",
        kind: "function",
        entry: 0xc349104usize,
        callable: 0xc349105usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(const char *, const char *)",
    },
    TargetPrivateSymbolRecord {
        name: "modhandle",
        kind: "function",
        entry: 0xc36d578usize,
        callable: 0xc36d579usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(const char *)",
    },
    TargetPrivateSymbolRecord {
        name: "rmmod",
        kind: "function",
        entry: 0xc32a660usize,
        callable: 0xc32a661usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_notification_insert_message",
        kind: "function",
        entry: 0xc37269cusize,
        callable: 0xc37269dusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(const firmware_notification_message *message)",
    },
    TargetPrivateSymbolRecord {
        name: "clock_gettime",
        kind: "function",
        entry: 0xc491644usize,
        callable: 0xc491645usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(uint32_t, stock_timespec_t *)",
    },
    TargetPrivateSymbolRecord {
        name: "close",
        kind: "function",
        entry: 0xc402afcusize,
        callable: 0xc402afdusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(int)",
    },
    TargetPrivateSymbolRecord {
        name: "driver_close_dispatch",
        kind: "function",
        entry: 0xc53b4a0usize,
        callable: 0xc53b4a1usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(file *) via fops+0x04",
    },
    TargetPrivateSymbolRecord {
        name: "driver_ioctl_dispatch",
        kind: "function",
        entry: 0xc7ceec0usize,
        callable: 0xc7ceec1usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(file *, int, uintptr_t) via fops+0x14",
    },
    TargetPrivateSymbolRecord {
        name: "driver_open_dispatch",
        kind: "function",
        entry: 0xc4454f4usize,
        callable: 0xc4454f5usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(file *) via fops+0x00",
    },
    TargetPrivateSymbolRecord {
        name: "driver_read_dispatch",
        kind: "function",
        entry: 0xc33b708usize,
        callable: 0xc33b709usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int32(file *, void *, uint32_t) via fops+0x08",
    },
    TargetPrivateSymbolRecord {
        name: "errno_location",
        kind: "function",
        entry: 0xc349378usize,
        callable: 0xc349379usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int *(void)",
    },
    TargetPrivateSymbolRecord {
        name: "firmware_log",
        kind: "function",
        entry: 0xc36c424usize,
        callable: 0xc36c425usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(int, const char *, ...)",
    },
    TargetPrivateSymbolRecord {
        name: "heap_free",
        kind: "function",
        entry: 0xc79d992usize,
        callable: 0xc79d993usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "heap_mallinfo",
        kind: "function",
        entry: 0xc360004usize,
        callable: 0xc360005usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "heap_malloc",
        kind: "function",
        entry: 0xc725aa4usize,
        callable: 0xc725aa5usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "heap_zalloc",
        kind: "function",
        entry: 0xc483e94usize,
        callable: 0xc483e95usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "ioctl",
        kind: "function",
        entry: 0xc4e6d6cusize,
        callable: 0xc4e6d6dusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int32_t(int32_t, uint32_t, uintptr_t)",
    },
    TargetPrivateSymbolRecord {
        name: "lseek",
        kind: "function",
        entry: 0xc371614usize,
        callable: 0xc371615usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int64_t(int, int64_t, int)",
    },
    TargetPrivateSymbolRecord {
        name: "open",
        kind: "function",
        entry: 0xc6a1ea8usize,
        callable: 0xc6a1ea9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(const char *, int)",
    },
    TargetPrivateSymbolRecord {
        name: "pthread_create_internal",
        kind: "function",
        entry: 0xc916a98usize,
        callable: 0xc916a99usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "",
    },
    TargetPrivateSymbolRecord {
        name: "read",
        kind: "function",
        entry: 0xc7a8280usize,
        callable: 0xc7a8281usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int32(int, void *, uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "register_blockdriver",
        kind: "function",
        entry: 0xc46bd12usize,
        callable: 0xc46bd13usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(const char *, const void *, uint32_t, void *)",
    },
    TargetPrivateSymbolRecord {
        name: "register_driver",
        kind: "function",
        entry: 0xc46bdb6usize,
        callable: 0xc46bdb7usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(const char *, const void *, uint32_t, void *)",
    },
    TargetPrivateSymbolRecord {
        name: "rename",
        kind: "function",
        entry: 0xc33d6c4usize,
        callable: 0xc33d6c5usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(const char *, const char *)",
    },
    TargetPrivateSymbolRecord {
        name: "sem_post",
        kind: "function",
        entry: 0xc359980usize,
        callable: 0xc359981usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "sem_trywait",
        kind: "function",
        entry: 0xc6f7954usize,
        callable: 0xc6f7955usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "sem_wait",
        kind: "function",
        entry: 0xc359510usize,
        callable: 0xc359511usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "unlink",
        kind: "function",
        entry: 0xc33caf8usize,
        callable: 0xc33caf9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(const char *)",
    },
    TargetPrivateSymbolRecord {
        name: "unregister_blockdriver",
        kind: "function",
        entry: 0xc7cff4eusize,
        callable: 0xc7cff4fusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(const char *)",
    },
    TargetPrivateSymbolRecord {
        name: "unregister_driver",
        kind: "function",
        entry: 0xc663914usize,
        callable: 0xc663915usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(const char *)",
    },
    TargetPrivateSymbolRecord {
        name: "write",
        kind: "function",
        entry: 0xc33d438usize,
        callable: 0xc33d439usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int32(int, const void *, uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_adapter_set_scan_mode",
        kind: "function",
        entry: 0xc7842d8usize,
        callable: 0xc7842d9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(int, int)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_alloc",
        kind: "function",
        entry: 0xc36cfb4usize,
        callable: 0xc36cfb5usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_buffer_new",
        kind: "function",
        entry: 0xc46c476usize,
        callable: 0xc46c477usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(uint16_t, uint16_t)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_create_bond_private",
        kind: "function",
        entry: 0xc342662usize,
        callable: 0xc342663usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(const uint8_t *, uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_discovery_start",
        kind: "function",
        entry: 0xc521968usize,
        callable: 0xc521969usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *, int)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_discovery_stop",
        kind: "function",
        entry: 0xc46a316usize,
        callable: 0xc46a317usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_free",
        kind: "function",
        entry: 0xc36cfaausize,
        callable: 0xc36cfabusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_get_bond_state",
        kind: "function",
        entry: 0xc73be80usize,
        callable: 0xc73be81usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "uint32_t(const uint8_t *)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_l2cap_disconnect",
        kind: "function",
        entry: 0xc493850usize,
        callable: 0xc493851usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(const void *)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_l2cap_submit_cid",
        kind: "function",
        entry: 0xc70ea00usize,
        callable: 0xc70ea01usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *, uint16_t)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_queue_external",
        kind: "function",
        entry: 0xc551518usize,
        callable: 0xc551519usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *, void *, void *, void *, uint8_t)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_queue_free",
        kind: "function",
        entry: 0xc328b04usize,
        callable: 0xc328b05usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_remove_bond_private",
        kind: "function",
        entry: 0xc3d5128usize,
        callable: 0xc3d5129usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(const uint8_t *, uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_timer_add",
        kind: "function",
        entry: 0xc46be6eusize,
        callable: 0xc46be6fusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "uint32_t(void *, uint32_t, uint8_t, void *, void *, const uint8_t *, uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "bt_timer_cancel",
        kind: "function",
        entry: 0xc466eb0usize,
        callable: 0xc466eb1usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(uint32_t *)",
    },
    TargetPrivateSymbolRecord {
        name: "gap_host_stock_receive",
        kind: "function",
        entry: 0xc85eed0usize,
        callable: 0xc85eed1usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *, uint8_t *, int)",
    },
    TargetPrivateSymbolRecord {
        name: "sdp_builder_create",
        kind: "function",
        entry: 0xc88093cusize,
        callable: 0xc88093dusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(uint32_t, uint16_t, uint16_t, uint8_t, const uint8_t *)",
    },
    TargetPrivateSymbolRecord {
        name: "sdp_commit",
        kind: "function",
        entry: 0xc480710usize,
        callable: 0xc480711usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "uint32_t(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "sdp_set_raw_attribute",
        kind: "function",
        entry: 0xc875b1cusize,
        callable: 0xc875b1dusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "uint8_t *(void *, uint16_t, uint16_t, uint16_t, const void *)",
    },
    TargetPrivateSymbolRecord {
        name: "sdp_unregister",
        kind: "function",
        entry: 0xc6c3f78usize,
        callable: 0xc6c3f79usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "app_lookup",
        kind: "function",
        entry: 0xc5c0528usize,
        callable: 0xc5c0529usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(uint16_t app_id)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_label_create",
        kind: "function",
        entry: 0xc7208c8usize,
        callable: 0xc7208c9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(void *parent)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_label_set_text",
        kind: "function",
        entry: 0xc0f77e8usize,
        callable: 0xc0f77e9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void(void *label, const char *text)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_list_row_create",
        kind: "function",
        entry: 0xc785048usize,
        callable: 0xc785049usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(void *parent, const char *primary, const char *secondary, uint8_t trailing)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_list_row_trailing",
        kind: "function",
        entry: 0xc3a0568usize,
        callable: 0xc3a0569usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(void *row)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_msgbox_create",
        kind: "function",
        entry: 0xc43e84cusize,
        callable: 0xc43e84dusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(void *parent, void *extra)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_msgbox_set_content",
        kind: "function",
        entry: 0xc566ebcusize,
        callable: 0xc566ebdusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void(void *box, uint32_t mode, const char *title, const char *body, const char *aux, const void *buttons, uint32_t count)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_object_align",
        kind: "function",
        entry: 0xc7209d8usize,
        callable: 0xc7209d9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void(void *object, uint32_t align, int32_t x, int32_t y)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_object_delete",
        kind: "function",
        entry: 0xc720890usize,
        callable: 0xc720891usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void(void *object)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_object_set_size",
        kind: "function",
        entry: 0xc720d08usize,
        callable: 0xc720d09usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void(void *object, int32_t width, int32_t height)",
    },
    TargetPrivateSymbolRecord {
        name: "service_manager_cleanup",
        kind: "function",
        entry: 0xc5b2fc0usize,
        callable: 0xc5b2fc1usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(int)",
    },
    TargetPrivateSymbolRecord {
        name: "service_manager_get_profile",
        kind: "function",
        entry: 0xc54b96cusize,
        callable: 0xc54b96dusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "service_manager_register",
        kind: "function",
        entry: 0xc5740b8usize,
        callable: 0xc5740b9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "service_manager_shutdown",
        kind: "function",
        entry: 0xc90856cusize,
        callable: 0xc90856dusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(int)",
    },
    TargetPrivateSymbolRecord {
        name: "service_manager_startup",
        kind: "function",
        entry: 0xc9085ccusize,
        callable: 0xc9085cdusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(int)",
    },
    TargetPrivateSymbolRecord {
        name: "lv_bar_create",
        kind: "function",
        entry: 0xc7207c8usize,
        callable: 0xc7207c9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "lv_bar_set_range",
        kind: "function",
        entry: 0xc0f7700usize,
        callable: 0xc0f7701usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void(void *, int32_t, int32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "lv_bar_set_value",
        kind: "function",
        entry: 0xc720cd8usize,
        callable: 0xc720cd9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void(void *, int32_t, uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "lv_event_get_code",
        kind: "function",
        entry: 0xc720780usize,
        callable: 0xc720781usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "uint32_t(void *event)",
    },
    TargetPrivateSymbolRecord {
        name: "lv_event_get_user_data",
        kind: "function",
        entry: 0xc720980usize,
        callable: 0xc720981usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "lv_image_create",
        kind: "function",
        entry: 0xc5d71c0usize,
        callable: 0xc5d71c1usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "lv_image_set_src",
        kind: "function",
        entry: 0xc3b2a5cusize,
        callable: 0xc3b2a5dusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void(void *, const void *)",
    },
    TargetPrivateSymbolRecord {
        name: "lv_obj_add_event_cb",
        kind: "function",
        entry: 0xc720db8usize,
        callable: 0xc720db9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void(void *, canopus_lvx_event_cb, uint32_t, void *)",
    },
    TargetPrivateSymbolRecord {
        name: "lv_obj_align_to",
        kind: "function",
        entry: 0xc7209c8usize,
        callable: 0xc7209c9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void(void *, void *, uint32_t, int32_t, int32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "lv_obj_move_to_index",
        kind: "function",
        entry: 0xc720df8usize,
        callable: 0xc720df9usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void (void *, int32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "lv_obj_set_hidden",
        kind: "function",
        entry: 0xc7208d0usize,
        callable: 0xc7208d1usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void(void *, uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "lv_obj_set_style_bg_opa",
        kind: "function",
        entry: 0xc6c2d94usize,
        callable: 0xc6c2d95usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void (void *, uint32_t, uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "lv_timer_create",
        kind: "function",
        entry: 0xc720808usize,
        callable: 0xc720809usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(canopus_lvx_event_cb, uint32_t, void *)",
    },
    TargetPrivateSymbolRecord {
        name: "lv_timer_del",
        kind: "function",
        entry: 0xc720c30usize,
        callable: 0xc720c31usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_image_set_scale",
        kind: "function",
        entry: 0xc3ae24eusize,
        callable: 0xc3ae24fusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void(void *, int32_t, int32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_list_item_update",
        kind: "function",
        entry: 0xc3dbd8cusize,
        callable: 0xc3dbd8dusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *, const char *, const char *, const char *, int32_t, uint8_t)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_object_add_flag",
        kind: "function",
        entry: 0xc720b50usize,
        callable: 0xc720b51usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void(void *, uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_page_content_create",
        kind: "function",
        entry: 0xc68f860usize,
        callable: 0xc68f861usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(void *)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_page_title_create",
        kind: "function",
        entry: 0xc89892cusize,
        callable: 0xc89892dusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "void *(void *, const char *, uint32_t, canopus_lvx_event_cb, void *)",
    },
    TargetPrivateSymbolRecord {
        name: "lvx_style_apply",
        kind: "function",
        entry: 0xc636da4usize,
        callable: 0xc636da5usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(void *, const void *, uint32_t, uint32_t)",
    },
    TargetPrivateSymbolRecord {
        name: "sport_titlebar_dispatch",
        kind: "function",
        entry: 0xc54efdcusize,
        callable: 0xc54efddusize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "",
    },
    TargetPrivateSymbolRecord {
        name: "watchface_manager_delete_watchface",
        kind: "function",
        entry: 0xc6c1564usize,
        callable: 0xc6c1565usize,
        status: "STATIC_RECOVERED",
        policy: "native-full-trust",
        prototype: "int(const char *)",
    },
];

pub const PAGE_FINISH_ENTRY: usize = 0xc4669e8usize;
pub const PAGE_FINISH_CALLABLE: usize = 0xc4669e9usize;
pub const PAGE_GOTO_ENTRY: usize = 0xc55ad88usize;
pub const PAGE_GOTO_CALLABLE: usize = 0xc55ad89usize;
pub const PAGE_NAVIGATOR_OPEN_PAGE_ENTRY: usize = 0xc633724usize;
pub const PAGE_NAVIGATOR_OPEN_PAGE_CALLABLE: usize = 0xc633725usize;
pub const SYSTEM_ROUTER_APP_WRAPPER_ENTRY: usize = 0xc45aac6usize;
pub const SYSTEM_ROUTER_APP_WRAPPER_CALLABLE: usize = 0xc45aac7usize;
pub const SYSTEM_ROUTER_GET_PAGES_WRAPPER_ENTRY: usize = 0xc8dbc88usize;
pub const SYSTEM_ROUTER_GET_PAGES_WRAPPER_CALLABLE: usize = 0xc8dbc89usize;
pub const APP_INSTALL_ENTRY: usize = 0xc6a6bf8usize;
pub const APP_INSTALL_CALLABLE: usize = 0xc6a6bf9usize;
pub const BT_ADAPTER_GET_INSTANCE_ENTRY: usize = 0xc56ad98usize;
pub const BT_ADAPTER_GET_INSTANCE_CALLABLE: usize = 0xc56ad99usize;
pub const BT_ADAPTER_GET_SCAN_MODE_ENTRY: usize = 0xc6668e8usize;
pub const BT_ADAPTER_GET_SCAN_MODE_CALLABLE: usize = 0xc6668e9usize;
pub const BT_ADAPTER_GET_STATE_ENTRY: usize = 0xc469f04usize;
pub const BT_ADAPTER_GET_STATE_CALLABLE: usize = 0xc469f05usize;
pub const BT_ADAPTER_REGISTER_ENTRY: usize = 0xc469e46usize;
pub const BT_ADAPTER_REGISTER_CALLABLE: usize = 0xc469e47usize;
pub const BT_ADAPTER_UNREGISTER_ENTRY: usize = 0xc469eb0usize;
pub const BT_ADAPTER_UNREGISTER_CALLABLE: usize = 0xc469eb1usize;
pub const BT_GET_PAIRING_STATE_ENTRY: usize = 0xc43e7b6usize;
pub const BT_GET_PAIRING_STATE_CALLABLE: usize = 0xc43e7b7usize;
pub const BT_L2CAP_CONNECT_ENTRY: usize = 0xc3a8e44usize;
pub const BT_L2CAP_CONNECT_CALLABLE: usize = 0xc3a8e45usize;
pub const BT_PAIR_DISPLAY_REPLY_ENTRY: usize = 0xc46a8aausize;
pub const BT_PAIR_DISPLAY_REPLY_CALLABLE: usize = 0xc46a8abusize;
pub const BT_PAIR_REQUEST_REPLY_ENTRY: usize = 0xc46a47cusize;
pub const BT_PAIR_REQUEST_REPLY_CALLABLE: usize = 0xc46a47dusize;
pub const CORE_BT_PAIR_REQUEST_CALLBACK_ENTRY: usize = 0xc4fbbe4usize;
pub const CORE_BT_PAIR_REQUEST_CALLBACK_CALLABLE: usize = 0xc4fbbe5usize;
pub const OFFLOAD_PROPERTY_APPLY_ENTRY: usize = 0xc4681d8usize;
pub const OFFLOAD_PROPERTY_APPLY_CALLABLE: usize = 0xc4681d9usize;
pub const BT_ADAPTER_REGISTER_A2DP_CALLBACKS_ENTRY: usize = 0xc8a7be4usize;
pub const BT_ADAPTER_REGISTER_A2DP_CALLBACKS_CALLABLE: usize = 0xc8a7be5usize;
pub const BT_ADAPTER_REGISTER_HFP_AG_CALLBACKS_ENTRY: usize = 0xc8a79c0usize;
pub const BT_ADAPTER_REGISTER_HFP_AG_CALLBACKS_CALLABLE: usize = 0xc8a79c1usize;
pub const HFP_AG_CONNECT_ENTRY: usize = 0xc46b890usize;
pub const HFP_AG_CONNECT_CALLABLE: usize = 0xc46b891usize;
pub const HFP_AG_DISCONNECT_ENTRY: usize = 0xc536510usize;
pub const HFP_AG_DISCONNECT_CALLABLE: usize = 0xc536511usize;
pub const BT_SOCKET_SERVER_RECEIVE_ENTRY: usize = 0xc54a65cusize;
pub const BT_SOCKET_SERVER_RECEIVE_CALLABLE: usize = 0xc54a65dusize;
pub const BTSNOOP_AVDTP_RECOGNIZER_ENTRY: usize = 0xc4765e8usize;
pub const BTSNOOP_AVDTP_RECOGNIZER_CALLABLE: usize = 0xc4765e9usize;
pub const CONTROLLER_CRASH_DUMP_ENTRY: usize = 0xc926ee8usize;
pub const CONTROLLER_CRASH_DUMP_CALLABLE: usize = 0xc926ee9usize;
pub const VENDOR_HCI_TRANSPORT_REGISTER_ENTRY: usize = 0xc6c4280usize;
pub const VENDOR_HCI_TRANSPORT_REGISTER_CALLABLE: usize = 0xc6c4281usize;
pub const APP_LAUNCHER_ADD_ENTRY: usize = 0xc3c2cccusize;
pub const APP_LAUNCHER_ADD_CALLABLE: usize = 0xc3c2ccdusize;
pub const APP_LAUNCHER_DATA_INIT_ENTRY: usize = 0xc344628usize;
pub const APP_LAUNCHER_DATA_INIT_CALLABLE: usize = 0xc344629usize;
pub const APP_LAUNCHER_DEL_ENTRY: usize = 0xc573204usize;
pub const APP_LAUNCHER_DEL_CALLABLE: usize = 0xc573205usize;
pub const HIDDEN_AND_SHOW_APP_CB_ENTRY: usize = 0xc545e50usize;
pub const HIDDEN_AND_SHOW_APP_CB_CALLABLE: usize = 0xc545e51usize;
pub const PROTOBUF_SET_ORDERED_APP_LIST_ENTRY: usize = 0xc5490b4usize;
pub const PROTOBUF_SET_ORDERED_APP_LIST_CALLABLE: usize = 0xc5490b5usize;
pub const INTERCONNECT_CLOSE_ENTRY: usize = 0xc902a9cusize;
pub const INTERCONNECT_CLOSE_CALLABLE: usize = 0xc902a9dusize;
pub const INTERCONNECT_CONNECT_ENTRY: usize = 0xc3f4230usize;
pub const INTERCONNECT_CONNECT_CALLABLE: usize = 0xc3f4231usize;
pub const INTERCONNECT_SEND_ENTRY: usize = 0xc368810usize;
pub const INTERCONNECT_SEND_CALLABLE: usize = 0xc368811usize;
pub const QUICKAPP_REGISTER_APP_ENTRY: usize = 0xc528c5cusize;
pub const QUICKAPP_REGISTER_APP_CALLABLE: usize = 0xc528c5dusize;
pub const THIRDPARTY_SUBMIT_MESSAGE_CONTENT_ENTRY: usize = 0xc93d2b0usize;
pub const THIRDPARTY_SUBMIT_MESSAGE_CONTENT_CALLABLE: usize = 0xc93d2b1usize;
pub const INSMOD_ENTRY: usize = 0xc349104usize;
pub const INSMOD_CALLABLE: usize = 0xc349105usize;
pub const MODHANDLE_ENTRY: usize = 0xc36d578usize;
pub const MODHANDLE_CALLABLE: usize = 0xc36d579usize;
pub const RMMOD_ENTRY: usize = 0xc32a660usize;
pub const RMMOD_CALLABLE: usize = 0xc32a661usize;
pub const LVX_NOTIFICATION_INSERT_MESSAGE_ENTRY: usize = 0xc37269cusize;
pub const LVX_NOTIFICATION_INSERT_MESSAGE_CALLABLE: usize = 0xc37269dusize;
pub const CLOCK_GETTIME_ENTRY: usize = 0xc491644usize;
pub const CLOCK_GETTIME_CALLABLE: usize = 0xc491645usize;
pub const CLOSE_ENTRY: usize = 0xc402afcusize;
pub const CLOSE_CALLABLE: usize = 0xc402afdusize;
pub const DRIVER_CLOSE_DISPATCH_ENTRY: usize = 0xc53b4a0usize;
pub const DRIVER_CLOSE_DISPATCH_CALLABLE: usize = 0xc53b4a1usize;
pub const DRIVER_IOCTL_DISPATCH_ENTRY: usize = 0xc7ceec0usize;
pub const DRIVER_IOCTL_DISPATCH_CALLABLE: usize = 0xc7ceec1usize;
pub const DRIVER_OPEN_DISPATCH_ENTRY: usize = 0xc4454f4usize;
pub const DRIVER_OPEN_DISPATCH_CALLABLE: usize = 0xc4454f5usize;
pub const DRIVER_READ_DISPATCH_ENTRY: usize = 0xc33b708usize;
pub const DRIVER_READ_DISPATCH_CALLABLE: usize = 0xc33b709usize;
pub const ERRNO_LOCATION_ENTRY: usize = 0xc349378usize;
pub const ERRNO_LOCATION_CALLABLE: usize = 0xc349379usize;
pub const FIRMWARE_LOG_ENTRY: usize = 0xc36c424usize;
pub const FIRMWARE_LOG_CALLABLE: usize = 0xc36c425usize;
pub const HEAP_FREE_ENTRY: usize = 0xc79d992usize;
pub const HEAP_FREE_CALLABLE: usize = 0xc79d993usize;
pub const HEAP_MALLINFO_ENTRY: usize = 0xc360004usize;
pub const HEAP_MALLINFO_CALLABLE: usize = 0xc360005usize;
pub const HEAP_MALLOC_ENTRY: usize = 0xc725aa4usize;
pub const HEAP_MALLOC_CALLABLE: usize = 0xc725aa5usize;
pub const HEAP_ZALLOC_ENTRY: usize = 0xc483e94usize;
pub const HEAP_ZALLOC_CALLABLE: usize = 0xc483e95usize;
pub const IOCTL_ENTRY: usize = 0xc4e6d6cusize;
pub const IOCTL_CALLABLE: usize = 0xc4e6d6dusize;
pub const LSEEK_ENTRY: usize = 0xc371614usize;
pub const LSEEK_CALLABLE: usize = 0xc371615usize;
pub const OPEN_ENTRY: usize = 0xc6a1ea8usize;
pub const OPEN_CALLABLE: usize = 0xc6a1ea9usize;
pub const PTHREAD_CREATE_INTERNAL_ENTRY: usize = 0xc916a98usize;
pub const PTHREAD_CREATE_INTERNAL_CALLABLE: usize = 0xc916a99usize;
pub const READ_ENTRY: usize = 0xc7a8280usize;
pub const READ_CALLABLE: usize = 0xc7a8281usize;
pub const REGISTER_BLOCKDRIVER_ENTRY: usize = 0xc46bd12usize;
pub const REGISTER_BLOCKDRIVER_CALLABLE: usize = 0xc46bd13usize;
pub const REGISTER_DRIVER_ENTRY: usize = 0xc46bdb6usize;
pub const REGISTER_DRIVER_CALLABLE: usize = 0xc46bdb7usize;
pub const RENAME_ENTRY: usize = 0xc33d6c4usize;
pub const RENAME_CALLABLE: usize = 0xc33d6c5usize;
pub const SEM_POST_ENTRY: usize = 0xc359980usize;
pub const SEM_POST_CALLABLE: usize = 0xc359981usize;
pub const SEM_TRYWAIT_ENTRY: usize = 0xc6f7954usize;
pub const SEM_TRYWAIT_CALLABLE: usize = 0xc6f7955usize;
pub const SEM_WAIT_ENTRY: usize = 0xc359510usize;
pub const SEM_WAIT_CALLABLE: usize = 0xc359511usize;
pub const UNLINK_ENTRY: usize = 0xc33caf8usize;
pub const UNLINK_CALLABLE: usize = 0xc33caf9usize;
pub const UNREGISTER_BLOCKDRIVER_ENTRY: usize = 0xc7cff4eusize;
pub const UNREGISTER_BLOCKDRIVER_CALLABLE: usize = 0xc7cff4fusize;
pub const UNREGISTER_DRIVER_ENTRY: usize = 0xc663914usize;
pub const UNREGISTER_DRIVER_CALLABLE: usize = 0xc663915usize;
pub const WRITE_ENTRY: usize = 0xc33d438usize;
pub const WRITE_CALLABLE: usize = 0xc33d439usize;
pub const BT_ADAPTER_SET_SCAN_MODE_ENTRY: usize = 0xc7842d8usize;
pub const BT_ADAPTER_SET_SCAN_MODE_CALLABLE: usize = 0xc7842d9usize;
pub const BT_ALLOC_ENTRY: usize = 0xc36cfb4usize;
pub const BT_ALLOC_CALLABLE: usize = 0xc36cfb5usize;
pub const BT_BUFFER_NEW_ENTRY: usize = 0xc46c476usize;
pub const BT_BUFFER_NEW_CALLABLE: usize = 0xc46c477usize;
pub const BT_CREATE_BOND_PRIVATE_ENTRY: usize = 0xc342662usize;
pub const BT_CREATE_BOND_PRIVATE_CALLABLE: usize = 0xc342663usize;
pub const BT_DISCOVERY_START_ENTRY: usize = 0xc521968usize;
pub const BT_DISCOVERY_START_CALLABLE: usize = 0xc521969usize;
pub const BT_DISCOVERY_STOP_ENTRY: usize = 0xc46a316usize;
pub const BT_DISCOVERY_STOP_CALLABLE: usize = 0xc46a317usize;
pub const BT_FREE_ENTRY: usize = 0xc36cfaausize;
pub const BT_FREE_CALLABLE: usize = 0xc36cfabusize;
pub const BT_GET_BOND_STATE_ENTRY: usize = 0xc73be80usize;
pub const BT_GET_BOND_STATE_CALLABLE: usize = 0xc73be81usize;
pub const BT_L2CAP_DISCONNECT_ENTRY: usize = 0xc493850usize;
pub const BT_L2CAP_DISCONNECT_CALLABLE: usize = 0xc493851usize;
pub const BT_L2CAP_SUBMIT_CID_ENTRY: usize = 0xc70ea00usize;
pub const BT_L2CAP_SUBMIT_CID_CALLABLE: usize = 0xc70ea01usize;
pub const BT_QUEUE_EXTERNAL_ENTRY: usize = 0xc551518usize;
pub const BT_QUEUE_EXTERNAL_CALLABLE: usize = 0xc551519usize;
pub const BT_QUEUE_FREE_ENTRY: usize = 0xc328b04usize;
pub const BT_QUEUE_FREE_CALLABLE: usize = 0xc328b05usize;
pub const BT_REMOVE_BOND_PRIVATE_ENTRY: usize = 0xc3d5128usize;
pub const BT_REMOVE_BOND_PRIVATE_CALLABLE: usize = 0xc3d5129usize;
pub const BT_TIMER_ADD_ENTRY: usize = 0xc46be6eusize;
pub const BT_TIMER_ADD_CALLABLE: usize = 0xc46be6fusize;
pub const BT_TIMER_CANCEL_ENTRY: usize = 0xc466eb0usize;
pub const BT_TIMER_CANCEL_CALLABLE: usize = 0xc466eb1usize;
pub const GAP_HOST_STOCK_RECEIVE_ENTRY: usize = 0xc85eed0usize;
pub const GAP_HOST_STOCK_RECEIVE_CALLABLE: usize = 0xc85eed1usize;
pub const SDP_BUILDER_CREATE_ENTRY: usize = 0xc88093cusize;
pub const SDP_BUILDER_CREATE_CALLABLE: usize = 0xc88093dusize;
pub const SDP_COMMIT_ENTRY: usize = 0xc480710usize;
pub const SDP_COMMIT_CALLABLE: usize = 0xc480711usize;
pub const SDP_SET_RAW_ATTRIBUTE_ENTRY: usize = 0xc875b1cusize;
pub const SDP_SET_RAW_ATTRIBUTE_CALLABLE: usize = 0xc875b1dusize;
pub const SDP_UNREGISTER_ENTRY: usize = 0xc6c3f78usize;
pub const SDP_UNREGISTER_CALLABLE: usize = 0xc6c3f79usize;
pub const APP_LOOKUP_ENTRY: usize = 0xc5c0528usize;
pub const APP_LOOKUP_CALLABLE: usize = 0xc5c0529usize;
pub const LVX_LABEL_CREATE_ENTRY: usize = 0xc7208c8usize;
pub const LVX_LABEL_CREATE_CALLABLE: usize = 0xc7208c9usize;
pub const LVX_LABEL_SET_TEXT_ENTRY: usize = 0xc0f77e8usize;
pub const LVX_LABEL_SET_TEXT_CALLABLE: usize = 0xc0f77e9usize;
pub const LVX_LIST_ROW_CREATE_ENTRY: usize = 0xc785048usize;
pub const LVX_LIST_ROW_CREATE_CALLABLE: usize = 0xc785049usize;
pub const LVX_LIST_ROW_TRAILING_ENTRY: usize = 0xc3a0568usize;
pub const LVX_LIST_ROW_TRAILING_CALLABLE: usize = 0xc3a0569usize;
pub const LVX_MSGBOX_CREATE_ENTRY: usize = 0xc43e84cusize;
pub const LVX_MSGBOX_CREATE_CALLABLE: usize = 0xc43e84dusize;
pub const LVX_MSGBOX_SET_CONTENT_ENTRY: usize = 0xc566ebcusize;
pub const LVX_MSGBOX_SET_CONTENT_CALLABLE: usize = 0xc566ebdusize;
pub const LVX_OBJECT_ALIGN_ENTRY: usize = 0xc7209d8usize;
pub const LVX_OBJECT_ALIGN_CALLABLE: usize = 0xc7209d9usize;
pub const LVX_OBJECT_DELETE_ENTRY: usize = 0xc720890usize;
pub const LVX_OBJECT_DELETE_CALLABLE: usize = 0xc720891usize;
pub const LVX_OBJECT_SET_SIZE_ENTRY: usize = 0xc720d08usize;
pub const LVX_OBJECT_SET_SIZE_CALLABLE: usize = 0xc720d09usize;
pub const SERVICE_MANAGER_CLEANUP_ENTRY: usize = 0xc5b2fc0usize;
pub const SERVICE_MANAGER_CLEANUP_CALLABLE: usize = 0xc5b2fc1usize;
pub const SERVICE_MANAGER_GET_PROFILE_ENTRY: usize = 0xc54b96cusize;
pub const SERVICE_MANAGER_GET_PROFILE_CALLABLE: usize = 0xc54b96dusize;
pub const SERVICE_MANAGER_REGISTER_ENTRY: usize = 0xc5740b8usize;
pub const SERVICE_MANAGER_REGISTER_CALLABLE: usize = 0xc5740b9usize;
pub const SERVICE_MANAGER_SHUTDOWN_ENTRY: usize = 0xc90856cusize;
pub const SERVICE_MANAGER_SHUTDOWN_CALLABLE: usize = 0xc90856dusize;
pub const SERVICE_MANAGER_STARTUP_ENTRY: usize = 0xc9085ccusize;
pub const SERVICE_MANAGER_STARTUP_CALLABLE: usize = 0xc9085cdusize;
pub const LV_BAR_CREATE_ENTRY: usize = 0xc7207c8usize;
pub const LV_BAR_CREATE_CALLABLE: usize = 0xc7207c9usize;
pub const LV_BAR_SET_RANGE_ENTRY: usize = 0xc0f7700usize;
pub const LV_BAR_SET_RANGE_CALLABLE: usize = 0xc0f7701usize;
pub const LV_BAR_SET_VALUE_ENTRY: usize = 0xc720cd8usize;
pub const LV_BAR_SET_VALUE_CALLABLE: usize = 0xc720cd9usize;
pub const LV_EVENT_GET_CODE_ENTRY: usize = 0xc720780usize;
pub const LV_EVENT_GET_CODE_CALLABLE: usize = 0xc720781usize;
pub const LV_EVENT_GET_USER_DATA_ENTRY: usize = 0xc720980usize;
pub const LV_EVENT_GET_USER_DATA_CALLABLE: usize = 0xc720981usize;
pub const LV_IMAGE_CREATE_ENTRY: usize = 0xc5d71c0usize;
pub const LV_IMAGE_CREATE_CALLABLE: usize = 0xc5d71c1usize;
pub const LV_IMAGE_SET_SRC_ENTRY: usize = 0xc3b2a5cusize;
pub const LV_IMAGE_SET_SRC_CALLABLE: usize = 0xc3b2a5dusize;
pub const LV_OBJ_ADD_EVENT_CB_ENTRY: usize = 0xc720db8usize;
pub const LV_OBJ_ADD_EVENT_CB_CALLABLE: usize = 0xc720db9usize;
pub const LV_OBJ_ALIGN_TO_ENTRY: usize = 0xc7209c8usize;
pub const LV_OBJ_ALIGN_TO_CALLABLE: usize = 0xc7209c9usize;
pub const LV_OBJ_MOVE_TO_INDEX_ENTRY: usize = 0xc720df8usize;
pub const LV_OBJ_MOVE_TO_INDEX_CALLABLE: usize = 0xc720df9usize;
pub const LV_OBJ_SET_HIDDEN_ENTRY: usize = 0xc7208d0usize;
pub const LV_OBJ_SET_HIDDEN_CALLABLE: usize = 0xc7208d1usize;
pub const LV_OBJ_SET_STYLE_BG_OPA_ENTRY: usize = 0xc6c2d94usize;
pub const LV_OBJ_SET_STYLE_BG_OPA_CALLABLE: usize = 0xc6c2d95usize;
pub const LV_TIMER_CREATE_ENTRY: usize = 0xc720808usize;
pub const LV_TIMER_CREATE_CALLABLE: usize = 0xc720809usize;
pub const LV_TIMER_DEL_ENTRY: usize = 0xc720c30usize;
pub const LV_TIMER_DEL_CALLABLE: usize = 0xc720c31usize;
pub const LVX_IMAGE_SET_SCALE_ENTRY: usize = 0xc3ae24eusize;
pub const LVX_IMAGE_SET_SCALE_CALLABLE: usize = 0xc3ae24fusize;
pub const LVX_LIST_ITEM_UPDATE_ENTRY: usize = 0xc3dbd8cusize;
pub const LVX_LIST_ITEM_UPDATE_CALLABLE: usize = 0xc3dbd8dusize;
pub const LVX_OBJECT_ADD_FLAG_ENTRY: usize = 0xc720b50usize;
pub const LVX_OBJECT_ADD_FLAG_CALLABLE: usize = 0xc720b51usize;
pub const LVX_PAGE_CONTENT_CREATE_ENTRY: usize = 0xc68f860usize;
pub const LVX_PAGE_CONTENT_CREATE_CALLABLE: usize = 0xc68f861usize;
pub const LVX_PAGE_TITLE_CREATE_ENTRY: usize = 0xc89892cusize;
pub const LVX_PAGE_TITLE_CREATE_CALLABLE: usize = 0xc89892dusize;
pub const LVX_STYLE_APPLY_ENTRY: usize = 0xc636da4usize;
pub const LVX_STYLE_APPLY_CALLABLE: usize = 0xc636da5usize;
pub const SPORT_TITLEBAR_DISPATCH_ENTRY: usize = 0xc54efdcusize;
pub const SPORT_TITLEBAR_DISPATCH_CALLABLE: usize = 0xc54efddusize;
pub const WATCHFACE_MANAGER_DELETE_WATCHFACE_ENTRY: usize = 0xc6c1564usize;
pub const WATCHFACE_MANAGER_DELETE_WATCHFACE_CALLABLE: usize = 0xc6c1565usize;

// ---- generated target-private raw wrappers ----
// Mechanical ABI only; ownership and policy stay in the handwritten facade.

pub unsafe fn raw_bt_adapter_get_instance() -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn() -> *mut core::ffi::c_void;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_ADAPTER_GET_INSTANCE_CALLABLE)
    };
    unsafe { f() }
}

pub unsafe fn raw_bt_l2cap_connect(a0: *const core::ffi::c_void) -> u32 {
    type F = unsafe extern "C" fn(*const core::ffi::c_void) -> u32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_L2CAP_CONNECT_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_core_bt_pair_request_callback(a0: *mut core::ffi::c_void, a1: *const u8) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, *const u8) -> i32;
    let f: F = unsafe {
        core::mem::transmute(
            canopus_target_generated::CANOPUS_FW_CORE_BT_PAIR_REQUEST_CALLBACK_CALLABLE,
        )
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_offload_property_apply(a0: *mut core::ffi::c_void) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_OFFLOAD_PROPERTY_APPLY_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_bt_adapter_register_a2dp_callbacks(
    a0: *mut core::ffi::c_void,
    a1: *const core::ffi::c_void,
) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, *const core::ffi::c_void) -> i32;
    let f: F = unsafe {
        core::mem::transmute(
            canopus_target_generated::CANOPUS_FW_BT_ADAPTER_REGISTER_A2DP_CALLBACKS_CALLABLE,
        )
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_bt_adapter_register_hfp_ag_callbacks(
    a0: *mut core::ffi::c_void,
    a1: *const core::ffi::c_void,
) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, *const core::ffi::c_void) -> i32;
    let f: F = unsafe {
        core::mem::transmute(
            canopus_target_generated::CANOPUS_FW_BT_ADAPTER_REGISTER_HFP_AG_CALLBACKS_CALLABLE,
        )
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_hfp_ag_connect(a0: *mut core::ffi::c_void, a1: *const core::ffi::c_void) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, *const core::ffi::c_void) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_HFP_AG_CONNECT_CALLABLE)
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_hfp_ag_disconnect(
    a0: *mut core::ffi::c_void,
    a1: *const core::ffi::c_void,
) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, *const core::ffi::c_void) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_HFP_AG_DISCONNECT_CALLABLE)
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_controller_crash_dump() -> i32 {
    type F = unsafe extern "C" fn() -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_CONTROLLER_CRASH_DUMP_CALLABLE)
    };
    unsafe { f() }
}

pub unsafe fn raw_app_launcher_data_init() -> i32 {
    type F = unsafe extern "C" fn() -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_APP_LAUNCHER_DATA_INIT_CALLABLE)
    };
    unsafe { f() }
}

pub unsafe fn raw_app_launcher_del(a0: u16) -> i32 {
    type F = unsafe extern "C" fn(u16) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_APP_LAUNCHER_DEL_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_interconnect_close(a0: *mut core::ffi::c_void) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_INTERCONNECT_CLOSE_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_interconnect_connect(
    a0: *mut core::ffi::c_void,
    a1: *mut core::ffi::c_void,
    a2: *const u8,
    a3: canopus_target_generated::canopus_interconnect_recv_cb,
) -> i32 {
    type F = unsafe extern "C" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *const u8,
        canopus_target_generated::canopus_interconnect_recv_cb,
    ) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_INTERCONNECT_CONNECT_CALLABLE)
    };
    unsafe { f(a0, a1, a2, a3) }
}

pub unsafe fn raw_interconnect_send(
    a0: *mut core::ffi::c_void,
    a1: *const u8,
    a2: *const canopus_target_generated::canopus_interconnect_message,
    a3: canopus_target_generated::canopus_interconnect_send_done,
    a4: *mut core::ffi::c_void,
) -> i32 {
    type F = unsafe extern "C" fn(
        *mut core::ffi::c_void,
        *const u8,
        *const canopus_target_generated::canopus_interconnect_message,
        canopus_target_generated::canopus_interconnect_send_done,
        *mut core::ffi::c_void,
    ) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_INTERCONNECT_SEND_CALLABLE)
    };
    unsafe { f(a0, a1, a2, a3, a4) }
}

pub unsafe fn raw_quickapp_register_app(
    a0: u16,
    a1: *const canopus_target_generated::canopus_interconnect_app_info,
) -> i32 {
    type F = unsafe extern "C" fn(
        u16,
        *const canopus_target_generated::canopus_interconnect_app_info,
    ) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_QUICKAPP_REGISTER_APP_CALLABLE)
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_thirdparty_submit_message_content(
    a0: *const core::ffi::c_void,
    a1: u32,
    a2: u32,
) -> i32 {
    type F = unsafe extern "C" fn(*const core::ffi::c_void, u32, u32) -> i32;
    let f: F = unsafe {
        core::mem::transmute(
            canopus_target_generated::CANOPUS_FW_THIRDPARTY_SUBMIT_MESSAGE_CONTENT_CALLABLE,
        )
    };
    unsafe { f(a0, a1, a2) }
}

pub unsafe fn raw_insmod(a0: *const u8, a1: *const u8) -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn(*const u8, *const u8) -> *mut core::ffi::c_void;
    let f: F =
        unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_INSMOD_CALLABLE) };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_modhandle(a0: *const u8) -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn(*const u8) -> *mut core::ffi::c_void;
    let f: F =
        unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_MODHANDLE_CALLABLE) };
    unsafe { f(a0) }
}

pub unsafe fn raw_rmmod(a0: *mut core::ffi::c_void) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> i32;
    let f: F = unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_RMMOD_CALLABLE) };
    unsafe { f(a0) }
}

pub unsafe fn raw_clock_gettime(
    a0: u32,
    a1: *mut canopus_target_generated::stock_timespec_t,
) -> i32 {
    type F = unsafe extern "C" fn(u32, *mut canopus_target_generated::stock_timespec_t) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_CLOCK_GETTIME_CALLABLE)
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_close(a0: i32) -> i32 {
    type F = unsafe extern "C" fn(i32) -> i32;
    let f: F = unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_CLOSE_CALLABLE) };
    unsafe { f(a0) }
}

pub unsafe fn raw_errno_location() -> *mut i32 {
    type F = unsafe extern "C" fn() -> *mut i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_ERRNO_LOCATION_CALLABLE)
    };
    unsafe { f() }
}

pub unsafe fn raw_heap_free(a0: *mut core::ffi::c_void) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> i32;
    let f: F =
        unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_HEAP_FREE_CALLABLE) };
    unsafe { f(a0) }
}

pub unsafe fn raw_heap_mallinfo(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_HEAP_MALLINFO_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_heap_malloc(a0: u32) -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn(u32) -> *mut core::ffi::c_void;
    let f: F =
        unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_HEAP_MALLOC_CALLABLE) };
    unsafe { f(a0) }
}

pub unsafe fn raw_heap_zalloc(a0: u32) -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn(u32) -> *mut core::ffi::c_void;
    let f: F =
        unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_HEAP_ZALLOC_CALLABLE) };
    unsafe { f(a0) }
}

pub unsafe fn raw_ioctl(a0: i32, a1: u32, a2: usize) -> i32 {
    type F = unsafe extern "C" fn(i32, u32, usize) -> i32;
    let f: F = unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_IOCTL_CALLABLE) };
    unsafe { f(a0, a1, a2) }
}

pub unsafe fn raw_lseek(a0: i32, a1: i64, a2: i32) -> i64 {
    type F = unsafe extern "C" fn(i32, i64, i32) -> i64;
    let f: F = unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_LSEEK_CALLABLE) };
    unsafe { f(a0, a1, a2) }
}

pub unsafe fn raw_open(a0: *const u8, a1: i32) -> i32 {
    type F = unsafe extern "C" fn(*const u8, i32) -> i32;
    let f: F = unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_OPEN_CALLABLE) };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_register_blockdriver(
    a0: *const u8,
    a1: *const core::ffi::c_void,
    a2: u32,
    a3: *mut core::ffi::c_void,
) -> i32 {
    type F = unsafe extern "C" fn(
        *const u8,
        *const core::ffi::c_void,
        u32,
        *mut core::ffi::c_void,
    ) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_REGISTER_BLOCKDRIVER_CALLABLE)
    };
    unsafe { f(a0, a1, a2, a3) }
}

pub unsafe fn raw_register_driver(
    a0: *const u8,
    a1: *const core::ffi::c_void,
    a2: u32,
    a3: *mut core::ffi::c_void,
) -> i32 {
    type F = unsafe extern "C" fn(
        *const u8,
        *const core::ffi::c_void,
        u32,
        *mut core::ffi::c_void,
    ) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_REGISTER_DRIVER_CALLABLE)
    };
    unsafe { f(a0, a1, a2, a3) }
}

pub unsafe fn raw_rename(a0: *const u8, a1: *const u8) -> i32 {
    type F = unsafe extern "C" fn(*const u8, *const u8) -> i32;
    let f: F =
        unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_RENAME_CALLABLE) };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_sem_post(a0: *mut core::ffi::c_void) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> i32;
    let f: F =
        unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_SEM_POST_CALLABLE) };
    unsafe { f(a0) }
}

pub unsafe fn raw_sem_trywait(a0: *mut core::ffi::c_void) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> i32;
    let f: F =
        unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_SEM_TRYWAIT_CALLABLE) };
    unsafe { f(a0) }
}

pub unsafe fn raw_sem_wait(a0: *mut core::ffi::c_void) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> i32;
    let f: F =
        unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_SEM_WAIT_CALLABLE) };
    unsafe { f(a0) }
}

pub unsafe fn raw_unlink(a0: *const u8) -> i32 {
    type F = unsafe extern "C" fn(*const u8) -> i32;
    let f: F =
        unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_UNLINK_CALLABLE) };
    unsafe { f(a0) }
}

pub unsafe fn raw_unregister_blockdriver(a0: *const u8) -> i32 {
    type F = unsafe extern "C" fn(*const u8) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_UNREGISTER_BLOCKDRIVER_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_unregister_driver(a0: *const u8) -> i32 {
    type F = unsafe extern "C" fn(*const u8) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_UNREGISTER_DRIVER_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_bt_adapter_set_scan_mode(a0: i32, a1: i32) -> i32 {
    type F = unsafe extern "C" fn(i32, i32) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_ADAPTER_SET_SCAN_MODE_CALLABLE)
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_bt_alloc(a0: u32) -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn(u32) -> *mut core::ffi::c_void;
    let f: F =
        unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_ALLOC_CALLABLE) };
    unsafe { f(a0) }
}

pub unsafe fn raw_bt_buffer_new(a0: u16, a1: u16) -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn(u16, u16) -> *mut core::ffi::c_void;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_BUFFER_NEW_CALLABLE)
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_bt_create_bond_private(a0: *const u8, a1: u32) -> i32 {
    type F = unsafe extern "C" fn(*const u8, u32) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_CREATE_BOND_PRIVATE_CALLABLE)
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_bt_discovery_start(a0: *mut core::ffi::c_void, a1: i32) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, i32) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_DISCOVERY_START_CALLABLE)
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_bt_discovery_stop(a0: *mut core::ffi::c_void) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_DISCOVERY_STOP_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_bt_free(a0: *mut core::ffi::c_void) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> i32;
    let f: F =
        unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_FREE_CALLABLE) };
    unsafe { f(a0) }
}

pub unsafe fn raw_bt_get_bond_state(a0: *const u8) -> u32 {
    type F = unsafe extern "C" fn(*const u8) -> u32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_GET_BOND_STATE_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_bt_l2cap_disconnect(a0: *const core::ffi::c_void) -> i32 {
    type F = unsafe extern "C" fn(*const core::ffi::c_void) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_L2CAP_DISCONNECT_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_bt_l2cap_submit_cid(a0: *mut core::ffi::c_void, a1: u16) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, u16) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_L2CAP_SUBMIT_CID_CALLABLE)
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_bt_queue_external(
    a0: *mut core::ffi::c_void,
    a1: *mut core::ffi::c_void,
    a2: *mut core::ffi::c_void,
    a3: *mut core::ffi::c_void,
    a4: u8,
) -> i32 {
    type F = unsafe extern "C" fn(
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        u8,
    ) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_QUEUE_EXTERNAL_CALLABLE)
    };
    unsafe { f(a0, a1, a2, a3, a4) }
}

pub unsafe fn raw_bt_queue_free(a0: *mut core::ffi::c_void) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_QUEUE_FREE_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_bt_remove_bond_private(a0: *const u8, a1: u32) -> i32 {
    type F = unsafe extern "C" fn(*const u8, u32) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_REMOVE_BOND_PRIVATE_CALLABLE)
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_bt_timer_add(
    a0: *mut core::ffi::c_void,
    a1: u32,
    a2: u8,
    a3: *mut core::ffi::c_void,
    a4: *mut core::ffi::c_void,
    a5: *const u8,
    a6: u32,
) -> u32 {
    type F = unsafe extern "C" fn(
        *mut core::ffi::c_void,
        u32,
        u8,
        *mut core::ffi::c_void,
        *mut core::ffi::c_void,
        *const u8,
        u32,
    ) -> u32;
    let f: F =
        unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_TIMER_ADD_CALLABLE) };
    unsafe { f(a0, a1, a2, a3, a4, a5, a6) }
}

pub unsafe fn raw_bt_timer_cancel(a0: *mut u32) -> i32 {
    type F = unsafe extern "C" fn(*mut u32) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_BT_TIMER_CANCEL_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_gap_host_stock_receive(a0: *mut core::ffi::c_void, a1: *mut u8, a2: i32) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, *mut u8, i32) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_GAP_HOST_STOCK_RECEIVE_CALLABLE)
    };
    unsafe { f(a0, a1, a2) }
}

pub unsafe fn raw_sdp_builder_create(
    a0: u32,
    a1: u16,
    a2: u16,
    a3: u8,
    a4: *const u8,
) -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn(u32, u16, u16, u8, *const u8) -> *mut core::ffi::c_void;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_SDP_BUILDER_CREATE_CALLABLE)
    };
    unsafe { f(a0, a1, a2, a3, a4) }
}

pub unsafe fn raw_sdp_commit(a0: *mut core::ffi::c_void) -> u32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> u32;
    let f: F =
        unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_SDP_COMMIT_CALLABLE) };
    unsafe { f(a0) }
}

pub unsafe fn raw_sdp_set_raw_attribute(
    a0: *mut core::ffi::c_void,
    a1: u16,
    a2: u16,
    a3: u16,
    a4: *const core::ffi::c_void,
) -> *mut u8 {
    type F = unsafe extern "C" fn(
        *mut core::ffi::c_void,
        u16,
        u16,
        u16,
        *const core::ffi::c_void,
    ) -> *mut u8;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_SDP_SET_RAW_ATTRIBUTE_CALLABLE)
    };
    unsafe { f(a0, a1, a2, a3, a4) }
}

pub unsafe fn raw_sdp_unregister(a0: u32) -> i32 {
    type F = unsafe extern "C" fn(u32) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_SDP_UNREGISTER_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_service_manager_cleanup(a0: i32) -> i32 {
    type F = unsafe extern "C" fn(i32) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_SERVICE_MANAGER_CLEANUP_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_service_manager_get_profile(a0: u32) -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn(u32) -> *mut core::ffi::c_void;
    let f: F = unsafe {
        core::mem::transmute(
            canopus_target_generated::CANOPUS_FW_SERVICE_MANAGER_GET_PROFILE_CALLABLE,
        )
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_service_manager_register(a0: *mut core::ffi::c_void) -> i32 {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_SERVICE_MANAGER_REGISTER_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_service_manager_shutdown(a0: i32) -> i32 {
    type F = unsafe extern "C" fn(i32) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_SERVICE_MANAGER_SHUTDOWN_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_service_manager_startup(a0: i32) -> i32 {
    type F = unsafe extern "C" fn(i32) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_SERVICE_MANAGER_STARTUP_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_lv_bar_create(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LV_BAR_CREATE_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_lv_bar_set_range(a0: *mut core::ffi::c_void, a1: i32, a2: i32) -> () {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, i32, i32) -> ();
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LV_BAR_SET_RANGE_CALLABLE)
    };
    unsafe { f(a0, a1, a2) }
}

pub unsafe fn raw_lv_bar_set_value(a0: *mut core::ffi::c_void, a1: i32, a2: u32) -> () {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, i32, u32) -> ();
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LV_BAR_SET_VALUE_CALLABLE)
    };
    unsafe { f(a0, a1, a2) }
}

pub unsafe fn raw_lv_event_get_user_data(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LV_EVENT_GET_USER_DATA_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_lv_image_create(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LV_IMAGE_CREATE_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_lv_image_set_src(a0: *mut core::ffi::c_void, a1: *const core::ffi::c_void) -> () {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, *const core::ffi::c_void) -> ();
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LV_IMAGE_SET_SRC_CALLABLE)
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_lv_obj_add_event_cb(
    a0: *mut core::ffi::c_void,
    a1: canopus_target_generated::canopus_lvx_event_cb,
    a2: u32,
    a3: *mut core::ffi::c_void,
) -> () {
    type F = unsafe extern "C" fn(
        *mut core::ffi::c_void,
        canopus_target_generated::canopus_lvx_event_cb,
        u32,
        *mut core::ffi::c_void,
    ) -> ();
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LV_OBJ_ADD_EVENT_CB_CALLABLE)
    };
    unsafe { f(a0, a1, a2, a3) }
}

pub unsafe fn raw_lv_obj_align_to(
    a0: *mut core::ffi::c_void,
    a1: *mut core::ffi::c_void,
    a2: u32,
    a3: i32,
    a4: i32,
) -> () {
    type F =
        unsafe extern "C" fn(*mut core::ffi::c_void, *mut core::ffi::c_void, u32, i32, i32) -> ();
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LV_OBJ_ALIGN_TO_CALLABLE)
    };
    unsafe { f(a0, a1, a2, a3, a4) }
}

pub unsafe fn raw_lv_obj_move_to_index(a0: *mut core::ffi::c_void, a1: i32) -> () {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, i32) -> ();
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LV_OBJ_MOVE_TO_INDEX_CALLABLE)
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_lv_obj_set_hidden(a0: *mut core::ffi::c_void, a1: u32) -> () {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, u32) -> ();
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LV_OBJ_SET_HIDDEN_CALLABLE)
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_lv_obj_set_style_bg_opa(a0: *mut core::ffi::c_void, a1: u32, a2: u32) -> () {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, u32, u32) -> ();
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LV_OBJ_SET_STYLE_BG_OPA_CALLABLE)
    };
    unsafe { f(a0, a1, a2) }
}

pub unsafe fn raw_lv_timer_create(
    a0: canopus_target_generated::canopus_lvx_event_cb,
    a1: u32,
    a2: *mut core::ffi::c_void,
) -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn(
        canopus_target_generated::canopus_lvx_event_cb,
        u32,
        *mut core::ffi::c_void,
    ) -> *mut core::ffi::c_void;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LV_TIMER_CREATE_CALLABLE)
    };
    unsafe { f(a0, a1, a2) }
}

pub unsafe fn raw_lv_timer_del(a0: *mut core::ffi::c_void) -> () {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> ();
    let f: F =
        unsafe { core::mem::transmute(canopus_target_generated::CANOPUS_FW_LV_TIMER_DEL_CALLABLE) };
    unsafe { f(a0) }
}

pub unsafe fn raw_lvx_image_set_scale(a0: *mut core::ffi::c_void, a1: i32, a2: i32) -> () {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, i32, i32) -> ();
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LVX_IMAGE_SET_SCALE_CALLABLE)
    };
    unsafe { f(a0, a1, a2) }
}

pub unsafe fn raw_lvx_list_item_update(
    a0: *mut core::ffi::c_void,
    a1: *const u8,
    a2: *const u8,
    a3: *const u8,
    a4: i32,
    a5: u8,
) -> i32 {
    type F = unsafe extern "C" fn(
        *mut core::ffi::c_void,
        *const u8,
        *const u8,
        *const u8,
        i32,
        u8,
    ) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LVX_LIST_ITEM_UPDATE_CALLABLE)
    };
    unsafe { f(a0, a1, a2, a3, a4, a5) }
}

pub unsafe fn raw_lvx_object_add_flag(a0: *mut core::ffi::c_void, a1: u32) -> () {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void, u32) -> ();
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LVX_OBJECT_ADD_FLAG_CALLABLE)
    };
    unsafe { f(a0, a1) }
}

pub unsafe fn raw_lvx_page_content_create(a0: *mut core::ffi::c_void) -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn(*mut core::ffi::c_void) -> *mut core::ffi::c_void;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LVX_PAGE_CONTENT_CREATE_CALLABLE)
    };
    unsafe { f(a0) }
}

pub unsafe fn raw_lvx_page_title_create(
    a0: *mut core::ffi::c_void,
    a1: *const u8,
    a2: u32,
    a3: canopus_target_generated::canopus_lvx_event_cb,
    a4: *mut core::ffi::c_void,
) -> *mut core::ffi::c_void {
    type F = unsafe extern "C" fn(
        *mut core::ffi::c_void,
        *const u8,
        u32,
        canopus_target_generated::canopus_lvx_event_cb,
        *mut core::ffi::c_void,
    ) -> *mut core::ffi::c_void;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LVX_PAGE_TITLE_CREATE_CALLABLE)
    };
    unsafe { f(a0, a1, a2, a3, a4) }
}

pub unsafe fn raw_lvx_style_apply(
    a0: *mut core::ffi::c_void,
    a1: *const core::ffi::c_void,
    a2: u32,
    a3: u32,
) -> i32 {
    type F =
        unsafe extern "C" fn(*mut core::ffi::c_void, *const core::ffi::c_void, u32, u32) -> i32;
    let f: F = unsafe {
        core::mem::transmute(canopus_target_generated::CANOPUS_FW_LVX_STYLE_APPLY_CALLABLE)
    };
    unsafe { f(a0, a1, a2, a3) }
}

pub unsafe fn raw_watchface_manager_delete_watchface(a0: *const u8) -> i32 {
    type F = unsafe extern "C" fn(*const u8) -> i32;
    let f: F = unsafe {
        core::mem::transmute(
            canopus_target_generated::CANOPUS_FW_WATCHFACE_MANAGER_DELETE_WATCHFACE_CALLABLE,
        )
    };
    unsafe { f(a0) }
}

// generated target-private raw wrapper count: 83
