//! Module scaffolding templates (CAN-REL-004).
//!
//! `canopus module new <name> --lang c|rust --target <id>` renders a working
//! module skeleton: source, package manifest and a build script that produces
//! a verifier-PASSED zero-import ELF32 ET_REL for the target.

use std::collections::BTreeMap;

/// Renders the file set (filename -> contents) for a new module.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ModuleLang {
    C,
    Rust,
}

pub fn render(name: &str, target_id: &str, lang: ModuleLang) -> BTreeMap<String, String> {
    match lang {
        ModuleLang::C => c_module(name, target_id),
        ModuleLang::Rust => rust_module(name, target_id),
    }
}

fn safe_name(name: &str) -> String {
    let mut out: String = name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() || c == '_' { c } else { '_' })
        .collect();
    while out.starts_with('_') {
        out.remove(0);
    }
    if out.is_empty() {
        out = "module".to_string();
    }
    out
}

fn manifest(name: &str, target_id: &str) -> String {
    format!(
        r#"{{
  "schema": 1,
  "package_id": "org.canopus.{name}",
  "module_id": "org.canopus.{name}",
  "version": "0.1.0",
  "build_generation": 1,
  "canopus_abi": "1",
  "lifecycle": "removable",
  "artifacts": [
    {{
      "target_id": "{target_id}",
      "target_pack_revision": 1,
      "firmware_sha256": "0000000000000000000000000000000000000000000000000000000000000000",
      "path": "artifacts/{target_id}/module.elf",
      "sha256": "0000000000000000000000000000000000000000000000000000000000000000"
    }}
  ],
  "capabilities": {{ "required": [] }},
  "target_pack_revision": 1,
  "signature": {{ "key_id": "dev-key-001", "algorithm": "ed25519" }},
  "min_manager_version": "0.1.0",
  "reboot_required": false
}}
"#,
        name = safe_name(name)
    )
}

fn c_source(name: &str, target_id: &str) -> String {
    let n = safe_name(name);
    format!(
        r#"/* {n}.c — Canopus removable module. Generated by `canopus module new`. */
#include "canopus_abi.h"
#include "canopus_runtime.h"
#include "canopus_veneer.h"
#include <stddef.h>

#define {U}_MAGIC 0x4D4F4455u /* "MODU" */

static uint32_t s_ready;

static int {n}_prepare(const struct canopus_context_v1 *ctx)
{{
    (void)ctx;
    s_ready = 0u;
    return 0;
}}

static int {n}_activate(const struct canopus_context_v1 *ctx)
{{
    (void)ctx;
    /* fail closed on a firmware mismatch */
    if (canopus_identity_guard() != 0) {{
        return -1;
    }}
    s_ready = 1u;
    return 0;
}}

static int {n}_deactivate(const struct canopus_context_v1 *ctx)
{{
    (void)ctx;
    s_ready = 0u;
    return 0;
}}

static int {n}_stop(const struct canopus_context_v1 *ctx)
{{
    (void)ctx;
    s_ready = 0u;
    return 0;
}}

static int {n}_query(struct canopus_status_writer_v1 *writer)
{{
    if (writer != 0) {{
        struct canopus_status_writer_v1 tmp = *writer;
        canopus_status_put_u32(&tmp, {U}_MAGIC);
        canopus_status_put_u32(&tmp, s_ready);
        canopus_status_writer_publish(&tmp);
        *writer = tmp;
    }}
    return 0;
}}

static const struct canopus_module_descriptor_v1 g_descriptor = {{
    .struct_size = sizeof(struct canopus_module_descriptor_v1),
    .abi_major = CANOPUS_ABI_MAJOR,
    .abi_minor = CANOPUS_ABI_MINOR,
    .flags = 0u,
    .module_id = "org.canopus.{n}",
    .module_version = "0.1.0",
    .build_id = "{n}-0.1.0",
    .target_id = "{target_id}",
    .prepare = {n}_prepare,
    .activate = {n}_activate,
    .deactivate = {n}_deactivate,
    .stop = {n}_stop,
    .query = {n}_query,
}};

const struct canopus_module_descriptor_v1 *{n}_descriptor(void)
{{
    return &g_descriptor;
}}

__attribute__((constructor)) static void {n}_ctor(void)
{{
    /* Fail closed on a firmware mismatch BEFORE any use. The identity guard
     * reads firmware addresses, which also keeps this constructor
     * non-eliminable under -ffunction-sections/-Os (clang drops constructors
     * whose bodies have no observable side effect). */
    if (canopus_identity_guard() != 0) {{
        return;
    }}
    (void){n}_prepare(0);
}}

__attribute__((destructor)) static void {n}_dtor(void)
{{
    (void){n}_stop(0);
}}
"#,
        n = n,
        U = n.to_uppercase(),
        target_id = target_id
    )
}

fn c_build_sh(dir_name: &str, safe: &str, target_id: &str) -> String {
    let n = safe.to_string();
    format!(
        r#"#!/bin/sh
# Builds the {n} module for {target_id}.
set -eu
ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd)
TARGET_ID="{target_id}"
PACK_DIR="$ROOT/targets/$TARGET_ID"
GENERATED="$PACK_DIR/generated/canopus_veneer.h"
OUT="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)/build"
CC=${{CC:-clang}}

[ -f "$GENERATED" ] || {{
    echo "error: run 'canopus target generate-veneer $TARGET_ID' first"
    exit 1
}}
mkdir -p "$OUT"
cd "$ROOT"

TARGET_FLAGS="--target=arm-none-eabi -mcpu=cortex-m33 -mthumb -mfloat-abi=soft \
  -ffreestanding -fno-common -fno-builtin -fno-stack-protector \
  -fno-unwind-tables -fno-asynchronous-unwind-tables -fdata-sections \
  -ffunction-sections -Os -Wall -Wextra -Werror -DCANOPUS_TARGET=1"

INC="-I$ROOT/sdk/c -I$ROOT/runtime/lifecycle -I$ROOT/runtime/resources \
  -I$ROOT/runtime/diagnostics -I$ROOT/runtime/control -I$ROOT/runtime/module \
  -I$PACK_DIR/generated -Imodules/{dir}"

SRCS="runtime/control/canopus_control.c runtime/lifecycle/canopus_lifecycle.c \
  runtime/resources/canopus_resource.c runtime/diagnostics/canopus_diagnostics.c \
  runtime/module/canopus_module.c modules/{dir}/{n}.c"

for s in $SRCS; do
    $CC $TARGET_FLAGS $INC -c "$ROOT/$s" -o "$OUT/$(basename "${{s%.c}}").o"
done

LD=${{LD:-ld.lld}}
$LD -r -o "$OUT/{n}_module.elf" "$OUT"/canopus_control.o \
    "$OUT"/canopus_lifecycle.o "$OUT"/canopus_resource.o \
    "$OUT"/canopus_diagnostics.o "$OUT"/canopus_module.o "$OUT"/{n}.o

"$ROOT/target/debug/canopus" verify "$OUT/{n}_module.elf" \
    --target "$TARGET_ID" --targets-dir "$ROOT/targets"
"#,
        n = n,
        dir = dir_name,
        target_id = target_id
    )
}

fn c_module(name: &str, target_id: &str) -> BTreeMap<String, String> {
    let n = safe_name(name);
    let mut files = BTreeMap::new();
    files.insert(format!("{n}.c"), c_source(&n, target_id));
    files.insert("package.json".into(), manifest(&n, target_id));
    files.insert("build.sh".into(), c_build_sh(name, &n, target_id));
    files
}

fn rust_source(name: &str, target_id: &str) -> String {
    let n = safe_name(name);
    format!(
        r#"//! {n} — Canopus no_std Rust module. Generated by `canopus module new`.
#![no_std]

use canopus_abi::*;
use canopus_runtime::*;
use core::sync::atomic::Ordering;

const {U}_MAGIC: u32 = 0x4D4F4455; // "MODU"

#[no_mangle]
pub extern "C" fn {n}_prepare(_ctx: *const ContextV1) -> i32 {{ 0 }}

#[no_mangle]
pub extern "C" fn {n}_activate(_ctx: *const ContextV1) -> i32 {{
    #[cfg(feature = "device")]
    {{
        if canopus_target_generated::canopus_identity_guard() != 0 {{
            return -1;
        }}
    }}
    0
}}

#[no_mangle]
pub extern "C" fn {n}_deactivate(_ctx: *const ContextV1) -> i32 {{ 0 }}

#[no_mangle]
pub extern "C" fn {n}_stop(_ctx: *const ContextV1) -> i32 {{ 0 }}

#[no_mangle]
pub extern "C" fn {n}_query(w: *mut StatusWriterV1) -> i32 {{
    if w.is_null() {{
        return -1;
    }}
    let w = unsafe {{ &mut *w }};
    unsafe {{
        if !status_put_u32(w, {U}_MAGIC) {{
            return -1;
        }}
        status_writer_publish(w);
    }}
    0
}}

#[no_mangle]
pub static canopus_module_descriptor: ModuleDescriptorV1 = ModuleDescriptorV1 {{
    struct_size: core::mem::size_of::<ModuleDescriptorV1>() as u32,
    abi_major: ABI_MAJOR,
    abi_minor: ABI_MINOR,
    flags: 0,
    module_id: pack(b"org.canopus.{n}"),
    module_version: pack(b"0.1.0"),
    build_id: pack(b"{n}-0.1.0"),
    target_id: pack(b"{target_id}"),
    prepare: Some({n}_prepare),
    activate: Some({n}_activate),
    deactivate: Some({n}_deactivate),
    stop: Some({n}_stop),
    query: Some({n}_query),
}};

const fn pack<const N: usize>(s: &[u8]) -> [u8; N] {{
    let mut out = [0u8; N];
    let mut i = 0;
    while i < s.len() && i < N {{
        out[i] = s[i];
        i += 1;
    }}
    out
}}

#[no_mangle]
pub extern "C" fn canopus_module_descriptor_ptr() -> *const ModuleDescriptorV1 {{
    &canopus_module_descriptor
}}
"#,
        n = n,
        U = n.to_uppercase(),
        target_id = target_id
    )
}

fn rust_cargo(n: &str) -> String {
    format!(
        r#"[package]
name = "{n}"
description = "Canopus Rust module (CAN-REL-004 template)"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[lib]
name = "{n}"
crate-type = ["rlib"]

[features]
default = []
device = ["dep:canopus-target-generated"]

[dependencies]
canopus-abi = {{ path = "../../sdk/rust/canopus-abi" }}
canopus-runtime = {{ path = "../../sdk/rust/canopus-runtime" }}
canopus-target-generated = {{ path = "../../sdk/rust/canopus-target-generated", optional = true }}

[dev-dependencies]
canopus-host-fake = {{ path = "../../sdk/rust/canopus-host-fake" }}
"#
    )
}

fn rust_module(name: &str, target_id: &str) -> BTreeMap<String, String> {
    let n = safe_name(name);
    let mut files = BTreeMap::new();
    files.insert("Cargo.toml".into(), rust_cargo(&n));
    files.insert("src/lib.rs".into(), rust_source(&n, target_id));
    files.insert("package.json".into(), manifest(&n, target_id));
    files
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn c_template_renders_valid_structure() {
        let files = render("my-fn", "xiaomi-band-10-pro-3.101.030", ModuleLang::C);
        assert_eq!(files.len(), 3);
        let src = &files["my_fn.c"];
        assert!(src.contains("canopus_identity_guard"));
        assert!(src.contains("org.canopus.my_fn"));
        assert!(src.contains("__attribute__((constructor))"));
        let sh = &files["build.sh"];
        assert!(sh.contains("xiaomi-band-10-pro-3.101.030"));
        assert!(sh.contains("verify"));
        // manifest parses as JSON
        let m: serde_json::Value = serde_json::from_str(&files["package.json"]).unwrap();
        assert_eq!(m["module_id"], "org.canopus.my_fn");
        assert_eq!(m["lifecycle"], "removable");
    }

    #[test]
    fn rust_template_renders_valid_structure() {
        let files = render("counter", "xiaomi-band-10-pro-3.101.030", ModuleLang::Rust);
        assert_eq!(files.len(), 3);
        let src = &files["src/lib.rs"];
        assert!(src.contains("#![no_std]"));
        assert!(src.contains("canopus_identity_guard"));
        assert!(src.contains("canopus_module_descriptor"));
        let cargo = &files["Cargo.toml"];
        assert!(cargo.contains("canopus-abi"));
        assert!(cargo.contains("canopus-runtime"));
        assert!(src.contains("no_std"));
    }

    #[test]
    fn unsafe_names_sanitized() {
        assert_eq!(safe_name("my module!"), "my_module_");
        assert_eq!(safe_name("___"), "module");
        assert_eq!(safe_name("ok"), "ok");
    }

    #[test]
    fn manifest_validates_against_schema() {
        let files = render("t", "xiaomi-band-10-pro-3.101.030", ModuleLang::C);
        let value: serde_json::Value = serde_json::from_str(&files["package.json"]).unwrap();
        crate::schema::validate(crate::schema::SchemaKind::Package, &value).unwrap();
    }
}
