#!/usr/bin/env python3
"""Build the complete flat Band 11 installer resources (device test candidate)."""
from __future__ import annotations
import argparse
import hashlib
import json
import os
from pathlib import Path
import struct
import subprocess
import tomllib
import zipfile
import zlib

ROOT = Path(__file__).resolve().parents[1]
TARGET = "xiaomi-band-11-4.100.139"
FAMILY = ROOT / "watchfaces/canopus-installer-prod/xiaomi-band-11"


def metadata(target_id=TARGET):
    if target_id != TARGET:
        raise ValueError(f"unsupported target: {target_id}")
    directory = ROOT / "targets" / target_id
    pack = tomllib.loads((directory / "target.toml").read_text())
    profile = tomllib.loads((directory / "loader/lua-recovery.toml").read_text())
    for key in ("target_id", "firmware_sha256", "firmware_version", "firmware_build"):
        if profile.get(key) != pack.get(key):
            raise ValueError(f"recovery profile {key} differs from target pack")
    if profile.get("schema") != 1 or profile.get("status") != "STATIC_RECOVERED":
        raise ValueError("recovery profile lacks static verification")
    for key in ("pmain", "pmain_error_handler", "os_execute", "luaopen_os", "system", "io_open"):
        value = profile.get(key)
        if type(value) is not int or value % 2 or not any(
            r["base"] <= value < r["base"] + r["size"] for r in pack["firmware_address_ranges"]
        ):
            raise ValueError(f"invalid even Thumb entry: {key}")
    return profile


def render(target_id=TARGET):
    profile = metadata(target_id)
    fields = ("target_id", "firmware_sha256", "firmware_version", "firmware_build",
              "lua_version", "identity_path", "pmain", "pmain_error_handler", "os_execute", "io_open")
    lua_profile = "local PROFILE = {\n" + "".join(
        f"    {key} = {hex(profile[key]) if type(profile[key]) is int else json.dumps(profile[key])},\n"
        for key in fields
    ) + "}"
    source = (FAMILY / "src/main.lua").read_text()
    replacements = {
        "-- @CANOPUS_RECOVERY@": "local recovery = (function()\n" + (FAMILY / "src/recover_execute.lua").read_text() + "\nend)()",
        "-- @CANOPUS_PROFILE@": lua_profile,
        "-- @CANOPUS_NATIVE_LOADER@": "local native_loader = (function()\n" + (FAMILY / "src/native_loader.lua").read_text() + "\nend)()",
        "-- @CANOPUS_PROGRESS@": "local progress = (function()\n" + (FAMILY / "src/progress.lua").read_text() + "\nend)()",
    }
    for marker, replacement in replacements.items():
        if source.count(marker) != 1:
            raise ValueError(f"entry marker missing or repeated: {marker}")
        source = source.replace(marker, replacement)
    return "-- Generated by scripts/build_band11_installer.py; edit src/ and target metadata.\n" + source, profile


def run(*args):
    subprocess.run([str(x) for x in args], cwd=ROOT, check=True)


def elf_sections(path):
    data = path.read_bytes()
    if data[:7] != b"\x7fELF\x01\x01\x01":
        raise ValueError("not little-endian ELF32")
    offset = struct.unpack_from("<I", data, 32)[0]
    stride, count, names = struct.unpack_from("<HHH", data, 46)
    rows = [struct.unpack_from("<10I", data, offset + i * stride) for i in range(count)]
    strings = data[rows[names][4]:rows[names][4] + rows[names][5]]
    return data, [(strings[r[0]:].split(b"\0", 1)[0].decode(), r) for r in rows]


def linked_binary(path):
    """Check PIC invariants and extract allocatable sections without objcopy."""
    data, sections = elf_sections(path)
    alloc = [(name, r) for name, r in sections if r[2] & 2 and r[5]]
    if any(r[1] == 8 or r[2] & 1 for _, r in alloc):
        raise ValueError("staged PIC image must have no GOT, writable data, or BSS")
    # --emit-relocs preserves link evidence. Absolute link-time addresses would
    # be wrong after moving the binary; only PC-relative relocations are allowed.
    for name, r in sections:
        if r[1] == 9:
            for pos in range(r[4], r[4] + r[5], 8):
                _, info = struct.unpack_from("<II", data, pos)
                if info & 255 not in (3, 10, 23, 30, 42):
                    raise ValueError(f"non-PIC relocation {info & 255} in {name}")
    end = max(r[3] + r[5] for _, r in alloc)
    result = bytearray(end)
    for _, r in alloc:
        result[r[3]:r[3] + r[5]] = data[r[4]:r[4] + r[5]]
    if struct.unpack_from("<I", data, 24)[0] & ~1:
        raise ValueError("stage entry must be offset zero")
    return bytes(result)


def build_stages(out, supervisor):
    cc = os.environ.get("CC", "clang")
    flags = ["--target=arm-none-eabi", "-mcpu=cortex-m33", "-mthumb", "-mfloat-abi=soft",
             "-ffreestanding", "-fPIC", "-fno-common", "-fno-builtin", "-fno-jump-tables",
             "-fno-stack-protector", "-fno-unwind-tables", "-fno-asynchronous-unwind-tables",
             "-fdata-sections", "-ffunction-sections", "-fstack-usage", "-Os", "-Wall", "-Wextra", "-Werror"]
    inc = [f"-I{ROOT / p}" for p in ("sdk/c", "runtime/loader", "manager/target/band11")] + [f"-I{out}"]
    header = out / "canopus_band11_sizes.h"
    header.write_text(f"#define B11_SUPERVISOR_SIZE {len(supervisor)}u\n#define B11_SUPERVISOR_CRC 0x{zlib.crc32(supervisor):08x}u\n")
    def compile(source, name):
        obj = out / (name + ".o")
        run(cc, *flags, *inc, "-c", ROOT / source, "-o", obj)
        return obj
    objects = [compile("manager/target/band11/stage2.c", "stage2"),
               compile("runtime/loader/canopus_arm_reloc.c", "stage2-reloc"),
               compile("runtime/loader/canopus_elf32_loader.c", "stage2-elf")]
    def link(name, objects):
        elf = out / (name + ".elf")
        run("ld.lld", "-static", "--gc-sections", "--emit-relocs", "-e", f"canopus_band11_{name}_entry",
            "-T", ROOT / "scripts/canopus_band11_stage.ld", "-o", elf, *objects)
        binary = linked_binary(elf)
        (out / (name + ".bin")).write_bytes(binary)
        return binary
    stage2 = link("stage2", objects)
    header.write_text(header.read_text() + f"#define B11_STAGE2_SIZE {len(stage2)}u\n#define B11_STAGE2_CRC 0x{zlib.crc32(stage2):08x}u\n")
    stage1 = link("stage1", [compile("manager/target/band11/stage1.S", "stage1-entry"),
                             compile("manager/target/band11/stage1.c", "stage1")])
    if not 32 < len(stage1) < 16384 or len(stage2) > 32768:
        raise ValueError("unexpected stage size")
    if stage1[4:8] != bytes(4):
        raise ValueError("stage1 mailbox patch offset drifted")
    return stage1, stage2


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", default=TARGET)
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--supervisor", type=Path, help="exact target verified ET_REL; otherwise build it")
    parser.add_argument("--firmware", type=Path)
    parser.add_argument("--check", action="store_true", help="check generated Lua without writes")
    args = parser.parse_args()
    source, profile = render(args.target)
    if args.check:
        if (FAMILY / "main.lua").read_text() != source:
            parser.error("Band 11 main.lua is stale")
        print("Band 11 production Lua is current; device validation pending")
        return
    if args.supervisor is None:
        env = dict(os.environ, CANOPUS_TARGET=TARGET)
        if args.output_dir:
            env["CANOPUS_BAND11_OUTPUT_DIR"] = str(args.output_dir.resolve())
        if args.firmware:
            env["CANOPUS_BAND11_FIRMWARE"] = str(args.firmware.resolve())
        subprocess.run([str(ROOT / "scripts/build_canopus_supervisor.sh")], cwd=ROOT, env=env, check=True)
        return
    out = (args.output_dir or FAMILY).resolve()
    work = out / "build" / args.target
    work.mkdir(parents=True, exist_ok=True)
    unexpected = [p.name for p in out.iterdir() if p.is_file() and p.name != "main.lua" and p.suffix != ".bin"]
    if unexpected:
        parser.error("non-watchface files in output root: " + ", ".join(sorted(unexpected)))
    firmware_path = args.firmware or ROOT / "fwbins" / TARGET / "vela_ap.bin"
    firmware = firmware_path.read_bytes()
    if hashlib.sha256(firmware).hexdigest() != profile["firmware_sha256"]:
        parser.error("firmware hash differs from target pack")
    run(ROOT / "target/debug/canopus", "verify", args.supervisor, "--target", TARGET, "--targets-dir", ROOT / "targets")
    supervisor = args.supervisor.read_bytes()
    stage1, stage2 = build_stages(work, supervisor)
    fingerprints = [0x0c91e540, 0x0c91e594, 0x0c36c6d8, 0x0c3507e8,
                    0x0c34cd2c, 0x0c914f64, 0x0c6ab350]
    # Fixed cache leaves and their PC-relative literals, including the enabled
    # I-cache branch. Every word is checked on-device before entering either.
    fingerprints += list(range(0x0c930218, 0x0c930224, 4)) + [0x0c930228]
    fingerprints += list(range(0x0c0c1808, 0x0c0c1824, 4)) + [0x0c0c1828]
    native_profile = dict(target_id=TARGET, loader_family="lua-owned-stage1-stage2",
                          status="STATIC_RECOVERED", device_status="NOT_PROBED")
    native_profile.update({f"{name}_{key}": value for name, data in (("stage1",stage1),("stage2",stage2),("supervisor",supervisor))
                           for key,value in (("size",len(data)),("crc",zlib.crc32(data)))})
    profile_lua = "return {\n" + "".join(f"  {k} = {json.dumps(v)},\n" for k,v in native_profile.items())
    profile_lua += "  fingerprints = {\n" + "".join(f"    {{0x{a:08x}, 0x{struct.unpack_from('<I', firmware, a - 0x0c0c0000)[0]:08x}}},\n" for a in fingerprints) + "  },\n}\n"
    resources = {"main.lua": source.encode(), "manager_icon.bin": (ROOT / "watchfaces/canopus-installer/manager_icon.bin").read_bytes(),
                 f"canopus_loader_profile-{TARGET}.bin": profile_lua.encode(),
                 f"canopus_stage1-{TARGET}.bin": stage1, f"canopus_stage2-{TARGET}.bin": stage2,
                 f"canopus_supervisor-{TARGET}.bin": supervisor}
    manifest = dict(target_id=TARGET, firmware_sha256=profile["firmware_sha256"],
                    artifact_kind="complete-flat-installer-resources", native_loader_status="STATIC_TEST_CANDIDATE",
                    device_status="NOT_PROBED", supervisor_included=True,
                    reentry_unwind_leaks_path=profile["reentry_unwind_leaks_path"],
                    resources={name:dict(size=len(data),sha256=hashlib.sha256(data).hexdigest()) for name,data in resources.items()})
    archive = work / f"canopus-installer-prod-{TARGET}.zip"
    with zipfile.ZipFile(archive, "w", compression=zipfile.ZIP_DEFLATED) as bundle:
        for name, data in resources.items():
            info = zipfile.ZipInfo(name, date_time=(2026,9,9,0,0,0)); info.compress_type=zipfile.ZIP_DEFLATED
            bundle.writestr(info, data)
    for name,data in resources.items():
        (out / name).write_bytes(data)
        temporary = FAMILY / (name + ".tmp")
        temporary.write_bytes(data); temporary.replace(FAMILY / name)
    (work / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"Pack this directory (main.lua + .bin files only): {out}")
    print(f"Resource ZIP: {archive}")
    print(f"stage1={len(stage1)} stage2={len(stage2)} Supervisor={len(supervisor)} bytes; device NOT_PROBED")

if __name__ == "__main__":
    main()
