#!/usr/bin/env python3
"""Validate signed payloads and generate one production watchface per device."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import struct
import subprocess
import tempfile
import tomllib
import zipfile

ROOT = Path(__file__).resolve().parents[1]
PRODUCTS = {
    'bluetooth-audio': ('bluetooth_audio', 'Bluetooth Audio', 262144,
                        ['appicon_headphones.bin']),
    'lyra-player': ('lyra_player', 'Lyra Player', 393216,
                    ['appicon_lyra.bin', 'lyra-previous.bin', 'lyra-play.bin',
                     'lyra-pause.bin', 'lyra-next.bin']),
}
SUPPORTED = ['xiaomi-band-10-pro-3.101.036', 'xiaomi-band-10-pro-3.101.043',
             'xiaomi-band-11-4.100.139']


def lua(value):
    if value is None:
        return 'nil'
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, dict):
        return '{' + ',\n'.join('[' + lua(k) + '] = ' + lua(v) for k, v in value.items()) + '}'
    if isinstance(value, list):
        return '{' + ','.join(map(lua, value)) + '}'
    return str(value)


def render(product, targets):
    if not targets or len({t.rsplit('-', 1)[0] for t in targets}) != 1:
        raise ValueError('a watchface must contain exactly one device family')
    token, title, maximum, assets = PRODUCTS[product]
    configs = {}
    for target in targets:
        if target not in SUPPORTED:
            raise ValueError('unsupported production target: ' + target)
        pack = tomllib.loads((ROOT / 'targets' / target / 'target.toml').read_text())
        configs[pack['firmware_version']] = dict(id=target, firmware=pack['firmware_sha256'],
            runtime_pending=False,
            build=pack.get('firmware_build'))
    config = dict(token=token, title=title, max_size=maximum, stem=product,
                  assets=assets, targets=configs)
    family = ROOT / 'watchfaces/canopus-installer-prod/xiaomi-band-11'
    source = (ROOT / 'watchfaces/module-installer-prod/src/main.lua').read_text()
    replacements = {
        '-- @CONFIG@': 'local CONFIG = ' + lua(config),
        '-- @PROGRESS@': 'local progress = (function()\n' + (family / 'src/progress.lua').read_text() + '\nend)()',
    }
    for marker, replacement in replacements.items():
        if source.count(marker) != 1:
            raise ValueError('missing template marker: ' + marker)
        source = source.replace(marker, replacement)
    return '-- Generated by Canopus/scripts/build_module_installer_prod.py.\n' + source, config


def verify_signature(receipt):
    source = (ROOT / 'manager/service/canopus_supervisor_platform.c').read_text()
    match = re.search(r's_installer_public_key\[32\]\s*=\s*\{(.*?)\};', source, re.S)
    if not match:
        raise ValueError('Supervisor trust key not found')
    public = bytes(int(x, 16) for x in re.findall(r'0x([0-9a-fA-F]{2})', match[1]))
    if len(public) != 32:
        raise ValueError('invalid Supervisor trust key')
    with tempfile.TemporaryDirectory(prefix='canopus-receipt-verify-') as temp:
        p = Path(temp)
        (p / 'public.der').write_bytes(bytes.fromhex('302a300506032b6570032100') + public)
        (p / 'prefix').write_bytes(receipt[:192])
        (p / 'signature').write_bytes(receipt[192:])
        subprocess.run(['openssl', 'pkeyutl', '-verify', '-pubin', '-keyform', 'DER',
                        '-inkey', str(p / 'public.der'), '-rawin', '-in', str(p / 'prefix'),
                        '-sigfile', str(p / 'signature')], check=True, capture_output=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--product', choices=PRODUCTS, required=True)
    parser.add_argument('--target', action='append', required=True)
    parser.add_argument('--payload-dir', type=Path, required=True)
    parser.add_argument('--assets-dir', type=Path, required=True)
    parser.add_argument('--output-dir', type=Path, required=True)
    args = parser.parse_args()
    if len(set(args.target)) != len(args.target):
        parser.error('duplicate target')
    groups = {}
    for target in args.target:
        if target not in SUPPORTED:
            parser.error('unsupported target: ' + target)
        device = target.rsplit('-', 1)[0]
        groups.setdefault(device, []).append(target)
    base = args.output_dir
    for device, targets in groups.items():
        check = argparse.Namespace(**vars(args))
        check.target, check.output_dir = targets, base / device
        build_device(check, validate_only=True)
    # Preserve the previous mixed-device resources as build history. The prod
    # root becomes a container of device folders, just like the framework.
    previous = [p for p in base.iterdir() if p.is_file() and
                (p.name == 'main.lua' or p.suffix == '.bin')] if base.exists() else []
    # Old mixed-device archives must not look like the current release.
    previous += [p for p in (base / 'build' / (args.product + '-prod.zip'),
                             base / 'build' / 'manifest.json') if p.is_file()]
    if previous:
        import time
        history = base / 'build' / ('previous-flat-' + str(time.time_ns()))
        history.mkdir(parents=True)
        for path in previous:
            path.replace(history / path.name)
    for device, targets in groups.items():
        args.target = targets
        args.output_dir = base / device
        build_device(args)
    docs = base / 'docs'
    docs.mkdir(exist_ok=True)
    (docs / 'README.md').write_text(
        '# ' + PRODUCTS[args.product][1] + ' production installers\n\n'
        'Select a device folder, not this parent directory:\n\n'
        '- `xiaomi-band-10-pro/`: firmware 3.101.036 and 3.101.043.\n'
        '- `xiaomi-band-11/`: firmware 4.100.139; exact-target private runtime included.\n\n'
        'The build selection controls which firmware versions are included in each device folder.\n'
        'Pack that folder\'s single main.lua and all .bin files. The folder\'s build/ contains its ZIP and hash manifest; docs/ is not packed.\n'
        'Update the framework Supervisor first: external installers use ordinary IO at /canopus/install.\n'
        'No execute recovery or debug access is included. Older mixed-device outputs are retained only as build history.\n')


def device_is_band11(targets):
    return any(t.startswith("xiaomi-band-11-") for t in targets)


def build_device(args, validate_only=False):
    source, config = render(args.product, args.target)
    resources = {'main.lua': source.encode()}
    for item in config['targets'].values():
        target = item['id']
        module = (args.payload_dir / target / (args.product + '.elf')).read_bytes()
        receipt = (args.payload_dir / target / 'receipt.bin').read_bytes()
        if not (512 <= len(module) <= config['max_size'] and module[:7] == b'\x7fELF\x01\x01\x01'
                and struct.unpack_from('<HH', module, 16) == (1, 40)):
            raise ValueError('invalid ARM payload: ' + target)
        fixed = lambda off, size: receipt[off:off + size].split(b'\0', 1)[0]
        if not (len(receipt) == 256 and struct.unpack_from('<3I', receipt) == (0x31494d43, 1, 256)
                and fixed(32, 32).decode() == config['token'] and fixed(64, 48).decode() == target
                and receipt[112:144].hex() == item['firmware']
                and struct.unpack_from('<I', receipt, 24)[0] == len(module)
                and receipt[144:176] == hashlib.sha256(module).digest()):
            raise ValueError('receipt/payload/target mismatch: ' + target)
        verify_signature(receipt)
        resources[args.product + '-' + target + '.bin'] = module
        resources[args.product + '-' + target + '.cmi.bin'] = receipt
    for name in config['assets']:
        data = (args.assets_dir / name).read_bytes()
        w, h, stride, reserved = struct.unpack_from('<4H', data, 4)
        expected = 117 if name.startswith('appicon_') else 64
        if not (data[:4] == b'\x19\x10\0\0' and (w, h, stride, reserved) ==
                (expected, expected, expected * 4, 0) and len(data) == 12 + h * stride):
            raise ValueError('invalid icon: ' + name)
        resources[name] = data
    if validate_only:
        return
    # Validate everything before replacing generated payloads in the prod root.
    out = args.output_dir
    out.mkdir(parents=True, exist_ok=True)
    docs = out / 'docs'
    docs.mkdir(exist_ok=True)
    generated = {args.product + '-' + target + suffix for target in SUPPORTED
                 for suffix in ('.bin', '.cmi.bin')}
    unexpected = [p for p in out.iterdir() if p.is_file()
                  and p.name not in set(resources) | generated | {'README.md'}]
    if unexpected:
        raise ValueError('non-watchface root files: ' + str(unexpected))
    if (out / 'README.md').exists():
        # Preserve the previous documentation; the packer accepts .lua/.bin only.
        old_readme = docs / 'README-previous.md'
        if old_readme.exists() and old_readme.read_bytes() != (out / 'README.md').read_bytes():
            raise ValueError('previous documentation already differs')
        (out / 'README.md').replace(old_readme)
    for p in out.iterdir():
        if p.is_file() and p.name in generated and p.name not in resources:
            p.unlink()
    for name, data in resources.items():
        (out / name).write_bytes(data)
    names = {p.name for p in out.iterdir() if p.is_file()}
    if names != set(resources):
        raise ValueError('unexpected stale resources: ' + str(names - set(resources)))
    manifest = dict(product=args.product, targets=config['targets'], device_status='NOT_PROBED',
                    resources={k: dict(size=len(v), sha256=hashlib.sha256(v).hexdigest())
                               for k, v in resources.items()})
    build = out / 'build'
    build.mkdir(exist_ok=True)
    (build / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    with zipfile.ZipFile(build / (args.product + '-prod.zip'), 'w', zipfile.ZIP_DEFLATED) as bundle:
        for name, data in resources.items():
            bundle.writestr(name, data)
    pending = any(item['runtime_pending'] for item in config['targets'].values())
    (docs / 'README.md').write_text(
        '# ' + config['title'] + ' production installer\n\n'
        'Build targets: ' + ', '.join(args.target) + '\n\n'
        'Pack only main.lua and the .bin files in this directory. Requires the matching resident Canopus Supervisor.\n'
        'Opening the watchface installs the signed module in the disabled state; it does not enable or bootstrap the framework.\n'
        'Use an updated Supervisor with /canopus/install. External Lua uses ordinary IO only; no execute recovery or debug access is embedded.\n'
        + ('Runtime adaptation is pending.\n' if pending else '') +
        ('Band 11 adapters pass compiled ARM/firmware ABI tests; physical radio/audio/display remain NOT_PROBED.\n' if device_is_band11(args.target) else '') +
        'The framework prepares /data/canopus/inbox before external installation. Signatures are verified against the Supervisor trust key during packaging; no private key is packaged.\n')
    print('Prod resources: ' + str(out))
    print('Targets: ' + ', '.join(args.target))
    print('Flat files: ' + str(len(resources)) + '; signatures and hashes verified')


if __name__ == '__main__':
    main()
