#!/usr/bin/env python3
"""Generate the private Band 11 native addresses from exact-target records."""
import argparse
import json
import re
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def metadata(target_id):
    root = ROOT / 'targets' / target_id
    pack = tomllib.loads((root / 'target.toml').read_text())
    profile = json.loads((root / 'loader/native-bindings.json').read_text())
    if profile['schema'] != 1 or any(profile[k] != pack[k] for k in ('target_id', 'firmware_sha256')):
        raise ValueError('native profile identity differs from target pack')
    symbols = {}
    for path in (root / 'symbols').glob('*.json'):
        record = json.loads(path.read_text())
        if record['name'] in symbols:
            raise ValueError(f'duplicate symbol name: {record["name"]}')
        symbols[record['name']] = record
    addresses = {}
    for macro, name in profile['bindings'].items():
        if not re.fullmatch(r'[A-Z][A-Z0-9_]+', macro):
            raise ValueError(f'invalid macro: {macro}')
        record = symbols[name]
        if record['target_id'] != target_id or record['provenance']['firmware_sha256'] != pack['firmware_sha256']:
            raise ValueError(f'wrong firmware provenance: {name}')
        if record['status'] != 'STATIC_RECOVERED' or record['policy'] != 'restricted':
            raise ValueError(f'native test ABI requires reviewed static evidence: {name}')
        for evidence in record['proof']['evidence_ids']:
            if not (root / 'evidence' / f'{evidence}.json').is_file():
                raise ValueError(f'missing native evidence: {evidence}')
        entry = int(record['entry_address'], 16)
        value = int(record['callable_address'], 16) if record['kind'] == 'function' else entry
        if record['kind'] == 'function' and (entry & 1 or value != entry | 1):
            raise ValueError(f'invalid Thumb callable: {name}')
        addresses[macro] = value
    return pack, profile, addresses


def render(target_id):
    pack, _, addresses = metadata(target_id)
    return ('/* Generated by generate_band11_native_config.py. Static private ABI; device pending.\n'
            f' * {target_id}\n * SHA256 {pack["firmware_sha256"]} */\n'
            '#ifndef CANOPUS_BAND11_ADDRESSES_H\n#define CANOPUS_BAND11_ADDRESSES_H\n' +
            ''.join(f'#define {name} 0x{value:08X}u\n' for name, value in sorted(addresses.items())) +
            '#endif\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--target', required=True)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'targets' / args.target / 'generated/canopus_band11_addresses.h'
    output = render(args.target)
    if args.check:
        if path.read_text() != output:
            raise ValueError(f'stale native addresses: {path}')
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(output)


if __name__ == '__main__':
    main()
